### ISSUE TITLE
Intermittent Aws::CloudSearchDomain::Errors::SignatureDoesNotMatch

### ISSUE THREAD

**Issue by alexfarrill** [aws/aws-sdk-ruby#929] opened 2015-09-21 05:26 UTC
Hi, we are seeing the error Aws::CloudSearchDomain::Errors::SignatureDoesNotMatch thrown intermittently in our logs when searching a domain in CloudSearch.

When I try to reproduce the search, it always succeeds.  What's a good way to debug this?

Thanks

Alex

**Comment by trevorrowe** [comment] 2015-09-21 20:17
Does the error message contain the expected string to sign and canonical request? If so, it would be possible, with a small patch, to get the SDK to save these values that it computed and then compare then to the expected values from the service.

**Comment by alexfarrill** [comment] 2015-09-21 20:34
Yes, the error message does include the Canonical String for this request and String-to-Sign

**Comment by trevorrowe** [comment] 2015-10-15 21:46
I've put together a monkey patch that you can apply to your SDK that will capture the string to sign and canonical request. If you could add these and then rescue the signature does not match error, then we can compare the strings to see where things have gone wrong.

```ruby
require 'aws-sdk'

module Aws
  module Signers
    class V4
      class << self
        def sign(context)
          signer = new(
            context.config.credentials,
            context.config.sigv4_name,
            context.config.sigv4_region
          )
          req = signer.sign(context.http_request)
          datetime = context.http_request.headers['X-Amz-Date']
          context[:string_to_sign] = signer.send(:string_to_sign,
            context.http_request,
            datetime,
            context.http_request.headers['X-Amz-Content-Sha256']
          )
          context[:canonical_request] = signer.send(:canonical_request,
            context.http_request,
            context.http_request.headers['X-Amz-Content-Sha256']
          )
          req
        end
      end
    end
  end
end
```

With this in place, you can do something like this:

```ruby
begin
  # your code here
rescue Aws::CloudSearchDomain::Errors::SignatureDoesNotMatch => error
  # these are the values the SDK computed client-side
  puts error.context[:string_to_sign]
  puts error.context[:canonical_request]

  # this contains the values computed server-side
  puts error.message
end
```

**Comment by alexfarrill** [comment] 2015-10-15 22:29
Thanks, I will patch it and get back to you

**Comment by alexfarrill** [comment] 2015-10-23 22:12
Hi Trevor, I emailed you earlier this week with the log output.  Let me know if there's anything else I can do to help debug.

**Comment by trevorrowe** [comment] 2015-10-26 20:31
Sorry for the slow response. I was pretty swamped last week. I'll try to take a look at that shortly. I did get the email.

**Comment by alexfarrill** [comment] 2015-11-03 18:16
Thanks Trevor, let me know if there's anything we can do to help.

**Comment by awood45** [comment] 2015-11-20 21:41
Picking this up, there is a tiny difference in the canonical request we generated versus the one generated by the server.

On our end, this is in the request:
`content-length:0`

On the server end, they expected:
`content-length:`

I'm going to investigate this further, see what the spec indicates should happen.

**Comment by alexfarrill** [comment] 2015-11-20 23:16
Awesome, thank you

**Comment by awood45** [comment] 2015-11-20 23:21
It could be helpful if there is any way you can capture a wire trace of this happening, to confirm that we are correctly signing the request (to determine if the problem is client side or server side).

To do this:
```ruby
client = Aws::CloudSearchDomain::Client.new(http_wire_trace: true, endpoint: endpoint)
```

I realize this is potentially very noisy in your logs, so I understand if you can't do it, but it's helpful if you can.

I also think that the intermittent nature of this problem implies that adding retries around your call for this error should be effective. Let me know if it is not.

**Comment by alexfarrill** [comment] 2015-11-23 21:31
Thanks Alex, we're enabling the http_wiretrace and I'll email you the log output next time the error occurs.  I also added a retry, thanks for that info

**Comment by awood45** [comment] 2015-11-23 23:47
The related issue makes me suspect strongly that there is a deeper issue here (they had a non-zero content length that still had a blank content-length value expected server side).

**Comment by awood45** [comment] 2015-11-24 18:23
So, if content-length is added after signing, then your request should work. Locally, my default handler order has content-length headers added after signing, which is why I can't recreate this locally.

What I'd like to see is your handler ordering and priority, to see if your handler order differs from mine. Can you give me the output of:
```ruby
client = Aws::CloudSearchDomain::Client.new(opts) # However you normally construct it.
client.handlers.entries.each { |h| puts "#{h.class}: #{h.step} #{h.priority}" }; nil
client.handlers.to_a
```

This will help me debug.

**Comment by alexfarrill** [comment] 2015-11-24 18:46
Sure, here's the output from that:

[Seahorse::Client::NetHttp::Handler, Seahorse::Client::Plugins::ContentLength::Handler, Aws::Json::ErrorHandler, Aws::Plugins::RequestSigner::Handler, Aws::Plugins::RetryErrors::Handler, Aws::Rest::Handler, Aws::Plugins::UserAgent::Handler, Seahorse::Client::Plugins::Endpoint::Handler, Aws::Plugins::ParamValidator::Handler, Seahorse::Client::Plugins::RaiseResponseErrors::Handler, Aws::Plugins::ParamConverter::Handler, Aws::Plugins::ResponsePaging::Handler, Seahorse::Client::Plugins::ResponseTarget::Handler]

**Comment by awood45** [comment] 2015-11-24 19:13
Can you rerun and provide the other output too? Sorry, need both to confirm a suspicion.

**Comment by alexfarrill** [comment] 2015-11-24 19:18
Yep, sorry, missed that:

irb(main):011:0> client.handlers.entries.each { |h| puts "#{h.handler_class}: #{h.step} #{h.priority}" }; nil
Seahorse::Client::Plugins::Endpoint::Handler: build 90
Seahorse::Client::NetHttp::Handler: send 50
Seahorse::Client::Plugins::RaiseResponseErrors::Handler: validate 95
Seahorse::Client::Plugins::ResponseTarget::Handler: initialize 90
Seahorse::Client::Plugins::ContentLength::Handler: sign 0
Aws::Plugins::ParamConverter::Handler: initialize 50
Aws::Plugins::ParamValidator::Handler: validate 50
Aws::Plugins::UserAgent::Handler: build 50
Aws::Plugins::RetryErrors::Handler: sign 99
Aws::Plugins::RequestSigner::Handler: sign 50
Aws::Plugins::ResponsePaging::Handler: initialize 90
Aws::Query::Handler: build 50
Aws::Xml::ErrorHandler: sign 50
=> nil
irb(main):012:0> client.handlers.to_a
=> [Seahorse::Client::NetHttp::Handler, Seahorse::Client::Plugins::ContentLength::Handler, Aws::Xml::ErrorHandler, Aws::Plugins::RequestSigner::Handler, Aws::Plugins::RetryErrors::Handler, Aws::Query::Handler, Aws::Plugins::UserAgent::Handler, Seahorse::Client::Plugins::Endpoint::Handler, Aws::Plugins::ParamValidator::Handler, Seahorse::Client::Plugins::RaiseResponseErrors::Handler, Aws::Plugins::ParamConverter::Handler, Seahorse::Client::Plugins::ResponseTarget::Handler]

**Comment by awood45** [comment] 2015-11-24 22:04
Okay, I have some more clarity on this issue.

What you're seeing is a two-stage error:

1. Your initial request generates a 500 Error, for whatever reason. The SDK recognizes this and attempts to retry.
2. On the second request only, we additionally sign the content-length header, which generates the signature error. We believe this to be a server-side issue.

I don't know what is causing the 500 Error to begin with, but if you're adding retries around that successfully, then that's a viable workaround. If you're consistently seeing 500 Errors, then you should separately reach out to the service team via AWS Support to investigate that.

**Comment by alexfarrill** [comment] 2015-11-25 18:02
Thanks Alex, I think this is a good workaround and the number of errors has actually dropped off since I first reported this.  I'm only seeing this error every few days now whereas before we were seeing it multiple times per day.  I'm not sure if that's because of a change in AWS or a change in our traffic patterns, but that in combination with the retries should be a good enough solution for now.  Thanks

**Comment by awood45** [comment] 2015-11-25 18:09
Glad to hear. I'm continuing to track this issue to resolution overall, but it sounds like we can close this one. Feel free to chime in issue #1014 (almost the exact same thing, different cause of the initial 500) if you have more issues.

Also, if the frequency of this is a problem for you, I definitely encourage you to reach out to the service team via AWS Support. If you're seeing this, you're probably not the only one, and your debug information has been helpful.

**Closed by awood45** 2015-11-25 18:09 UTC
Labels: bug, information requested, Version 2
