### ISSUE TITLE
CognitoIdentity: Tag Resource - Access Denied

### ISSUE THREAD

**Issue by OBCENEIKON** [aws/aws-sdk-ruby#2173] opened 2019-11-21 17:48 UTC
Issue Description:
When attempting to `list_tags_for_resource` I am getting an access denied error.

Gem Name and Version:
`aws-sdk-cognitoidentity` `1.18.0`

Version of Ruby:
`2.5.0`
OS environment:
docker container running `Debian GNU/Linux 9 (stretch)`

Code Snippets / Steps to Reproduce:
```
tags = []
client.list_tags_for_resource(resource_arn: identity_pool_id).tags.each do |tag|
  tags << tag
end
tags
```

Error Message:
```
Aws::CognitoIdentity::Errors::AccessDeniedException User: arn:aws:sts::245319550715:assumed-role/admin/admin is not authorized to perform: cognito-identity:ListTagsForResource on resource: us-east-1:d64ff45f-ecf5-4c8d-9196-8e06bf4dfd77
/usr/local/bundle/gems/aws-sdk-core-3.80.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.80.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.80.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.80.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.80.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.80.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.80.0/lib/seahorse/client/request.rb:70:in `send_request'
/usr/local/bundle/gems/aws-sdk-cognitoidentity-1.18.0/lib/aws-sdk-cognitoidentity/client.rb:962:in `list_tags_for_resource'
```

**Comment by mullermp** [comment] 2019-11-21 18:23
I see that you are providing `identity_pool_id` and not `identity_pool_arn` -- you need to provide the ARN since the input is `resource_arn` and not `resource_id`. I was able to reproduce this error when only providing the ID.

**Comment by OBCENEIKON** [comment] 2019-11-22 16:15
Forgive me if I am not seeing this in the documentation, but I cannot seem to find a way to retrieve the `identity_pool_arn` through the API.

Describe Identity Pool Example Response:
```
{
   "AllowClassicFlow": boolean,
   "AllowUnauthenticatedIdentities": boolean,
   "CognitoIdentityProviders": [ 
      { 
         "ClientId": "string",
         "ProviderName": "string",
         "ServerSideTokenCheck": boolean
      }
   ],
   "DeveloperProviderName": "string",
   "IdentityPoolId": "string",
   "IdentityPoolName": "string",
   "IdentityPoolTags": { 
      "string" : "string" 
   },
   "OpenIdConnectProviderARNs": [ "string" ],
   "SamlProviderARNs": [ "string" ],
   "SupportedLoginProviders": { 
      "string" : "string" 
   }
}
```

List Identity Pools Example Response:
```
{
   "IdentityPools": [ 
      { 
         "IdentityPoolId": "string",
         "IdentityPoolName": "string"
      }
   ],
   "NextToken": "string"
}
```
Maybe I'm missing something here?

**Comment by mullermp** [comment] 2019-11-22 18:09
When looking at the [cognito tagging docs](https://docs.aws.amazon.com/cognito/latest/developerguide/tagging.html) for resource-arn, it seems to me that it's only retrievable via the web console unfortunately. I may be wrong on this too. You may need to store this value somehow -- but from the resource ARN, you should be able to extract out the identity pool id and use it however you need. I plan on releasing a generic ARN parser for the core gem if that helps you here.

Next steps on our side, I think I want to relay this feedback to the cognito team to see if they can output the ARN in their describe API because it seems like a bad customer experience for it not to be.

**Comment by mullermp** [comment] 2019-11-22 18:09
@ajredniwja can you follow up with service team discussions on this?

**Comment by ajredniwja** [comment] 2019-11-22 18:21
@mullermp I will reach out to the service team and update here whenever I hear back from them.

**Comment by OBCENEIKON** [comment] 2019-11-22 20:09
Thank you for all of your help @mullermp.
Unfortunately, none of our interactions are done through the console and it's all done through the API. So for our needs, we would need for the ARN to be retrievable from the API.
I'll check back frequently for the generic ARN parser.

**Comment by mullermp** [comment] 2019-11-27 19:20
@OBCENEIKON Cognito Identity team acknowledged this feature request and should queue it up some time after re:Invent. Two alternatives are: 1) describe API returns an ARN or 2) tagging APIs can use a resource_id.

In the mean time, you can construct the ARN string yourself as a work around:

```
arn:aws:cognito-identity:<AWS region>:<AWS Account id>:identitypool/<identity pool id>
```

I will be publishing an ARN/ARN parser class sometime soon :). I am going to close this for now. Please ping me here if there are any issues.

**Closed by mullermp** 2019-11-27 19:20 UTC
Labels: guidance, service-api
