### ISSUE TITLE
Aws::CloudFormation::Stack.stack_name regression

### ISSUE THREAD

**Issue by lwoggardner** [aws/aws-sdk-ruby#1646] opened 2017-10-23 10:11 UTC
### Issue description
In version 2 Aws::CloudFormation::Stack.new(<stack_id>).stack_name would invoke DescribeStack api and return just the stack name.

In version 3 it is just an alias to #name, and thus returns whatever was passed into the constructor, which might have been a full stack id arn.

### Gem name 
aws-sdk-cloudformation 1.2.0

### Version of Ruby, OS environment
ruby 2.3 windows and linux

### Code snippets / steps to reproduce
```ruby
cfnr = Aws::CloudFormation::Resource.new()
stack_id = 'arn:aws:cloudformation:ap-southeast-2:<redacted>:stack/AStackName/<uuid>'
cfnr.stack(stack_id).stack_name
# expect 'AStackName', get 'arn:aws:cloudformation....'
```

**Comment by cjyclaire** [comment] 2017-10-23 17:15
@lwoggardner Thanks for the info. I can reproduce this locally. A workaround is by calling `stack.stack_id` instead, it will return the arn value. This is actually a correct behavior for stack that `#stack_name` returns name only and `#stack_id` returns the arn.

Taking a look at V2 about the difference behavior now ...

**Comment by lwoggardner** [comment] 2017-10-23 21:36
@cjyclaire  I have a stack_id and I'm trying to get just the name.  My (temporary) workaround is to monkey patch Aws::CloudFormation:;Stack  roughly like

```ruby
class Aws::CloudFormation::Stack
  def stack_name
    name.start_with?('arn:') ? name.split('/')[1] : name
  end
end
```

**Comment by lwoggardner** [comment] 2017-10-24 10:08
Similar issue exists with Aws::EC2::KeyPair#key_name, it is just an alias to the constructor value #name, so previously where calling this would raise Aws::EC2::Errors::InvalidKeyPairNotFound it now just returns the string.

```ruby
begin
    ec2_resource.key_pair(input_value).key_name # in v3 this now returns input_value instead of raising 
rescue Aws::EC2::Errors::InvalidKeyPairNotFound => ec2_error
   #if input_value key does not exist fall back to master_keyname
   ec2_resource.key_pair(master_keyname).key_name
end
```

**Comment by cjyclaire** [comment] 2017-11-02 21:59
A short summary for this regression here, so in V2, every attribute is fetched from [data](https://github.com/aws/aws-sdk-ruby/blob/version-2/aws-sdk-resources/lib/aws-sdk-resources/builder_sources.rb#L60), in V3, since we are code-generation those resource objects, their identifiers are not loaded from data anymore, those identifiers helps with object initialization instead. 

Personally, I think using those non-matching input to expect a matching result is not a good practice there. Those identifiers are chosen for resources for a reason usually, for example, as for "Stack" object, "stack_name" is a require member while "stack_arn" is not. We have the promise to keep v2 compatibility there, however I'm not sure whether your usage case is a validate scenario that we would like to keep. Let me know how this usage is beneficial to you, any limitations there?

Open to hear your thoughts and happy to have discussion : )

**Comment by awood45** [comment] 2017-11-13 20:33
It's quite possible as well that this is a shortcoming with the resource model, and that we're unfortunately running in to it now. Migrating to client calls is the cleanest solution, though I definitely appreciate that this is a major overhaul, potentially. We're going to see if it's feasible to update the resource model, and if not, if it's feasible to customize this particular resource to match V2 behavior.

**Comment by mullermp** [comment] 2019-09-10 22:15
Going to close this issue for now. Please reopen if this is still any concern.

**Closed by mullermp** 2019-09-10 22:15 UTC
Labels: resource-model, v3, wont-fix
