### ISSUE TITLE
Kinesis Firehose data not being unescaped when delivered to S3

### ISSUE THREAD

**Issue by tommybonderenka** [aws/aws-sdk-ruby#1847] opened 2018-08-01 14:09 UTC
### Issue description
Using the `put_record_batch` method on the `Aws::Firehose::Client`, every now and again the records being sent to the firehose are not unescaped and still contain the `data:` key when delivered to S3. 

Example: 
```
{"data":"{\"object_type\": \"foo_bar\", \"body\": {\"id\":\"80c2944f-475d-47fb-9817-0fe4eb099c8b\",\"created_at\":\"2016-01-08T17:09:26.491-10:00\",\"updated_at\":\"2018-07-28T03:29:57.274-10:00\",\"deleted\":false,\"name\":\"Foo Bar\",\"username\":\"fbar\",\"email\":\"\",\"status\":\"Active\"}, \"meta\": {\"sent_at\": \"2018-07-28T13:30:13.127Z\",\"env\": \"production\"}}\n"}
```

Note that when I manually resend these models to the Firehose, everything works fine and they are delivered to S3 normally. 

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
`aws-sdk` `2.11.33`

### Version of Ruby, OS environment
Ruby: `2.3.7`
OS: macOS High Sierra `10.13.5`

### Code snippets / steps to reproduce
```
def initialize(stream: ApplicationConfig[:foo_bar_stream_name])
    @stream_name = stream
end

def put_batch(record_array)
  raise "Too many records in batch" if record_array.size > 500

  batch = record_array.collect do |data|
    data = data.to_json unless data.kind_of?(String)
    {data: data}
  end

  response = client.put_record_batch({
    delivery_stream_name: @stream_name,
    records: batch
  })

  if response.failed_put_count > 0
    response.request_responses.each.with_index do |record_response, index|
      next if record_response.error_code.blank?
      # resend the record, per Amazon docs
      put(batch[index])
    end
  end
end
```

**Comment by awood45** [comment] 2018-08-01 17:50
This looks like it's most likely an issue with the service - are you able to capture a wire trace of any of the problematic calls?

**Comment by tommybonderenka** [comment] 2018-08-01 17:53
I was thinking it was probably an issue with the service as well but wasn't sure. I don't have a wire trace of any of the problematic calls as of yet, though I will look into adding that to the calls to try and capture some more information.

**Comment by awood45** [comment] 2018-08-01 17:59
I'd recommend reaching out to AWS Support. I don't see anything about the client (there are no customizations, for example) that would indicate this would happen, it's a plain API call. If we see a wire trace showing we double-counted the data key, for example, that would be interesting.

It may also require grabbing some data from the `context.http_request` object - do you have a way to reproduce this predictably?

**Comment by tommybonderenka** [comment] 2018-08-01 18:00
I do not have a way to reproduce it predictably at this point, it seems very random. The records that it effects have almost nothing in common and the timestamps vary greatly, it just kinda "happens" sometimes.

**Comment by srchase** [comment] 2018-11-20 17:00
@tommybonderenka 

I'm going to close this issue for now.  If you are able to capture a wire trace, or have feedback from the service, let us know and we can re-open.

**Closed by srchase** 2018-11-20 17:00 UTC
Labels: information requested, service-api
