### ISSUE TITLE
Numerous method redefinitions in aws-sdk-core

### ISSUE THREAD

**Issue by mbowen13** [aws/aws-sdk-ruby#2070] opened 2019-06-13 19:01 UTC
### Issue description
Many methods are redefined in aws-sdk-core when rake is ran

### Gem name

aws-sdk-core-3.54.2

### Version of Ruby, OS environment
Ruby 2.5.5, MacOS 10.14.5

### Code snippets / steps to reproduce
```rake```

Output
```

/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/plugin.rb:125: warning: method redefined; discarding old doc_default
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/aws-sdk-sts/client.rb:590: warning: method redefined; discarding old assume_role
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of assume_role was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/aws-sdk-sts/client.rb:849: warning: method redefined; discarding old assume_role_with_saml
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of assume_role_with_saml was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/aws-sdk-sts/client.rb:1177: warning: method redefined; discarding old assume_role_with_web_identity
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of assume_role_with_web_identity was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/aws-sdk-sts/client.rb:1257: warning: method redefined; discarding old decode_authorization_message
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of decode_authorization_message was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/aws-sdk-sts/client.rb:1327: warning: method redefined; discarding old get_caller_identity
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of get_caller_identity was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/aws-sdk-sts/client.rb:1574: warning: method redefined; discarding old get_federation_token
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of get_federation_token was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/aws-sdk-sts/client.rb:1715: warning: method redefined; discarding old get_session_token
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of get_session_token was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:565: warning: method redefined; discarding old batch_get_item
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of batch_get_item was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:818: warning: method redefined; discarding old batch_write_item
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of batch_write_item was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:887: warning: method redefined; discarding old create_backup
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of create_backup was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:961: warning: method redefined; discarding old create_global_table
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of create_global_table was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:1389: warning: method redefined; discarding old create_table
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of create_table was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:1462: warning: method redefined; discarding old delete_backup
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of delete_backup was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:1735: warning: method redefined; discarding old delete_item
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of delete_item was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:1867: warning: method redefined; discarding old delete_table
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of delete_table was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:1941: warning: method redefined; discarding old describe_backup
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of describe_backup was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:1987: warning: method redefined; discarding old describe_continuous_backups
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of describe_continuous_backups was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:2008: warning: method redefined; discarding old describe_endpoints
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of describe_endpoints was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:2041: warning: method redefined; discarding old describe_global_table
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of describe_global_table was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:2122: warning: method redefined; discarding old describe_global_table_settings
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of describe_global_table_settings was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:2231: warning: method redefined; discarding old describe_limits
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of describe_limits was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:2374: warning: method redefined; discarding old describe_table
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of describe_table was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:2404: warning: method redefined; discarding old describe_time_to_live
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of describe_time_to_live was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:2599: warning: method redefined; discarding old get_item
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of get_item was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:2683: warning: method redefined; discarding old list_backups
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of list_backups was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:2724: warning: method redefined; discarding old list_global_tables
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of list_global_tables was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:2782: warning: method redefined; discarding old list_tables
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of list_tables was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:2829: warning: method redefined; discarding old list_tags_of_resource
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of list_tags_of_resource was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:3166: warning: method redefined; discarding old put_item
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of put_item was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:3698: warning: method redefined; discarding old query
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of query was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:3808: warning: method redefined; discarding old restore_table_from_backup
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of restore_table_from_backup was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:3947: warning: method redefined; discarding old restore_table_to_point_in_time
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of restore_table_to_point_in_time was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:4387: warning: method redefined; discarding old scan
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of scan was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:4429: warning: method redefined; discarding old tag_resource
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of tag_resource was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:4513: warning: method redefined; discarding old transact_get_items
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of transact_get_items was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:4732: warning: method redefined; discarding old transact_write_items
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of transact_write_items was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:4769: warning: method redefined; discarding old untag_resource
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of untag_resource was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:4819: warning: method redefined; discarding old update_continuous_backups
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of update_continuous_backups was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:4888: warning: method redefined; discarding old update_global_table
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of update_global_table was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:5070: warning: method redefined; discarding old update_global_table_settings
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of update_global_table_settings was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:5464: warning: method redefined; discarding old update_item
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of update_item was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:5725: warning: method redefined; discarding old update_table
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of update_table was here
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:5797: warning: method redefined; discarding old update_time_to_live
/Users/michael.bowen/.rvm/gems/ruby-2.5.5@lex/gems/aws-sdk-core-3.54.2/lib/seahorse/client/base.rb:198: warning: previous definition of update_time_to_live was here
```

**Comment by cjyclaire** [comment] 2019-06-18 17:43
Hmmm we use `rake` for test, build and release and I couldn't reproduce those on OSX locally with  `rake, version 12.3.2`, with ruby version `2.3.4`, maybe I need to try `2.5.5`? Any more details about how did you see all those warnings? (multi thread env?)

**Comment by mbowen13** [comment] 2019-06-20 02:21
Yes, I used ruby version 2.5.5
You can also see that I am using rvm to store gems for my project.

**Comment by cjyclaire** [comment] 2019-06-27 23:47
Soft update, using rbenv
```
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin16]
```
rake
```
rake, version 12.3.2
```
I'm running tests for all sdk gems with rake but still cannot reproduce. 
Mind sharing a tiny script using sdk in your rakefile that produces the issue?

**Comment by mbowen13** [comment] 2019-06-28 00:50
Sure, let's do it.

**Comment by jonathanhefner** [comment] 2019-08-30 18:35
I am also seeing these using `ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]`.

I see them when running `rake test` in the [aws/aws-sdk-rails](https://github.com/aws/aws-sdk-rails) repo.

**Comment by jonathanhefner** [comment] 2019-10-02 19:14
@ajredniwja What kind of response are you looking for?  The issue can be reproduced by running `rake test` in the official [aws/aws-sdk-rails](https://github.com/aws/aws-sdk-rails) repo:
```bash
$ git clone git@github.com:aws/aws-sdk-rails.git
$ cd aws-sdk-rails
$ bundle
$ bundle exec rake test
```

I am running this using Ruby 2.6, on Linux: 
```bash
$ ruby -v
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
```

You can also test against `aws-sdk-ruby` master by adding the following line to `aws-sdk-rails/Gemfile`:
```ruby
gem 'aws-sdk-ses', git: 'https://github.com/aws/aws-sdk-ruby', glob: 'gems/aws-sdk-ses/*.gemspec'
```
And then running `bundle && bundle exec rake test`.  The warnings still occur.

p.s.  Apparently adding a tag (e.g. `closing-soon-if-no-response`) does not notify issue subscribers.  I did not receive a notification until the issue was marked as closed.  Just fyi, for future issues.

**Comment by mullermp** [comment] 2019-10-03 17:41
I'm able to reproduce this using Ruby 2.6.3. This is for cloning and running tests in the aws-sdk-**rails** repo and not the aws-sdk-**ruby** repo, however aws-sdk-**rails** does depend on ses and therefore core.

**Comment by mullermp** [comment] 2019-10-08 18:02
I've fixed this by setting `t.warning = false` in the Rakefile for the aws-sdk-rails package. I will close this issue.

**Closed by mullermp** 2019-10-08 18:02 UTC
Labels: investigating

**Comment by jonathanhefner** [comment] 2019-10-14 21:44
@mullermp  I don't think that would be a sufficient solution.  Here is a simpler reproduction:

```bash
$ irb -w
> require "aws-sdk-ses" # any client gem goes here
```

I've created #2137 to address the issue.  What do you think?

**Comment by mullermp** [comment] 2019-10-16 18:19
You're right on that one - I ideally wanted to fix it upstream (in the core package). I will do a review for that, thanks for helping us out!
