### ISSUE TITLE
How to extract Export Name from outputs

### ISSUE THREAD

**Issue by astratto** [aws/aws-sdk-ruby#1547] opened 2017-06-23 09:27 UTC
Hi,

Unless I'm missing something, Export Names are not extracted when listing the outputs of a Stack.

```
2.4.0 :002 > c = Aws::CloudFormation::Client.new(region: 'us-west-2')
=> #<Aws::CloudFormation::Client>

2.4.0 :004 > stack = Aws::CloudFormation::Stack.new('dev-test-vpc', c, region: 'us-west-2')
=> #<Aws::CloudFormation::Stack name="dev-test-vpc">

2.4.0 :005 > test = stack.outputs.find { |i| i.output_key =~ /MyOutput/ }
=> #<struct Aws::CloudFormation::Types::Output output_key="MyOutput1", output_value="1", description="Whatever">
```

Is there a reason why the export name is not there?

**Comment by awood45** [comment] 2017-06-26 16:36
I'm unable to reproduce this, and to be honest not sure what you're referring to. Can you refresh my memory on what you're expecting to find?

**Comment by astratto** [comment] 2017-06-26 16:44
@awood45 sure, thanks for looking into this.

CloudFormation outputs have a Key, Value, Description and optional Export name: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html

![image](https://user-images.githubusercontent.com/207754/27550282-05e770b8-5a97-11e7-9d20-3ff870fd7367.png)

The Export Name is not extracted, even when present.
Let me know if you need more info.

**Comment by awood45** [comment] 2017-06-26 17:06
It would be useful to see the output of the following:

```ruby
client = Aws::CloudFormation::Client.new(region: 'us-west-2')
client.describe_stacks(stack_name: 'dev-test-vpc')
```

Feel free to anonymize as needed, the question is if the service is returning the values you're expecting. If it is, then we may need to look at the model. If it is not, the issue does not lie with the SDK.

**Comment by astratto** [comment] 2017-06-26 17:22
Okay, using the SDK I get back a `Aws::CloudFormation::Types::DescribeStackOutput` with a `stacks` list of `Aws::CloudFormation::Types::Stack` that then have parameters of type `Aws::CloudFormation::Types::Output`.

```
#<struct Aws::CloudFormation::Types::Output output_key="MyOutput", output_value="output.value", description="Test output">
```

Nothing surprising, so I used the aws cli and the export names are not exposed there neither...
```
{ 
   "Description": "Test output",
   "OutputKey": "MyOutput",
   "OutputValue": "output.value"
},
```

And then found this: https://github.com/aws/aws-cli/issues/2637

**Comment by awood45** [comment] 2017-06-26 17:27
That's definitely a possible issue, that would be along the lines of "if the service is sending it over the wire but we don't render it..." that was my leading guess.

I'll try to get an update about what the service team is doing about this.

**Comment by BroganD1993** [comment] 2017-08-11 09:55
Any updates on this @awood45? I'd love to see this added to the SDK

**Comment by awood45** [comment] 2017-08-11 16:01
Actually, I do have an update and forgot to update this - this value should be present in the latest version of the SDK. Try upgrading and see if this works for you now.

Closing since it's added to the API, if you continue to have issues after upgrading feel free to reopen.

**Closed by awood45** 2017-08-11 16:01 UTC
Labels: pending, service api, Version 2
