### ISSUE TITLE
NoMethodError - undefined method `last_modified' for #<Hash:0x1e8b16d2>

### ISSUE THREAD

**Issue by PetrKaleta** [aws/aws-sdk-ruby#1607] opened 2017-09-11 09:52 UTC
`/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/aws-sdk-s3-1.2.0/lib/aws-sdk-s3/object_summary.rb:43:in `last_modified'`

Please have a look in `ObjectSummary` class...

```ruby
    # @return [Time]
    def last_modified
      data.last_modified
    end

    # @return [String]
    def etag
      data.etag
    end

    # @return [Integer]
    def size
      data.size
    end
```

but `data` is a hash...

**Comment by cjyclaire** [comment] 2017-09-11 16:27
Taking a look

**Comment by cjyclaire** [comment] 2017-09-11 16:42
@PetrKaleta Hmm, this sounds like a bug, could you help provide some code snippet to help me reproduce the issue?
I tried to reproduce in the simplest way:
```ruby
obj = Aws::S3::Resource.new.bucket('a-fancy-bucket').object('hello')
obj.last_modified
# => 2017-08-31 16:37:14 +000
```
And this works fine for me.

**Comment by PetrKaleta** [comment] 2017-09-11 16:52
This code was working without any issues until V3 was introduced

``` ruby
      def structure_at(bucket:, path: nil)
        bucket.client.list_objects_v2 prefix: path,
                                      bucket: bucket.name,
                                      delimiter: '/'
      end

      def files_at(bucket:, path: nil)
        structure = structure_at bucket: bucket, path: path

        structure
          .contents
          .map do |object|
            next if object.key.end_with? '/'

            Aws::S3::ObjectSummary.new bucket_name: bucket.name,
                                       key: object.key,
                                       data: object.to_h
          end
          .compact
      end
```

So it looks like the weak point is data attribute in `ObjectSummary` constructor...

**Comment by cjyclaire** [comment] 2017-09-11 18:15
@PetrKaleta Ah sorry about the confusion, I should try with object summary instead. I can reproduce this, looks like this will work if remove `.to_h` for the object in `:data` field. Double checking v2 behavior now before adding back compatiblity

**Comment by cjyclaire** [comment] 2017-09-11 18:57
@PetrKaleta A quick follow up question, may I ask for the documentation source that lead you to use `.to_h` in v2? Just trying to make sure I covered all in my fix PR.

Adding notes here: at V2, passing an object or hash both works.

**Comment by PetrKaleta** [comment] 2017-09-12 06:12
@cjyclaire Hmmmmm, I think I found it directly in the source code....

**Comment by cjyclaire** [comment] 2017-09-13 21:41
Soft update, the PR fix has been merged, will ping the thread once release is out

**Comment by cjyclaire** [comment] 2017-09-14 23:31
The release is [out](https://rubygems.org/gems/aws-sdk-s3/versions/1.4.0), closing

**Closed by cjyclaire** 2017-09-14 23:31 UTC
Labels: pending, Version 3
