### ISSUE TITLE
Aws::SNS::Errors isn't caught as document says

### ISSUE THREAD

**Issue by bluesh55** [aws/aws-sdk-ruby#1347] opened 2016-11-23 09:05 UTC
Hi! I'm using SNS service. I used catching exception code as [document says](http://docs.aws.amazon.com/sdkforruby/api/Aws/SNS/Errors.html).

```ruby
begin
  # do stuff
rescue Aws::SNS::Errors::EndpointDisabledException
  # ...
end
```
But It didn't work. And then it works after I changed `EndpointDisabledException` to `EndpointDisabled`. Is it documentation issue?

AWS sdk version : 2.6.11

**Comment by trevorrowe** [comment] 2016-11-23 19:47
This is an issue with documentation. The error raised by the SDK is `Aws::SNS::Errors:: EndpointDisabled`. This is a known issue/limitation that is in our backlog to correct the documentation.

**Comment by cjyclaire** [comment] 2017-06-19 18:31
Closing, this issue goes away in V3 documentation(which is currently under preview and is backward compatible with v2 doc). Adding some side notes: in V3, service errors are auto generated based on its shape from [`DynamicError`](https://github.com/aws/aws-sdk-ruby/blob/code-generation/gems/aws-sdk-sns/lib/aws-sdk-sns/errors.rb) module, and binds to its [operation](https://github.com/aws/aws-sdk-ruby/blob/code-generation/gems/aws-sdk-sns/lib/aws-sdk-sns/client_api.rb#L633).

**Closed by cjyclaire** 2017-06-19 18:31 UTC
Labels: Documentation, pending, Version 2

**Comment by amancevice** [comment] 2025-02-24 21:09
FYI this still happens with the v3 SDK

**Comment by mullermp** [comment] 2025-02-24 21:25
Thanks for the bug report. Do you have a reproduction case? I see the documentation suffixed with Exception. It's possible the service is not responding with the appropriate error code, so a dynamic error is created instead.

**Comment by amancevice** [comment] 2025-02-24 22:02
I think that's exactly what's happening @mullermp — I don't have a reproduction case but I suppose it's possible to create an endpoint and then mark it as disabled and test? All I know is I found what I assumed to be a bug in our code — a block rescuing the `EndpointDisabled` exception and corrected it to the `EndpointDisabledException` class and then HoneyBadger started going crazy over unhandled exceptions :)

**Comment by mullermp** [comment] 2025-02-26 00:56
The issue is worse than I thought. It appears to just be an issue with all XML responses that have a custom code, for which SNS appears to do for every exception (they just remove the Exception part). For example, [ResourceNotFoundException](https://github.com/aws/aws-sdk-ruby/blob/877b459c03ce053a2e311d3d6873ce1b210180a5/apis/sns/2010-03-31/api-2.json#L1699). A lot of the older services use XML/Query. It looks like we correctly crawl the model for error codes when it comes to [parsing data](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/aws-sdk-core/xml/error_handler.rb#L28), but not for extracting the error code itself. Fixing this may be a big breaking. I'm not certain I want to touch this. The best I could do is probably update the documentation.

**Comment by mullermp** [comment] 2025-03-06 04:16
A documentation fix for this was merged.
