### ISSUE TITLE
resource recordsets returning asterisks as octal

### ISSUE THREAD

**Issue by kidbrax** [aws/aws-sdk-ruby#1468] opened 2017-03-24 14:43 UTC
When you have an asterisk in your name, it is returned as \\052.

According to http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DomainNameFormat.html?shortFooter=true#domain-name-format-asterisk wildcards should only be treated as octal when not in the leftmost position.  However, that doesn't seem to be the case.  

So the question is can the sdk be updated to convert the ascii back to a wildcard?

Other reference:
https://forums.aws.amazon.com/thread.jspa?threadID=113183

**Comment by cjyclaire** [comment] 2017-03-24 20:44
@kidbrax Thanks for reaching out, may I ask for a bit more information to clear my confusions before digging deeper into the issue?

As in the public doc you referred, 
> If your domain name contains any of the following characters, you must specify the characters by using escape codes in the format \three-digit octal code:

Also, it's true that 
>You can create hosted zones that include * in the name. Note the following:
You can't include an * in the leftmost label in a domain name. For example, *.example.com is not allowed.
If you include * in other positions, DNS treats it as an * character (ASCII 42), not as a wildcard.

Maybe I'm missing something that you are suggesting? Looks like have it nor presenting as a wildcard is the correct behavior there? Even if looking at console, just as you have mentioned, it's shows as `\052`. May I ask which API are you using that make you feel this is troublesome? Then I might reach out to service team for potential feature request.

Also, recently, our `README.md`'s [`Getting Help`](https://github.com/aws/aws-sdk-ruby/blob/master/README.md#getting-help) section has been updated, feel free to get involved in other channels as well :) If you still find this could potentially be a SDK bug, I'm more than happy to help dig deeper into the behavior :)

**Comment by kidbrax** [comment] 2017-03-28 15:20
To clarify, I am talking about a record set which does allow a leftmost wildcard, not a hosted zone.

> You can also create resource record sets that include * in the name. DNS treats the * character either as a wildcard or as the * character (ASCII 42), depending on where it appears in the name. Note the following restrictions on using * as a wildcard in the name of resource record sets:

> The * must replace the leftmost label in a domain name, for example, *.example.com. It can't replace any of the middle labels, for example, marketing.*.example.com.
> The * must replace the entire label. For example, you can't specify *prod.example.com or prod*.example.com.
> You can't use the * as a wildcard for resource records sets that have a type of NS.
> For resource record sets, if you include * in any position other than the leftmost label in a domain name, DNS treats it as an * character (ASCII 42), not as a wildcard.

In my case, the asterisk is in the leftmost position.  However, when i retrieve it through the api, it is shown as the ASCII character.  It seems that Amazon's documentation is misleading and I have a support ticket out to them as well.  I guess what I'm asking for is maybe a flag/switch that will convert ascii characters.  That way, we're covered either way.

**Comment by cjyclaire** [comment] 2017-03-28 20:33
@kidbrax Thanks for your patience and clarification, now I can reproduce the case and see what you are suggesting : ) Your request sounds reasonable to me, I'll tag this as a feature request.

**Comment by cjyclaire** [comment] 2017-06-16 16:35
This is tracked in our feature backlog, closing.

**Closed by cjyclaire** 2017-06-16 16:35 UTC
Labels: feature request, service api, Version 2
