### ISSUE TITLE
gem install aws-sdk 3.1.0 / aws-sdk-applicationdiscoveryservice-1.49.0 missing ri file

### ISSUE THREAD

**Issue by cdenneen** [aws/aws-sdk-ruby#2833] opened 2023-03-14 15:23 UTC
### Describe the bug

On windows getting following error:

No such file or directory @ rb_sysopen - ./Aws/ApplicationDiscoveryService/Types/DisassociateConfigurationItemsFromApplicationRequest/cdesc-DisassociateConfigurationItemsFromApplicationRequest.ri

### Expected Behavior

gem install successfully

### Current Behavior

No such file or directory @ rb_sysopen - ./Aws/ApplicationDiscoveryService/Types/DisassociateConfigurationItemsFromApplicationRequest/cdesc-DisassociateConfigurationItemsFromApplicationRequest.ri

Installing ri documentation for aws-sdk-applicationdiscoveryservice-1.49.0

### Reproduction Steps

gem install aws-sdk-applicationdiscoveryservice -v 1.49.0

### Possible Solution

Disable installing documentation.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-applicationdiscoveryservice-1.49.0

### Environment details (Version of Ruby, OS environment)

ruby 2.5.9, CentOS 7

**Comment by mullermp** [comment] 2023-03-14 17:33
Are you able to install other gems like aws-sdk-s3? Have you tried installing rdoc-data first? Try `gem install rdoc-data` and `rdoc-data --install`

**Comment by cdenneen** [comment] 2023-03-14 18:48
Yes all other gems installed fine. It's just the RI for this one gem (aws-sdk-applicationdiscoveryservice-1.49.0) and only on Windows.
Works fine on linux, same gem versions.

**Comment by mullermp** [comment] 2023-03-14 19:26
Weird. I've personally never used Ruby on Windows. Is it an issue specifically with generated service documentation? I don't know how those RI files are generated.

**Comment by mullermp** [comment] 2023-03-14 19:37
Does it work for `aws-sdk-applicationdiscoveryservice-1.49.0` on older versions? (1.49.0 is the latest)

I'm noticing the docs for that shape have empty refs. Are you able to install `aws-sdk-pi`?

**Comment by cdenneen** [comment] 2023-03-14 20:22
I've never tried... i'm doing a packer build of an AMI and we have installed the aws-sdk for years... few years back it was broken into all these individual pieces in the past its worked (1.40.0). This was first time I tried since. 

As far as your question:

```
 .\gem install aws-sdk-pi
Successfully installed aws-sdk-pi-1.43.0
Parsing documentation for aws-sdk-pi-1.43.0
Installing ri documentation for aws-sdk-pi-1.43.0
Done installing documentation for aws-sdk-pi after 1 seconds
1 gem installed
```

**Comment by mullermp** [comment] 2023-03-15 17:00
Can you check the `./Aws/ApplicationDiscoveryService/Types/` directory and tell me what's there? Are all of the Types there EXCEPT the one that's missing? Or are they all missing and this is the first one encountered?

**Comment by cdenneen** [comment] 2023-03-15 18:30
Sorry I've destroyed that machine and switched our automated install of these gems to `--no-document` to bypass this issue.

**Comment by mullermp** [comment] 2023-03-16 14:09
Ok, I'll have to get myself a Windows machine and debug this. Thanks for reporting, I'm glad there's a work around, and sorry I don't know the issue.

**Comment by mullermp** [comment] 2023-04-01 03:21
I'm able to install this gem on Ruby 3.1 and 2.5.9 in Windows. I cannot reproduce. Since you are unblocked, I will close this.

**Closed as completed by mullermp** 2023-04-01 03:21 UTC
Labels: documentation
