### ISSUE TITLE
Multipart upload fails - 400 Bad request

### ISSUE THREAD

**Issue by kvmuralidhar** [aws/aws-sdk-ruby#2228] opened 2020-02-14 18:25 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
Hi there,

I was reviewing the aws-sdk documentation as well as the tcpdump for multipart upload and wanted to see if I can get help to troubleshoot this further. The documentation says "Whenever you upload a part, Amazon S3 returns an ETag header in its response. For each part upload, you must record the part number and the ETag value." I do not see ETag in the response.

We are not using s3 storage provided by aws but are using CEPH storage.

I am also attaching herewith an excel spreadsheet that shows the request/response. Any help would be very much appreciated.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
    aws-sdk (2.11.444)
      aws-sdk-resources (= 2.11.444)
    aws-sdk-core (2.11.444)
      aws-sigv4 (~> 1.0)
    aws-sdk-v1 (1.67.0)

**Version of Ruby, OS environment**
jruby/2.5.3 java resources, RHEL 7.7 

**To Reproduce (observed behavior)**
Logstash 7.3.2 & a compatible s3 storage like (ceph)

**Expected behavior**
Timeout error in logs and trace (tcpdump)

**Additional context**
[tcpdump-request.xlsx](https://github.com/aws/aws-sdk-ruby/files/4206084/tcpdump-request.xlsx)

**Comment by mullermp** [comment] 2020-02-14 19:16
Hey there, do you have any code snippets we can use to reproduce this? You mentioned that you are using CEPH storage. I'm not sure that we support using that from the official SDK? I see that your request has `Host: internal.cephstroage.com`, so your response from this service may not be forwarding all of the response values you are expecting. An ETag should be returned for each part when calling `upload_part` as per [documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#upload_part-instance_method).

**Comment by kvmuralidhar** [comment] 2020-02-15 23:31
Hi Matt,

Thank you for quick response :-).  We are using the official aws-sdk that's shipped along with logstash 7.3.2.   I will continue to investigate on my end.  

Here is the backtrace that we see in our logstash logs (backtrace is the same with 2.11.440)

`Uploading failed, retrying. {:exception=>Aws::S3::MultipartUploadError, :message=>"multipart upload failed: Net::ReadTimeout; Net::ReadTimeout; Net::ReadTimeout; Net::ReadTimeout", :path=>"/u/elasticStack/logstash-working-dir/ls-szng1/tmp/482ec854-eb7b-4bd2-ba8c-92ca83f08f5e/ls.s3.59a7b8a1-3906-4331-9e16-ee7afe4bc2bc.2020-02-05T20.42.part18.txt.gz", :backtrace=>["/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.330/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:81:in abort_upload'", "/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.330/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:70:in upload_parts'", "/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.330/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:44:in upload'", "/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.330/lib/aws-sdk-resources/services/s3/file_uploader.rb:32:in upload'", "/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.330/lib/aws-sdk-resources/services/s3/object.rb:252:in upload_file'", "/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.1.9/lib/logstash/outputs/s3/uploader.rb:38:in upload'", "/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.1.9/lib/logstash/outputs/s3/uploader.rb:29:in block in upload_async'", "/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/java_executor_service.rb:85:in run'"]}`

Thanks
Murali

**Comment by mullermp** [comment] 2020-02-17 19:46
Hi @kvmuralidhar, do you have any code snippets for how you are using the multipart uploader? What version of JRuby 9.x are you using?

`Net::ReadTimeout` can occur when the host is unreachable. Could you try reproducing with wire logging? You can enable wire logging via the REPL console with the `-v` arg or a client option `Service::Client.new(..., http_wire_trace: true)`

**Comment by kvmuralidhar** [comment] 2020-02-17 20:34
Hi Matt,

jruby is part of logstash install and here is the version.  

./vendor/jruby/bin/jruby --version
jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 OpenJDK 64-Bit Server VM 25.232-b09 on 1.8.0_232-b09 +jit [linux-x86_64]
The code that invokes aws-sdk ruby script is part of logstash-output-s3-4.2.0 filter (no customization done by us).  I enabled trace and small file (4mb) failed to upload as well.  The trace shows that

a-> successfully opened a connection to the destination 
b -> Request-> put request
c -> response -> 100-Continue
d -> read timeout

The one difference with ceph is the use of endpoint (http://host:80).

Thanks
Murali
[ceph.txt](https://github.com/aws/aws-sdk-ruby/files/4216087/ceph.txt)

**Comment by kvmuralidhar** [comment] 2020-02-17 20:51
Hi Matt,

We are having no issues uploading a file to ceph using aws-sdk version 2.11.177 (jruby version 9.1.13.0 (2.3.3) ).

Thanks
Murali

**Comment by mullermp** [comment] 2020-02-17 20:53
Hi @kvmuralidhar, could you try the latest 2.11.x version with that version of JRuby? I'm willing to bet it'd from a JRuby failure and not necessarily the SDK.

**Comment by mullermp** [comment] 2020-02-17 23:30
Using JRuby 9.2.7.0 and the latest SDK I'm not able to reproduce this on V3. I'm going to close this since you are not having any more issues, but I do recommend updating your SDK version.

**Comment by kvmuralidhar** [comment] 2020-02-18 00:56
> 
> 
> Hi @kvmuralidhar, could you try the latest 2.11.x version with that version of JRuby? I'm willing to bet the problem is from a JRuby bug/failure and not the SDK. I was going to try and reproduce this in JRuby 9.2.7.0.
> 
> I have never used log stash before, which module/file is being used in [their repo](https://github.com/logstash-plugins/logstash-output-s3)?

Hi Matt,

I tried your test.  Using the older version of aws-sdk with the newer version of logstash 7.3.2 (jruby) results in the same issue (Read connection timeout).  Did another test, ran the newer version of s3 output with the older version of logstash 6.5.4 results in no issues.  So, it seems like the newer version of jruby is causing the upload to fail.

`   aws-sdk (2.11.343)
      aws-sdk-resources (= 2.11.343)
    aws-sdk-core (2.11.343)
      aws-sigv4 (~> 1.0)
    aws-sdk-resources (2.11.343)
      aws-sdk-core (= 2.11.343)
    aws-sdk-v1 (1.67.0)
    aws-sigv4 (1.0.3)
`
Thank you.
Murali

**Comment by mullermp** [comment] 2020-02-18 01:33
It's possible that there's also a bug in the logstash library. It sounds like it's not a bug on our side?

**Comment by mullermp** [comment] 2020-02-18 18:24
I'm going to close this again unless there's a bug with the SDK.

**Closed by mullermp** 2020-02-18 18:24 UTC
Labels: 3rd-party, needs-sample
