### ISSUE TITLE
Getting storage class for all objects in a bucket

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [aws/aws-sdk-ruby#766] opened 2015-04-07 12:29 UTC
Version 2.0.36.

I was expecting this to be easy! I got my bucket and listed the objects, which according to http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Bucket.html#objects-instance_method should give me a collection of Aws::S3::ObjectSummary's, which conveniently have a storage_class method. However, it appears I instead get Aws::S3::Object's, which don't have a storage_class method and I can't work out how to get it!

```ruby
resource = Aws::S3::Resource.new
bucket = resource.bucket('bucket-name')
bucket.objects.limit(10).each do |obj|
  puts "Obj.class: #{obj.class}"
end
```

Output:
Obj.class: Aws::S3::Object
Obj.class: Aws::S3::Object
....

So a couple of questions:
1) Why doesn't Aws::S3::Bucket#objects return ObjectSummary's as advertised?
2) How do you get the storage_class for a Aws::S3::Object?

For now I guess I use http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#list_objects-instance_method.

**Comment by trevorrowe** [comment] 2015-04-09 22:58
I am unable to reproduce this issue. Earlier versions of the `aws-sdk` gem did return `Aws::S3::Objects`, but this was changed a while ago. Off the cuff I'd say about 2 months ago. Are you certain you are testing with the version you gave? Can you add a puts statement into your example like this:

```ruby
puts Aws::VERSION
resource = Aws::S3::Resource.new
bucket = resource.bucket('bucket-name')
bucket.objects.limit(10).each do |obj|
  puts "Obj.class: #{obj.class}"
end
```
When running the example above, I get the expected `Aws::S3::ObjectSummary` class name and version. Also, a stack trace could be helpful.

**Comment by trevorrowe** [comment] 2015-04-10 17:42
I'm going to close this as a non-issue. I suspect there is an issue in your environment with how the SDK is loaded. Please do re-open this issue if you can share a failure test case.

**Closed by trevorrowe** 2015-04-10 17:42 UTC
Labels: requesting feedback, Version 2
