### ISSUE TITLE
`to_json` causing `SystemStackError` for SES response in v3

### ISSUE THREAD

**Issue by rishabhsairawat** [aws/aws-sdk-ruby#2732] opened 2022-07-25 17:57 UTC
### Describe the bug

`send_raw_email` method on `Aws::SES::Client` object returns a `Aws::SES::Types::SendRawEmailResponse` which should be supporting `to_json` but on **v3** it is causing `SystemStackError: stack level too deep`. 
It was working fine in **v2**.

### Expected Behavior

It should return a valid JSON string.

### Current Behavior

Currently it is causing `SystemStackError: stack level too deep`,

### Reproduction Steps

call `send_raw_email` method on a valid `Aws::SES::Client` object and call `to_json` method for the response.

### Possible Solution

I tried calling the `to_s` method for both v2 & v3 versions.

On V2, `to_s` returns `"#<struct Aws::SES::Types::SendRawEmailResponse message_id=\"01010182363d52db-5bcb1ffd-f7aa-4863-b383-8f984cac1e6a-000000\">"`

On V3, `to_s` returns `"{:message_id=>\"0111118236469049-ec2d2a68-9eb1-411f-9f70-e50ae14de671-1110000\"}"`

This might help in fixing it.

### Additional Information/Context

I think this behavior has changed because of https://github.com/aws/aws-sdk-ruby/blame/e969f29e23f4930ff58728c5215a2e22fb2578cd/gems/aws-sdk-core/lib/aws-sdk-core/structure.rb#L51

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

'aws-sdk-ses'

### Environment details (Version of Ruby, OS environment)

Any version

**Comment by mullermp** [comment] 2022-07-25 19:49
Thanks for opening an issue. Do you perhaps have Rails loaded in the same environment? I recall some similar issue. A stack trace would help.

**Comment by rishabhsairawat** [comment] 2022-07-26 04:35
@mullermp Yes, I am using it in a rails app. Also, stack trace won't be possible as it is `SystemStackError: stack level too deep`.

Here is the sample code which I used:
`gem 'aws-sdk-ses', '~>1'`
```
region = 'us-west-2'
credentials = Aws::Credentials.new(ENV['ACCESS_KEY'], ENV['SECRET_KEY'])
client = Aws::SES::Client.new(credentials: credentials, region: region)
subject = 'Test Email'
from_email = 'noreply@example.com'
from_name = 'Example.com'
reply_to = 'reply@example.com'
mail = Mail.new
mail[:from] = from_name+' <' + from_email + '>'
mail[:reply_to] = reply_to
mail[:subject] = subject
template = 'test_env'
headers = {'template_name'=> template}
mail.headers(headers)
mail[:to] = "test <test@example.com>"
html_part = Mail::Part.new do
  content_type 'text/html; charset=UTF-8'
  body 'sample content'
end
mail.html_part = html_part
mail.text_part = nil
response = client.send_raw_email({raw_message: {data: mail.encoded}})
```

Here is the output for various methods:


<img width="1164" alt="ErrorResponse" src="https://user-images.githubusercontent.com/26122851/180939747-54ef03dd-6ac1-4070-838d-1df66f3f7dac.png">

**Comment by mullermp** [comment] 2022-07-26 14:09
Are you able to call `response.to_h.to_json` as a workaround? I don't recall details but I remember it being a funky interaction between the SDK and activesupport because [activesupport modifies Ruby stdlib classes](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/core_ext/object/json.rb), as you can see from the traceback.

Also, unrelated, the SDK should automatically pick up your credentials and region if you set `AWS_REGION`, `AWS_ACCESS_KEY_ID`, and `AWS_SECRET_ACCESS_KEY`, and construct a client `Aws::SES::Client.new` - you shouldn't need to construct a Credentials object.

**Comment by rishabhsairawat** [comment] 2022-07-26 14:18
@mullermp Yes, for the workaround, I have decided to use `response.to_h.to_json`. But any plans on a permanent fix of the issue as it is very common to call the `to_json` method?

Also, thank you for pointing out that credentials are automatically loaded from respective environment variables. I am also aware of that. I just used that for this issue's demonstration purposes only.

**Comment by mullermp** [comment] 2022-07-26 14:25
When I investigated this issue a while back (can't seem to find the related issue..) it was dependent on load ordering. When I load Rails first, then the SDK, I can reproduce your issue, but when I load the SDK, then Rails, it doesn't occur:

Using Pry from aws-v3.rb (loads SDK, then I load rails)
```
[1] pry(Aws)> require 'rails'
=> true
[2] pry(Aws)> lambda.list_functions.to_json
=> "{\"next_marker\":null,\"functions\":[{\"function_name\":\"CreateSong\ ...
```

Using IRB - Load rails then SDK
```
mamuller@147dda1143b7 aws-sdk-ruby % irb                       
irb(main):001:0> require 'rails'
=> true
irb(main):002:0> require 'aws-sdk-lambda'
=> true
irb(main):003:0> Aws::Lambda::Client.new.list_functions.to_json
Traceback (most recent call last):
       16: from /Users/mamuller/.gem/ruby/2.7.4/gems/activesupport-7.0.3.1/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
```

**Comment by mullermp** [comment] 2022-07-26 14:38
I think this will be fixed in the next major version (which is currently in development).

Based on the stack trace I see here:
```
0: /Users/mamuller/.gem/ruby/2.7.4/gems/activesupport-7.0.3.1/lib/active_support/core_ext/object/json.rb:159:in `dup'
1: /Users/mamuller/.gem/ruby/2.7.4/gems/activesupport-7.0.3.1/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
2: /Users/mamuller/.gem/ruby/2.7.4/gems/activesupport-7.0.3.1/lib/active_support/core_ext/object/json.rb:159:in `map'
3: /Users/mamuller/.gem/ruby/2.7.4/gems/activesupport-7.0.3.1/lib/active_support/core_ext/object/json.rb:159:in `as_json'
4: /Users/mamuller/.gem/ruby/2.7.4/gems/activesupport-7.0.3.1/lib/active_support/core_ext/object/json.rb:141:in `as_json'
``` 
It's bouncing between as_json for Array and Enumerable. I believe this is partly because of a design decision that can't be changed in V3, to use pageable response objects ([the response object is an Enumerable](https://github.com/aws/aws-sdk-ruby/blob/485d4a7278979287caad2aad19f582e106df966a/gems/aws-sdk-core/lib/aws-sdk-core/pageable_response.rb#L157)). In the new major version, response objects will be structs, and not be enumerable, but enumeration will occur in a separate class/abstraction.

So unfortunately, I don't think this is avoidable right now..

**Comment by mullermp** [comment] 2022-07-26 14:49
We may be able to implement a `to_json` on Structure, and it could call to_h to do so.

**Comment by mullermp** [comment] 2022-07-26 19:06
I found a way to fix the problem by implementing a simple to_json override in PageableResponse.

**Closed as completed** 2022-07-27 14:13 UTC
Labels: bug

**Comment by rishabhsairawat** [comment] 2022-07-28 13:58
@mullermp instead of implementing `to_json` we should have implemented `as_json` as ActiveSupport internally uses that.

If i make a custom hash with value as the response object, then it is causing SystemStackError.
```
rishabhsairawat@FVFF8434Q05N ~ % irb                
irb(main):001:0> require 'rails'
=> true
irb(main):002:0> require 'aws-sdk-lambda'
=> true
irb(main):003:0> Aws::Lambda::Client.new.list_functions.to_json
=> "{\"functions\":[]}"
irb(main):004:0> custom_response = {"lambda": Aws::Lambda::Client.new.list_functions}
=> {:lambda=>#<struct Aws::Lambda::Types::ListFunctionsResponse next_marker=nil, functions=[]>}
irb(main):005:0> custom_response.to_json
Traceback (most recent call last):
        11393: from /Users/rishabhsairawat/.rbenv/versions/2.7.3/bin/irb:23:in `<main>'
        11392: from /Users/rishabhsairawat/.rbenv/versions/2.7.3/bin/irb:23:in `load'
        11391: from /Users/rishabhsairawat/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'                     
         ... 11381 levels...     
            4: from /Users/rishabhsairawat/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
            3: from /Users/rishabhsairawat/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/core_ext/object/json.rb:141:in `as_json'
            2: from /Users/rishabhsairawat/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/core_ext/object/json.rb:159:in `as_json'
            1: from /Users/rishabhsairawat/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/core_ext/object/json.rb:159:in `map'
/Users/rishabhsairawat/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/core_ext/object/json.rb:159:in `block in as_json': stack level too deep (SystemStackError)
irb(main):006:0>  
```
After implementing the `as_json` method, it works as expected. Here is PR for the same

```
rishabhsairawat@FVFF8434Q05N ~ % irb                       
irb(main):001:0> require 'rails'
=> true
irb(main):002:0> require 'aws-sdk-lambda'
=> true
irb(main):003:0> Aws::Lambda::Client.new.list_functions.to_json
=> "{\"functions\":[]}"
irb(main):004:0> custom_response = {"lambda": Aws::Lambda::Client.new.list_functions}
=> {:lambda=>#<struct Aws::Lambda::Types::ListFunctionsResponse next_marker=nil, functions=[]>}
irb(main):005:0> custom_response.to_json
=> "{\"lambda\":{\"functions\":[]}}"
irb(main):006:0> 
```

I have created PR for the same. Please check

**Comment by mullermp** [comment] 2022-07-28 15:33
Ah..! I'm very sorry about that.
