### ISSUE TITLE
Issue with  Aws::SQS automatic MD5 computation, verification and stubbing.

### ISSUE THREAD

**Issue by albertogg** [aws/aws-sdk-ruby#1100] opened 2016-02-24 21:13 UTC
Hello, I'm having an issue but don't know if a bug or I need to do something more/else. Based on the **CHANGELOG.md** for version **2.2.19** there's this new feature:

  - Feature - Aws::SQS - Added automatic MD5 computation and verification of message bodies and attributes. This is now enabled by default for all #send_message and #send_message_batch requests.

But it seems this feature is not getting stubbed with:

```ruby
Aws.config[:stub_responses] = true
```

because I'm getting every single time:

```bash
Aws::Errors::ChecksumError:
       MD5 returned by SQS does not match the calculation on the original request. (MD5 calculated by the message body: '4e5dd0ef8e23423bf8226703669bf612', MD5 checksum returned: 'String')
```

I just want to know if I need to disable this new feature while stubbing or if this is an odd behavior. This is not happening on previous version (**2.2.18**).

I hope I made myself clear, thanks in advance!

**Comment by jv-dan** [comment] 2016-02-24 23:33
I hate dropping a "me too", but confirmed this affects my specs as well, and this is not an isolated incident.

**Comment by trevorrowe** [comment] 2016-02-25 01:50
@albertogg @jv-dan Thank you for reporting this issue. Looks like this was an unintended interaction between the default stubs plugin and the verify checksums plugin. The response stubbing is generating a fake response where the checksums are the string literals `"String"`.

Any easy fix would be to have the SQS MD5 plugin simply not attempt to verify checksums when response stubbing is enabled. Thoughts?

**Comment by albertogg** [comment] 2016-02-25 02:00
I think that might be the desired behavior. Thanks for the super quick response!

**Comment by trevorrowe** [comment] 2016-02-25 02:19
Okay, I've pushed a fix with some additional tests around this. I'll see if it is possible to get a patch release published tomorrow with the fix.

**Closed** 2016-02-25 02:18 UTC
Labels: bug, Version 2

**Comment by albertogg** [comment] 2016-02-25 15:27
Thanks for the quick fix! :clap:
