### ISSUE TITLE
aws-sdk-s3 started failing after v1.50.0 with Unresolved Specs Error

### ISSUE THREAD

**Issue by parepallykiran** [aws/aws-sdk-ruby#2141] opened 2019-10-21 19:03 UTC
Please fill out the sections below to help us address your issue

### Issue description

We have a chef cookbook which is using resource aws_s3_file started failing after aws-sdk-s3 version is upgraded to v1.50.0.

aws-sdk-s3 gem is failing with below error after v1.50.0 using aws-sdk 3.0.1

 WARN: Unresolved specs during Gem::Specification.reset:
     aws-sdk-batch (~> 1)
     aws-sdk-cloudwatch (~> 1)
      aws-sdk-kafka (~> 1)
      aws-sdk-kinesisvideoarchivedmedia (~> 1)
      aws-sdk-marketplacecommerceanalytics (~> 1)
     aws-sdk-personalize (~> 1)
      aws-sdk-rds (~> 1)
      aws-sdk-robomaker (~> 1)
     aws-sdk-s3 (~> 1)
      aws-sdk-workspaces (~> 1)
WARN: Clearing out unresolved specs.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3 v1.50.0

### Version of Ruby, OS environment
Ruby v2.1.0, Ubuntu 14.04.6

### Code snippets / steps to reproduce
Sample code from cookbook,

aws_s3_file "/var/cache/master.tar.gz" do
    bucket                aws_s3_service_bucket
    region                'aws_region'
    remote_path           "aws_s3_object.tar.gz"
    aws_access_key_id     aws_access_key_id
    aws_secret_access_key aws_secret_access_key
  end

**Comment by cjyclaire** [comment] 2019-10-21 20:02
From our s3 release log [here](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/CHANGELOG.md), the only change we take from 1.49.0 to 1.50.0 is this [feature](https://github.com/aws/aws-sdk-ruby/commit/24fa03ecfb5a645e5ee0cd88cd7aae55c88247b9).

Quick question, you are seeing this error when upgrading 1.50.0 from 1.49.0 or a more early version? Are you seeing this error at runtime or install/upgrade time? Are you able to reproduce the error with SDK only?(not in chef? I cannot reproduce this error locally)

**Comment by parepallykiran** [comment] 2019-10-21 20:06
From logs last successful last version was 1.49.0. But any server which is downloading v1.50.0 is failing with attached error. Seeing attached error during run time. Below error in chef recipe while trying to download s3 file,

cannot load such file -- aws-sdk-s3

**Comment by ajredniwja** [comment] 2019-10-29 22:54
Hey @parepallykiran I was not able to reproduce it locally using, it seems to be a chef issue. 
It would be really helpful if you could provide us with any additional context for the issue.

**Comment by parepallykiran** [comment] 2019-10-30 22:34
Hi @ajredniwja Issue is auto resolved after new version of aws-sdk-s3 v1.51.0. We have initially seen issue when aws-sdk-s3 gem is upgraded from v1.49.0 to v1.50.0. But currently I am not seeing any issues in chef run currently, it is using aws-sdk-s3 v1.51.0.

**Comment by ajredniwja** [comment] 2019-10-31 17:00
Hi @parepallykiran,

Thank-you for updating us. Will close this issue now, please reach out if you have any other questions.

**Closed by ajredniwja** 2019-10-31 17:00 UTC
Labels: guidance
