### ISSUE TITLE
Md5s plugin generates incorrect MD5 for empty `message_attributes`

### ISSUE THREAD

**Issue by jvilk-stripe** [aws/aws-sdk-ruby#2081] opened 2019-06-28 22:47 UTC
### Issue description

Try to send a message with `message_attributes` set to `{}` (empty object), and you'll receive the following `Aws::Errors::ChecksumError` exception:

```
MD5 returned by SQS does not match the calculation on the original request. (MD5 calculated by the message attributes: 'd41d8cd98f00b204e9800998ecf8427e', MD5 checksum returned: '')
```

In other words, the Md5s plugin calculates `d41d8cd98f00b204e9800998ecf8427e` for `message_attributes`, but SQS returns ''.

'd41d8cd98f00b204e9800998ecf8427e' is the MD5 of the empty string.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

It looks like the logic is still in master:

https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-sqs/lib/aws-sdk-sqs/plugins/md5s.rb#L70

### Version of Ruby, OS environment

N/A

### Code snippets / steps to reproduce

The following should do it:

```ruby
require 'aws-sdk-sqs'  # v2: require 'aws-sdk'

sqs = Aws::SQS::Client.new(region: 'us-west-2')

sqs.send_message(queue_url: URL, message_body: 'Hello world', message_attributes: {})
```

**Comment by cjyclaire** [comment] 2019-07-16 21:10
Apologies for the delay, I can reproduce this, taking a look

**Comment by cjyclaire** [comment] 2019-07-16 21:33
PR #2086 addressing the issue is under review

**Comment by cjyclaire** [comment] 2019-07-18 20:44
Latest release containing the fix was out, closing

**Closed by cjyclaire** 2019-07-18 20:44 UTC
Labels: pr-in-progress
