### ISSUE TITLE
Aws::EC2::Types::EbsBlockDevice.encrypted expects nil instead of a boolean value to disable encryption.

### ISSUE THREAD

**Issue by dElogics** [aws/aws-sdk-ruby#1471] opened 2017-03-26 09:21 UTC
In my block device specification (Aws::EC2::Types::EbsBlockDevice), I've set the encrypted attribute to false. But instances won't launch complaining -- 

`Parameter encrypted is invalid. You cannot specify the encrypted flag if specifying a snapshot id in a block device mapping. (Aws::EC2::Errors::InvalidParameter)`

From bug source: https://github.com/hashicorp/terraform/issues/1862
setting encrypted attribute to nil does suffice

Sample code -- 

```
rootdevMapping.ebs.delete_on_termination = true
puts "root device is encrypted: #{rootdevMapping.ebs.encrypted}"

# define interface (previously made)
pinterfaceSpec = Aws::EC2::Types::InstanceNetworkInterfaceSpecification.new
pinterfaceSpec.network_interface_id = pinterface.id
pinterfaceSpec.device_index = 0

aninstance = resource.create_instances( { :block_device_mappings => [rootdevMapping], :image_id => ami.id, :instance_type => "t2.micro", :min_count => 1 , :max_count => 1, :instance_initiated_shutdown_behavior => "terminate", :network_interfaces => [pinterfaceSpec] } ).first
```
outputs -- 
```
root device is encrypted: false
/usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.50/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Parameter encrypted is invalid. You cannot specify the encrypted flag if specifying a snapshot id in a block device mapping. (Aws::EC2::Errors::InvalidParameter)
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.50/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.50/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.50/lib/seahorse/client/plugins/response_target.rb:21:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.50/lib/seahorse/client/request.rb:70:in `send_request'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.50/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-resources-2.6.50/lib/aws-sdk-resources/request.rb:24:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-resources-2.6.50/lib/aws-sdk-resources/operations.rb:41:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-resources-2.6.50/lib/aws-sdk-resources/operations.rb:87:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-resources-2.6.50/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
        from ./aws.rb:87:in `<main>'
```
Not specifying rootdevMapping launches the instance -- 
```
rootdevMapping.ebs.delete_on_termination = true
puts "root device is encrypted: #{rootdevMapping.ebs.encrypted}"

# define interface (previously made)
pinterfaceSpec = Aws::EC2::Types::InstanceNetworkInterfaceSpecification.new
pinterfaceSpec.network_interface_id = pinterface.id
pinterfaceSpec.device_index = 0

aninstance = resource.create_instances( { :image_id => ami.id, :instance_type => "t2.micro", :min_count => 1 , :max_count => 1, :instance_initiated_shutdown_behavior => "terminate", :network_interfaces => [pinterfaceSpec] } ).first
```
Setting rootdevMapping.ebs.encrypted to nil also launches the instance.

**Comment by cjyclaire** [comment] 2017-03-27 22:30
Taking a look...

**Comment by cjyclaire** [comment] 2017-03-27 23:13
@dElogics Ah looks like the issue is using `snapshot_id` and `encrypted` at same time is not allowed actually. If I use `dry_run: true`, it will give helpful message (as you have observed): 
```
Aws::EC2::Errors::InvalidParameter Parameter encrypted is invalid. You cannot specify the encrypted flag if specifying a snapshot id in a block device mapping.
```
This is expected since `encrypted` cannot be used with `snapshot_id` together. Using `nil` works because it actually mocks the behavior of mot providing `encrypted` parameter.

**Comment by cjyclaire** [comment] 2017-03-28 17:38
Closing, since this relates to API behavior instead of SDK bug, feel free to reopen with further details if you feel it still feels like a SDK bug :) Thanks

**Closed by cjyclaire** 2017-03-28 17:38 UTC
Labels: service api, usage-question, Version 2
