### ISSUE TITLE
`Aws::S3::FileDownloader` chunk downloading is not thread-safe

### ISSUE THREAD

**Issue by tpett** [aws/aws-sdk-ruby#1566] opened 2017-08-14 14:12 UTC
When downloading multiple files at the same time in different threads the second file to finish downloading will always fail to concatenate its parts because the first file will have cleaned them up.

To reproduce:

```ruby
(1..2)
  .map { |_| Thread.new { object.download_file("file.mov") } }
  .each(&:join)
```

The reason for this is that `FileDownloader` is using `Dir.tmpdir` as the top level for the chunks without any form of namespacing. ([See this line][1]). For a thread-safe option check out the [`Dir.mktmpdir` method][2] in the standard library which creates a uniquely named directory to do your work in. If you use that as the toplevel directory, this would eliminate the problem. This would also simplify the cleanup code as you could just call `FileUtils.remove_entry tmp_dir` instead of unlinking each file.

For now, my workaround is to simply use the `"single_request"` mode.

[1]:https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-resources/lib/aws-sdk-resources/services/s3/file_downloader.rb#L117
[2]:http://ruby-doc.org/stdlib-2.0.0/libdoc/tmpdir/rdoc/Dir.html

**Comment by awood45** [comment] 2017-08-14 16:06
Thanks for the report on this. This is definitely not intended behavior, and at this point looking at this as a bug.

**Comment by cjyclaire** [comment] 2017-08-14 23:49
The fix PR has been merged, will be tagged in the next release ;) (likely tomorrow)
closing, will ping the thread once release is out, thanks!

**Closed by cjyclaire** 2017-08-14 23:49 UTC
Labels: bug, Version 2

**Comment by tpett** [comment] 2017-08-15 14:29
Wow, way to be super responsive guys!
