### ISSUE TITLE
iot-data api has incorrect prefix, hence does not work

### ISSUE THREAD

**Issue by SStorm** [aws/aws-sdk-ruby#1064] opened 2016-01-19 08:01 UTC
The file aws-sdk-core/apis/iot-data/2015-05-28/api-2.json lists the endpoint for the iot-data API as "data.iot", however this is not a correct endpoint. If you then proceed to attempt to access the given API via the ruby aws sdk with something like:

```ruby
iot = Aws::IoT::Client.new
endpoint = iot.describe_endpoint.endpoint_address

# Yes, my region for iot resources is eu-west-1
iotd = Aws::IoTDataPlane::Client.new(region: 'eu-west-1', endpoint: 'https://' + endpoint)
iotd.publish({
                 topic: '/test/topic',
                 qos: 1,
                 payload: "{'test':'1'}",
             })
```

something like this happens:
```
rake aborted!
Aws::IoTDataPlane::Errors::ForbiddenException: Credential should be scoped to a valid region, not 'us-east-1'. 
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/request.rb:70:in `send_request'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/Users/romanas/workspace/bootstrap/workspace/playground/Rakefile:32:in `block in <top (required)>'
```

If I manually edit the api descriptor file and change the endpoint to "iot", I get something like:

```
Aws::Json::ParseError: 795: unexpected token at 'OK'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/aws-sdk-core/json.rb:30:in `rescue in load'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/aws-sdk-core/json.rb:26:in `load'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/aws-sdk-core/json/parser.rb:17:in `parse'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/aws-sdk-core/rest/response/body.rb:37:in `parse'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/aws-sdk-core/rest/response/body.rb:23:in `apply'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/aws-sdk-core/rest/response/parser.rb:29:in `extract_body'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/aws-sdk-core/rest/response/parser.rb:13:in `apply'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/aws-sdk-core/rest/handler.rb:8:in `block in call'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/response.rb:43:in `call'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/response.rb:43:in `block in on'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/http/response.rb:139:in `block in on_success'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/http/response.rb:166:in `call'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/http/response.rb:166:in `block in listener'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/http/response.rb:130:in `call'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/http/response.rb:130:in `on_done'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/http/response.rb:137:in `on_success'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/response.rb:42:in `on'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/aws-sdk-core/rest/handler.rb:8:in `call'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/request.rb:70:in `send_request'
/Users/romanas/bundler/ruby/1.9.1/gems/aws-sdk-core-2.2.10/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/Users/romanas/workspace/bootstrap/workspace/playground/Rakefile:32:in `block in <top (required)>'
```

Which looks like another bug parsing the response, but is seemingly a successful operation (I get things delivered to the broker).

**Comment by awood45** [comment] 2016-01-19 17:22
There are a couple things going on here, I'll break it down one at a time.

First, IoT data plane uses an endpoint unique to you, which is the reason that we require you explicitly define an endpoint.

Consider the following:
```ruby
# Note that you do not need to explicitly define an endpoint.
iot = Aws::IoT::Client.new(region: "us-east-1")

# Throws an ArgumentError
Aws::IoTDataPlane::Client.new(region: "us-east-1")

# Valid
client = Aws::IoTDataPlane::Client.new(
  region: "us-east-1",
  endpoint: "https://#{iot.describe_endpoint.endpoint_address}"
)
```

**Comment by awood45** [comment] 2016-01-19 17:27
The second part is a bug between the server and client that I am currently looking at. To help illustrate, let's expand on that last example:
```ruby
iot = Aws::IoT::Client.new(region: "us-east-1")
client = Aws::IoTDataPlane::Client.new(
  region: "us-east-1",
  endpoint: "https://#{iot.describe_endpoint.endpoint_address}",
  http_wire_trace: true
)
client.publish(topic: "foo")
```
You'll see something like this:
```
-> "HTTP/1.1 200 OK\r\n"
-> "content-type: application/json\r\n"
-> "content-length: 2\r\n"
-> "date: Tue, 19 Jan 2016 17:26:10 GMT\r\n"
-> "x-amzn-RequestId: 0827dce3-d9ef-4463-b1f1-40a06d0ead44\r\n"
-> "connection: Keep-Alive\r\n"
-> "\r\n"
reading 2 bytes...
-> "OK"
read 2 bytes
```
We try to parse the response of `OK` as JSON, and that's where you get the error. The fix is going to be to make a customization for this service that explicitly checks for this and crafts the appropriate response.

**Comment by awood45** [comment] 2016-01-19 17:59
We've taken a different approach on this than a customization, but we've confirmed a fix for this. Will go out with the next release.

**Closed by awood45** 2016-01-19 17:59 UTC
Labels: bug, usage-question, Version 2
