### ISSUE TITLE
Aws::EC2::Route#data method raises when created by RouteTable#create_route.

### ISSUE THREAD

**Issue by glennpratt** [aws/aws-sdk-ruby#1269] opened 2016-08-10 05:23 UTC
```ruby
route = rtb.routes[1] # => Aws::EC2::Route route_table_id="rtb-58d83d3e", destination_cidr_block="10.201.0.0/16">
route.data # => <struct Aws::EC2::Types::Route
# destination_cidr_block="10.201.0.0/16",
# destination_prefix_list_id=nil,
# gateway_id=nil,
# instance_id=nil,
# instance_owner_id=nil,
# network_interface_id=nil,
# vpc_peering_connection_id="pcx-28f27e41",
# nat_gateway_id=nil,
# state="active",
# origin="CreateRoute">
```

```ruby
rt = rtb.create_route(destination_cidr_block: "10.201.0.0/16", vpc_peering_connection_id: "pcx-28f27e41") # => <Aws::EC2::Route route_table_id="rtb-58d83d3e", destination_cidr_block="10.201.0.0/16">
rt # => <Aws::EC2::Route route_table_id="rtb-58d83d3e", destination_cidr_block="10.201.0.0/16">
rt.data
# NotImplementedError: #load not defined for Aws::EC2::Route
# from /Users/glenn.pratt/Code/fields/vendor/bundle/ruby/2.1.0/gems/aws-sdk-resources-2.3.19/lib/aws-sdk-resources/resource.rb:150:in `load'
```

Edit: I removed one extraneous line from this example (`route.data.to_h`). It wasn't part of the issue.

**Comment by Doug-AWS** [comment] 2016-08-10 13:23
You've discovered that the type RouteTable (http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Types/RouteTable.html) is not the same as the class RouteTable (http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/RouteTable.html). You are accessing the type in your first example, the class in your second. If you want to just see the vales of all of your RouteTable objects in us-west-2, you can do something like the following:

```
require 'aws-sdk'

ec2 = Aws::EC2::Resource.new(region: 'us-west-2')

ec2.route_tables.each do |table|
  puts "ID:          #{table.id}"
  
  table.routes.each do |r|
    puts "  Gateway:     #{r.gateway_id}"
    puts "  State:       #{r.state}"
  end

  table.associations.each do |a|
    puts "  Subnet ID:    #{a.subnet_id}"
  end

  puts "VPC:         #{table.vpc_id}"
end
```

**Comment by glennpratt** [comment] 2016-08-10 13:36
@Doug-AWS thanks for the reply, but that does not appear to be the case in my example (see the types in the commented output) or in the return types in the documentation:

http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/RouteTable.html#routes-instance_method

http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/RouteTable.html#create_route-instance_method

**Comment by glennpratt** [comment] 2016-08-10 13:37
In my example, `route` and `rt` are both `Aws::EC2::Route`, yet `rt.data` raises `NotImplementedError: #load not defined for Aws::EC2::Route`.

**Comment by Doug-AWS** [comment] 2016-08-10 15:28
Does the route table show up in the console?

**Comment by glennpratt** [comment] 2016-08-10 16:18
@Doug-AWS yes, I don't think there is any issue with EC2 functionality, just that `Route#create_route` seems to return an incomplete object.

**Comment by awood45** [comment] 2016-08-24 20:24
Ok, I'm able to recreate this on my end. Taking a look, sorry for the initial confusion.

**Comment by awood45** [comment] 2016-08-24 20:34
Okay, here's the story - this is working as intended, with an unhelpful error message.

The first example you give, is sourced from a call to `Aws::EC2::Client#describe_route_tables`, which gives us the full suite of information for the route table, which we then populate the object with. You will notice, however, that `#load` isn't defined for that object either, if you try to call it directly, we can just hydrate the object with the response.

However, the second example calls `Aws::EC2::Client#create_route`, which does not give us a response body - we can only hydrate the object with the keys used to make it, and know it was created. There doesn't currently exist a way to describe a single route from a route table.

This means that you'll have to step back to describing the full route table again after creating the route, to get the full properties of the object. Happy to share feedback upstream that an individual route description API would be useful, but that's all we can do.

Closing this as we've answered, but feel free to follow up with any questions you still have.

**Closed by awood45** 2016-08-24 20:34 UTC
Labels: service api, Version 2

**Comment by glennpratt** [comment] 2016-08-24 23:07
@awood45 thanks for looking into this, I think I understood that when I posted the issue. I'm confused why returning a broken object is intended behavior.

If you can't construct a working object, why return an object of that class from `Aws::EC2::Client#create_route`? Returning a simpler struct (with appropriate doc changes) would be preferable to a broken object in my opinion.

**Comment by trevorrowe** [comment] 2016-08-25 02:19
While the data is not available from the returned route, you can call instance methods on that object, such as `#replace_route` and `#delete`.
