### ISSUE TITLE
DeploymentPolicy ignored in aws:elasticbeanstalk:command during Aws::ElasticBeanstalk::Client#update_environment

### ISSUE THREAD

**Issue by miensol** [aws/aws-sdk-ruby#1394] opened 2017-01-24 09:21 UTC
Hi All,

We are using https://github.com/ThoughtWorksStudios/eb_deployer which under the hood uses ElasticBeanstalk Ruby Aws Sdk. The [`Aws::ElasticBeanstalk::Client#update_environment`](http://docs.aws.amazon.com/sdkforruby/api/Aws/ElasticBeanstalk/Client.html#update_environment-instance_method) method is used in particular to trigger a deployment. I'm trying to make use of `RollingWithAdditionalBatch` deployment policy however this settings seems to be ignored when the environment update is initiated via mentioned sdk method. 

Inside of `option_settings` parameter of `update_environment` we have:
```
{"namespace"=>"aws:elasticbeanstalk:command","option_name"=>"DeploymentPolicy","value"=>"RollingWithAdditionalBatch"},
```

However despite the above the deployment is using Rolling strategy as far as I can tell:
```
2017-01-11 15:59:42 UTC+0100	INFO	Environment update completed successfully.
2017-01-11 15:59:42 UTC+0100	INFO	Successfully deployed new configuration to environment.
2017-01-11 15:59:42 UTC+0100	INFO	New application version was deployed to running EC2 instances.
2017-01-11 15:58:32 UTC+0100	INFO	Deploying new version to instance(s).
2017-01-11 15:57:57 UTC+0100	INFO	Updating environment ENV_ID configuration settings.
```

You can find the details of the method call in a [update-environment-call.txt](https://github.com/aws/aws-sdk-ruby/files/726149/update-environment-call.txt).

_What's interesting is that when the deployment is triggered through AWS console the Rolling With Additional Batch is executed properly:_
```
2017-01-12 08:44:12 UTC+0100	INFO	Rolling with Additional Batch deployment policy enabled. Launching a new batch of 1 additional instance(s).
```

Is this a bug in SDK, AWS API or I'm calling the method incorrectly?

**Comment by cjyclaire** [comment] 2017-01-24 22:12
@miensol Interesting, taking a look to see if I could reproduce the issue. Thanks for the information.

**Comment by cjyclaire** [comment] 2017-01-25 01:19
@miensol  Adding updates, I couldn't reproduce the issue with 
```ruby
{"namespace"=>"aws:elasticbeanstalk:command","option_name"=>"DeploymentPolicy","value"=>"RollingWithAdditionalBatch"}
```
with `update_environment` API, the policy has been updated successfully.

Looking at the config file provided, I don't see anything that is obviously wrong. So I'm curious what's happening. So may I ask more information? For example, is the update fails with `DeployPolicy` only? Are there other updates failures? Which version of SDK is used? Is there any error log that you encountered when performing the request?

**Comment by miensol** [comment] 2017-01-25 10:22
@cjyclaire  thanks for checking things out.

Here are the versions that are used:
```
    aws-sdk (2.6.44)
      aws-sdk-resources (= 2.6.44)
    aws-sdk-core (2.6.44)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-resources (2.6.44)
      aws-sdk-core (= 2.6.44)
    aws-sigv4 (1.0.0)
    eb_deployer (0.6.6)
      aws-sdk (~> 2, >= 2.0.0)
    jmespath (1.3.1)
```

I did more testing and it turns out that the issue might not necessarily be related to this library. 
The following invocation:
```
 client.update_environment(
         environment_id:"ENV_ID",
         version_label:"backend.1762",
         option_settings:[       
{
            "namespace"=>"aws:elasticbeanstalk:command",
            "option_name"=>"DeploymentPolicy",
            "value"=>"RollingWithAdditionalBatch"
},
       {"namespace"=>"aws:ec2:vpc","option_name"=>"VPCId","value"=>"VPC_ID_ABC"}
])  
```
Triggers **Rolling** deployment:
```
2017-01-25 11:07:33 UTC+0100	INFO	Environment update completed successfully.
2017-01-25 11:07:33 UTC+0100	INFO	Successfully deployed new configuration to environment.
2017-01-25 11:07:33 UTC+0100	INFO	New application version was deployed to running EC2 instances.
2017-01-25 11:06:39 UTC+0100	INFO	Deploying new version to instance(s).
2017-01-25 11:06:04 UTC+0100	INFO	Updating environment ENV_NAME configuration settings.
2017-01-25 11:05:47 UTC+0100	INFO	Environment update is starting.
```

However if we remove the VPC setting **Rolling with additional batch** is invoked as requested:


```
 client.update_environment(
         environment_id:"ENV_ID",
         version_label:"backend.1762",
         option_settings:[       
{
            "namespace"=>"aws:elasticbeanstalk:command",
            "option_name"=>"DeploymentPolicy",
            "value"=>"RollingWithAdditionalBatch"
}
])  
```

I find it strange since in both cases the VPC setting effective value did not change. Is that's how it's supposed to work?

**Comment by cjyclaire** [comment] 2017-01-26 01:04
@miensol Interesting, I'm wondering that might be the problem. 

Did you get any error message when updating VPC alone? May I ask is your environment sits in a VPC already? If not, you might need to do some [migration](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.managing.vpc.html) first before updating. If that's the case, you might see an `ConfigurationValidationException` error.

If not, perhaps the environment has the status "Updating" when you issued another request? It can only be updated when its status shows "Ready".

Hope those helps

**Comment by miensol** [comment] 2017-01-26 07:22
The environment is already in the target VPC and this `VPCId` is used in the `update_environment` call - so it's effective value before and after update is the same. I suspect the behavior is similar with other `option_settings` elements. 

There's also no error message logged - the update environment calls completes successfully in both cases. In our case majority of time all `otions_settings` are the same in subsequent `update_environments` calls as typically a deployment does not need to change any _environment_ settings.

The environment status is "Ready" otherwise we'd get a typical error message/event logged stating that it has to be "Ready" to perform an update.

**Comment by cjyclaire** [comment] 2017-01-27 00:46
@miensol Thanks for the information! So just to clarify on the issue before I dive deeper or contact service team about this behavior, are you suggesting that, for the `option_settings` parameter, it works when entries included are updated ones (instead of all options) ? Or you find that `VPCId` is the only one that causes the problem?

**Comment by miensol** [comment] 2017-01-27 08:37
@cjyclaire Not exactly. 

In my tests between subsequent calls to `update_environment` the only parameter that has different value is `version_label`. 

Step 1. We call `update_environment` with `version_label: 1` and certain `option_settings`. The `option_settings` include `RollingWithAdditionalBatch` **but also have other settings i.e. `VPCId`**. The environment is updated properly and the `RollingWithAdditionalBatch` shows as a settings in AWS Web Console. 

Step 2,3,4,5,... We call `update_environment` with `version_label: n` and **the same `option_settings`** as in Step 1. The new version of application is deployed using **Rolling** strategy which in my view is unexpected.

In my tests it turned out that if we perform Step 2,3,5 and in `option_settings` provide **only a single option** for `RollingWithAdditionalBatch` then the new version is deployed correctly using `RollingWithAdditionalBatch`.

**Comment by miensol** [comment] 2017-02-06 10:08
@cjyclaire Please let me know if there is anything I can do to help tackling the issue?

**Comment by cjyclaire** [comment] 2017-02-06 22:28
@miensol Thanks for the information! I'm having trouble in reproducing the `RollingWithAdditionalBatch` issue. I'll contact service team and let them know about this behavior for verification. And I'll keep you posted, meanwhile, our [#GettingHelp](https://github.com/aws/aws-sdk-ruby#getting-help) section has been updated, feel free to engaged in other channel as well : )

**Comment by cjyclaire** [comment] 2017-02-08 23:29
I got information from service team that a support ticket has been opened for this. Happy to know that other resource channel is engaged actively : ) If they need any thing from us, they will let us know. Closing, yet feel free to reopen with further questions or needs  : )

**Closed by cjyclaire** 2017-02-08 23:29 UTC
Labels: service api, usage-question

**Comment by miensol** [comment] 2017-03-03 07:25
Here are some important excerpts from our conversation with aws support so that people having the same problem as we do can find it (emphasis mine):

> As (...) mentioned, this behaviour occurred because the changes you made resulted in a **configuration update** being triggered. The deployment strategy used by a configuration change is different to that used by an application deployment. Certain modifications will trigger a configuration update, and some of these changes will require that your environment's instances be replaced (though some will not). Importantly, a configuration update can be triggered **even if the configuration option has not been changed since the last `update_environment` call**.
