### ISSUE TITLE
Online Documentation is not loading properly

### ISSUE THREAD

**Issue by bananastalktome** [aws/aws-sdk-ruby#3138] opened 2024-11-01 16:03 UTC
### Describe the issue

The online documentation (at https://docs.aws.amazon.com/sdk-for-ruby/v3/api/ as referenced from https://docs.aws.amazon.com/sdk-for-ruby/) appears to no longer be available:
![Screenshot 2024-11-01 at 11 59 28 AM](https://github.com/user-attachments/assets/2793a2eb-a14a-4c72-acac-8fa62e2c8075)

Additionally, deep links to parts of the documentation (such as https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/BedrockRuntime/Client.html) that used to work now appear rather broken:
![Screenshot 2024-11-01 at 12 00 55 PM](https://github.com/user-attachments/assets/9c85a8ec-422a-4664-aa3b-9075bfe2b539)

I first noticed this yesterday, but it may have been broken longer than that.

### Links

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/
https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/BedrockRuntime/Client.html

**Comment by mullermp** [comment] 2024-11-01 16:10
Wow! Thank you for reporting. We're not sure what happened. We are looking into this immediately.

**Comment by mullermp** [comment] 2024-11-01 19:33
We've deployed an older version to mitigate for now. We found the root cause and it's very sad: we hit the limitation of files with rubyzip (65,535) and enabled zip64 support which was not on by default. We will be pushing through updated docs shortly. I am going to close this. Thanks for bringing this to our attention.

**Closed as completed by mullermp** 2024-11-01 19:33 UTC
Labels: documentation, needs-triage

**Comment by bananastalktome** [comment] 2024-11-01 19:45
Thank you for the update, and for getting this fixed!
