### ISSUE TITLE
Regression: aws-sdk-rds v1.38.0 has broken dependencies

### ISSUE THREAD

**Issue by bjonord** [aws/aws-sdk-ruby#1918] opened 2018-11-16 11:41 UTC
### Issue description

Broken dependency in aws-sdk-rds v1.38.0 against endpoint_discovery.rb introduced in v3.37.0 of aws-sdk-core.

Gem has the following dependency:
```
 spec.add_dependency('aws-sdk-core', '~> 3', '>= 3.26.0')
```

This dependency does not contain the file required.

### Steps to reproduce

In Gemfile

```
gem 'aws-sdk-core', '~> 3.36.0'
gem 'aws-sdk-rds', '~> 1.38.0'
```

```
irb(main):001:0> require 'aws-sdk-rds'
Traceback (most recent call last):
       10: from /.rvm/rubies/ruby-2.5.1/bin/irb:11:in `<main>'
        9: from (irb):1
        8: from /.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        7: from /.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        6: from /.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        5: from /.rvm/gems/ruby-2.5.1@gemset/gems/aws-sdk-rds-1.38.0/lib/aws-sdk-rds.rb:13:in `<top (required)>'
        4: from /.rvm/gems/ruby-2.5.1@gemset/gems/aws-sdk-rds-1.38.0/lib/aws-sdk-rds.rb:13:in `require_relative'
        3: from /.rvm/gems/ruby-2.5.1@gemset/gems/aws-sdk-rds-1.38.0/lib/aws-sdk-rds/client.rb:18:in `<top (required)>'
        2: from /.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        1: from /.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
LoadError (cannot load such file -- aws-sdk-core/plugins/endpoint_discovery.rb)
```

### Ways to correct

Alter Gemfile

```
gem 'aws-sdk-core', '~> 3.37.0'
gem 'aws-sdk-rds', '~> 1.38.0'
```

**Comment by valscion** [comment] 2018-11-16 12:05
Seems to be a duplicate of #1917

**Comment by bjonord** [comment] 2018-11-16 12:08
👍

**Comment by srchase** [comment] 2018-11-16 16:07
@bjonord 

I've marked this as a duplicate and will close.  You can track resolution for this dependency issue in #1917.

**Closed by srchase** 2018-11-16 16:07 UTC
Labels: duplicate
