### ISSUE TITLE
Regression: Calling expiring_url with ActiveSupport::Duration throws error

### ISSUE THREAD

**Issue by bmulholland** [aws/aws-sdk-ruby#1732] opened 2018-03-20 17:04 UTC
Please fill out the sections below to help us address your issue

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3 1.8.2
aws-sigv4 1.0.2

### Version of Ruby, OS environment

Ruby 2.4.2
Rails 4.2.10

### Code snippets / steps to reproduce

In previous versions of the aws-s3 API you could get an expiring URL for an S3 asset like so: `object.expiring_url(30.minutes)`. 30.minutes is actually an `ActiveSupport::Duration`, but `30.minutes.to_s #=> "180"`.

This worked just fine until the aws-sigv4 gem was split out, when this crept in: https://github.com/aws/aws-sdk-ruby/blob/bf306e340c38928fd0f121448c240a2f8050e9be/gems/aws-sigv4/lib/aws-sigv4/signer.rb#L549

(was this change documented anywhere? Can't find it in a changelog). Previously the header was just set by `to_s`, so it worked fine: https://github.com/aws/aws-sdk-ruby/blob/f2c2e81087aa3c2c487f54e9e10961c58b4f67df/gems/aws-sdk-core/lib/aws-sdk-core/signers/v4.rb#L88

Specifically we are using this with the paperclip gem, which just released support for aws-sdk-s3 and so this bug was just exposed to us. So to repro:

1. Install aws-sdk v2
2. Install paperclip
3. Get an expiring link for an object with `object.expiring_url(30.seconds)`
4. Note that it works
5. Upgrade to aws-sdk-s3 and paperclip version that supports it
6. Run the code in step 3

Expected:
No change, link is generated

Actual:
"expected :expires_in to be a number of seconds" `lib/aws-sigv4/signer.rb:552:in 'extract_expires_in'`

**Comment by cjyclaire** [comment] 2018-06-25 22:58
Apology for the late reply, I agree that this is an un-intended regression that we introduced. 

When we are separating SigV4 gem, stronger restrictions are added as it became a gem that can be used without AWS service gems. We were hoping that helpful error checking can prevent an invalid url in the first place( as string can be anything with un-intended typos).

For workarounds, could you try `to_i` method for [`ActiveSupport::Duration`](http://api.rubyonrails.org/classes/ActiveSupport/Duration.html#method-i-to_i)?

Closing, feel free to re-open with further comments/issues : )

**Closed by cjyclaire** 2018-06-25 22:58 UTC
Labels: Version 3
