### ISSUE TITLE
Update the minor version when adding features to this gem

### ISSUE THREAD

**Issue by drywheat** [aws/aws-sdk-ruby#776] opened 2015-04-10 21:38 UTC
Why is the minor version of this library not updated whenever new features are added?  This is especially disruptive when those features break existing functionality and consumers only see the the bug version updated.  

It basically makes it so that pessimistic version governance, like "~> 2.0.22", is still unsafe.

**Comment by trevorrowe** [comment] 2015-04-10 22:01
I'm not opposed to using the minor vs the patch for some of our update. That said, the majority of the changes to this repository are:

* Service API additions.
* Bug fixes.

Most releases are not feature additions. Bug fixes belong as patch releases. The API updates can be argued as patches or features. The reasons I've been using patch versions for API updates is that they do not require code changes. We load a JSON document that describes the service API. The runtime does not need to change to support these updates.

Is there a specific update or feature addition that was no backwards compatible that is causing you an issue? Again, I'm not opposed to doing bumps to the minor version when new features have been added, but upgrading issues should be treated as bugs/regressions. Please feel free to open a GitHub issue if you run into something.

**Comment by trevorrowe** [comment] 2015-04-13 21:39
Please feel free to still respond. I'm closing this as a non-issue. I am still interested in feedback on what updates may have caused problems.

**Closed by trevorrowe** 2015-04-13 21:39 UTC
