### ISSUE TITLE
Undefined method `key?' - error when using default xml parser

### ISSUE THREAD

**Issue by quezacoatl** [aws/aws-sdk-ruby#715] opened 2015-02-23 19:20 UTC
I'm a bit confused about which XML parser will be used by ```multi_xml``` when no parsing lib has been required. If I don't require ```nokogiri``` I get the following error when getting messages from a queue created on a ```fake_sqs``` server:

```
/home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/xml/parser.rb:33:in `block in structure': undefined method `key?' for "\n    ":String (NoMethodError)
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/model/shapes.rb:252:in `yield'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/model/shapes.rb:252:in `block (2 levels) in members'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/model/shapes.rb:251:in `map'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/model/shapes.rb:251:in `block in members'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/xml/parser.rb:31:in `each'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/xml/parser.rb:31:in `each'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/xml/parser.rb:31:in `structure'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/xml/parser.rb:91:in `parse_shape'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/xml/parser.rb:34:in `block in structure'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/model/shapes.rb:252:in `yield'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/model/shapes.rb:252:in `block (2 levels) in members'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/model/shapes.rb:251:in `map'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/model/shapes.rb:251:in `block in members'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/xml/parser.rb:31:in `each'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/xml/parser.rb:31:in `each'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/xml/parser.rb:31:in `structure'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/xml/parser.rb:20:in `parse'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/query/handler.rb:36:in `parse_xml'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/query/handler.rb:13:in `block in call'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/response.rb:43:in `call'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/response.rb:43:in `block in on'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/http/response.rb:135:in `block in on_success'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/http/response.rb:162:in `call'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/http/response.rb:162:in `block in listener'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/http/response.rb:126:in `call'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/http/response.rb:126:in `on_done'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/http/response.rb:133:in `on_success'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/response.rb:42:in `on'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/response.rb:51:in `on_success'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/query/handler.rb:11:in `call'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/plugins/restful_bindings.rb:13:in `call'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/plugins/endpoint.rb:35:in `call'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/plugins/param_validation.rb:22:in `call'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/plugins/response_target.rb:18:in `call'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/seahorse/client/base.rb:216:in `block (2 levels) in define_operation_methods'
```

**Comment by trevorrowe** [comment] 2015-02-23 19:40
The SDK will default to using REXML from the Ruby standard lib. It is not the most performant library, but it is always available and requires no native extension support. I personally recommend the Ox gem. It is faster than nokogiri, but less portable, so your own needs will dictate the solution.

This error, however does not look like an issue with REXML. Instead, I suspect the fake sqs server is not sending back the expected response structure. Can you enable the HTTP wire trace to help debug?

```ruby
sqs = Aws::SQS::Client.new(http_wire_trace:true)
# ...
```

**Comment by quezacoatl** [comment] 2015-02-23 20:27
Ok, you're probably right about ```fake_sqs``` as it's not maintained but everything worked fine until and including version ```2.0.0.rc15```.

The output is:
```
reading 221 bytes...
-> "<ReceiveMessageResponse>\n    <ReceiveMessageResult>\n    </ReceiveMessageResult>\n    <ResponseMetadata>\n        <RequestId>19643011-2310-45d0-8611-e8eaaccc550e</RequestId>\n    </ResponseMetadata>\n</ReceiveMessageResponse>\n"
read 221 bytes
Conn keep-alive
E, [2015-02-23T20:58:48.777826 #31500] ERROR -- : Error in EventMachine event loop: undefined method `key?' for "\n    ":String
```

**Comment by quezacoatl** [comment] 2015-02-24 08:42
I tried to remove the indentation in the ```FakeSQS::Responder``` response, and that works perfectly. Ie., ```Builder::XmlMarkup.new(:indent => 4)``` to ```Builder::XmlMarkup.new```.

I don't know if there is any issue with REXML here. The response from AWS is most likely missing indentation.

**Comment by quezacoatl** [comment] 2015-02-24 09:41
With ```ox````my fix does not seem to work. The error is ```undefined method `key?' for "":String```

**Comment by trevorrowe** [comment] 2015-02-24 18:06
I'll try to take a look at this closer today. It is curious to me that the xml parsing logic is whitespace sensitive and that may warrant fixing in the SDK.

**Comment by trevorrowe** [comment] 2015-03-04 23:54
I was unable to reproduce the same issue locally. This gist, https://gist.github.com/trevorrowe/df78dd1f92cf02f19f76, gives the exact output you have in your example to the parser and it has no issues with the whitespace or xml formatting. More interesting, the actual error message indicates a different string being parsed:

    /home/quezacoatl/dev/work/sony/entrance/apps/worker/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.27/lib/aws-sdk-core/xml/parser.rb:33:in `block in structure': undefined method `key?' for "\n    ":String (NoMethodError)

This implies, that somehow the parser was receiving only a portion of the full xml body, and it was just whitespace.

Does this error persist on every request? If so, would you consider pairing over hangouts so that we can debug / reproduce this issue together?

**Comment by quezacoatl** [comment] 2015-03-05 07:41
I reproduced the issue with the gist you sent. I've created a new updated gist here: https://gist.github.com/quezacoatl/7f55bc833b103aa7f378

You must make sure that ```require "nokogiri"``` fails, which is done by ```require "bundler/setup"``` here. Maybe that is why you could not reproduce?

If you still cannot reproduce the issue I'm happy to assist over hangouts.

**Comment by trevorrowe** [comment] 2015-03-05 20:33
@quezacoatl Thank you for the updated gist. I was able to reproduce the error locally and it know makes sense to me what is going on.

In the sample XML there is the following:

```xml
<ReceiveMessageResult>\n    </ReceiveMessageResult>
```

When the `ReceiveMessageResult` xml element is present, it is expected to be a structure, i.e. a node with multiple child elements. Because none of these elements are present, the multi_xml gem is assuming that this is a string element and is returning the whitespace `"\n    "` value. The parser blows up because it is expecting a Hash, not a string.

The simplest fix for this is to send one of the following XML results:

```xml
<ReceiveMessageResult/>
<ReceiveMessageResult></ReceiveMessageResult>
```

Ideally, this would be reported to multi_xml as a bug. There should not be a difference in return value from `MultiXml.parse` based on the provider; I verified that Nokogiri works while REXML fails.

Given that the SDK works given expected input, I'm not inclined to make any changes in the SDK at this point. If I were to make a change, it would be to replace the multi_xml dependency. Parsing the entire document into a dom-like hash, just to translate the entire structure is less efficient than sax parsing directly into the desired structure.

My suggested work-around to you would be to patch fake_sqs at this point. Please, if you encounter any other issues like this, please let me know.

**Closed by trevorrowe** 2015-03-05 20:33 UTC
Labels: requesting feedback, Version 2

**Comment by trevorrowe** [comment] 2015-03-05 21:26
I've opened an issue with MultiXxml here: https://github.com/sferik/multi_xml/issues/46
