### ISSUE TITLE
Aws::S3::Object#upload_stream fails for empty files

### ISSUE THREAD

**Issue by janko-m** [aws/aws-sdk-ruby#1880] opened 2018-09-23 08:47 UTC
### Issue description

The new `Aws::S3::Object#upload_stream` doesn't work correctly for empty files. For a correct multipart upload of an empty file, an empty multipart part needs to be uploaded. `#upload_stream` doesn't do that, instead it tries to complete the multipart upload without any parts, which fails.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-sdk-s3 1.20.0`

### Version of Ruby, OS environment

```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
```

### Code snippets / steps to reproduce

```rb
require "aws-sdk-s3"

resource = Aws::S3::Resource.new(
  region: "...",
  access_key_id: "...",
  secret_access_key: "...",
)

bucket = resource.bucket("my-bucket")

object = bucket.object("foo")

object.upload_stream { |write_stream| write_stream.write("") }
```
```
        14: from script.rb:14:in `<main>'
        13: from /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-s3-1.20.0/lib/aws-sdk-s3/customizations/object.rb:269:in `upload_stream'
        12: from /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-s3-1.20.0/lib/aws-sdk-s3/multipart_stream_uploader.rb:44:in `upload'
        11: from /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-s3-1.20.0/lib/aws-sdk-s3/multipart_stream_uploader.rb:54:in `complete_upload'
        10: from /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-s3-1.20.0/lib/aws-sdk-s3/client.rb:393:in `complete_multipart_upload'
         9: from /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.27.1/lib/seahorse/client/request.rb:70:in `send_request'
         8: from /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.27.1/lib/seahorse/client/plugins/response_target.rb:23:in `call'
         7: from /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.27.1/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
         6: from /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.27.1/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
         5: from /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.27.1/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
         4: from /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.27.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
         3: from /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-s3-1.20.0/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'
         2: from /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-s3-1.20.0/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'
         1: from /Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-s3-1.20.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'
/Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.27.1/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The XML you provided was not well-formed or did not validate against our published schema (Aws::S3::Errors::MalformedXML)
```

**Comment by srchase** [comment] 2018-09-24 19:02
@janko-m 

Thanks for reporting this issue.  We're taking a look.

**Comment by cjyclaire** [comment] 2018-09-24 22:03
PR #1881 addressing the issue is under review

**Comment by cjyclaire** [comment] 2018-10-29 22:56
PR #1881 has been merged, fix will be out in the next release :)

**Closed by cjyclaire** 2018-10-29 22:56 UTC
Labels: Version 3, pr-in-progress
