### ISSUE TITLE
MultiXml::ParseError on high load workers getting files from S3 

### ISSUE THREAD

**Issue by magegu** [aws/aws-sdk-ruby#761] opened 2015-04-02 09:57 UTC
Hi there,

I'm using the Ruby SDK on a Elastic Beanstalk (Dockerized) Worker Environment to process(transforming) S3 files. So basically i'm getting s3 objects, create thumbnails, save some other things and put all back on another bucket. This is all happing on high load. Thousands of objects are getting pushed on s3 (from another client) and pulled by this ruby worker. 

Every once a while (1 time out ouf 10k requests) my ruby worker chrashed during a get_object from s3 ... i've no idea WHY it happend or what happend. but it does not seem like a bug in my code.

I attaching my stack trace I got from new relic

Thanks,
Martin

````
…gems/multi_xml-0.5.5/lib/multi_xml/parsers/
nokogiri.rb:  15:in `parse'
/usr/local/bundle/gems/multi_xml-0.5.5/lib/
multi_xml.rb: 138:in `parse'
…-sdk-core-2.0.28/lib/aws-sdk-core/xml/
error_handler.rb:  45:in `extract_error'
…-sdk-core-2.0.28/lib/aws-sdk-core/xml/
error_handler.rb:  21:in `error'
…-sdk-core-2.0.28/lib/aws-sdk-core/xml/
error_handler.rb:   9:in `block in call'
…ms/aws-sdk-core-2.0.28/lib/seahorse/client/
response.rb:  43:in `call'
…ms/aws-sdk-core-2.0.28/lib/seahorse/client/
response.rb:  43:in `block in on'
…s-sdk-core-2.0.28/lib/seahorse/client/http/
response.rb: 135:in `block in on_success'
…s-sdk-core-2.0.28/lib/seahorse/client/http/
response.rb: 162:in `call'
…s-sdk-core-2.0.28/lib/seahorse/client/http/
response.rb: 162:in `block in listener'
…s-sdk-core-2.0.28/lib/seahorse/client/http/
response.rb: 126:in `call'
…s-sdk-core-2.0.28/lib/seahorse/client/http/
response.rb: 126:in `on_done'
…s-sdk-core-2.0.28/lib/seahorse/client/http/
response.rb: 133:in `on_success'
…ms/aws-sdk-core-2.0.28/lib/seahorse/client/
response.rb:  42:in `on'
…-sdk-core-2.0.28/lib/aws-sdk-core/xml/
error_handler.rb:   8:in `call'
…e-2.0.28/lib/aws-sdk-core/plugins/
s3_request_signer.rb: 124:in `call'
…k-core-2.0.28/lib/aws-sdk-core/plugins/
s3_redirects.rb:  15:in `call'
…k-core-2.0.28/lib/aws-sdk-core/plugins/
retry_errors.rb:  88:in `call'
…ws-sdk-core-2.0.28/lib/aws-sdk-core/plugins/
s3_md5s.rb:  33:in `call'
….28/lib/aws-sdk-core/plugins/
s3_expect_100_continue.rb:  21:in `call'
…-core-2.0.28/lib/aws-sdk-core/plugins/
s3_bucket_dns.rb:  31:in `call'
…-sdk-core-2.0.28/lib/aws-sdk-core/
rest_body_handler.rb:   9:in `call'
…sdk-core-2.0.28/lib/aws-sdk-core/plugins/
user_agent.rb:  12:in `call'
…2.0.28/lib/seahorse/client/plugins/
restful_bindings.rb:  13:in `call'
…dk-core-2.0.28/lib/seahorse/client/plugins/
endpoint.rb:  35:in `call'
…2.0.28/lib/seahorse/client/plugins/
param_validation.rb:  22:in `call'
…8/lib/seahorse/client/plugins/
raise_response_errors.rb:  14:in `call'
…sdk-core-2.0.28/lib/aws-sdk-core/plugins/
s3_sse_cpk.rb:  18:in `call'
…2.0.28/lib/seahorse/client/plugins/
param_conversion.rb:  22:in `call'
…ore-2.0.28/lib/aws-sdk-core/plugins/
response_paging.rb:  10:in `call'
…-2.0.28/lib/seahorse/client/plugins/
response_target.rb:  18:in `call'
…ems/aws-sdk-core-2.0.28/lib/seahorse/client/
request.rb:  70:in `send_request'
…e/gems/aws-sdk-core-2.0.28/lib/seahorse/client/
base.rb: 216:in `block (2 levels) in define_operation_methods'
     /app/app/controllers/workers/
workers_controller.rb: 279:in `process_compressed_document'
```

**Comment by trevorrowe** [comment] 2015-04-02 20:53
Can you confirm this stack trace is from a get object request? The response from the GET request should not involve any XML parsing, unless the HTTP status code was a non ~200 response. If you can access the status code that would be helpful.

Also worth nothing, in the version that will be released shorty today, I replaced the XML parser/parsing logic. I've removed MultiXml, to avoid DOM parsing the data multiple times and replaced it with a single-pass SAX parser. This should be faster and may affect or resolve this issue.

Any additional information you have would be helpful in trying to track down the cause of this issue.

**Comment by trevorrowe** [comment] 2015-04-03 19:39
The new version is out now. When you update can you please report back if this or any related issues persist?

**Comment by magegu** [comment] 2015-04-03 20:11
Thanks for the feedback. I'll run the next tests next week and report if there is any improvement!

**Comment by trevorrowe** [comment] 2015-04-16 19:17
Can you confirm if this issue persists? If it does, it would be helpful to see the actual error class, message and a full stack trace.

**Comment by trevorrowe** [comment] 2015-04-21 13:55
I haven't heard anything back. No news is good news, right? :) Please feel free to re-open this issue if you encounter these errors again after the update.

**Closed by trevorrowe** 2015-04-21 13:55 UTC
Labels: requesting feedback, Version 2

**Comment by magegu** [comment] 2015-04-21 15:25
hi @trevorrowe thanks for your help.
I haven't had this issue since the last update (as far as i saw error reportings at new relic) ... so yes, consider it closed :)
