### ISSUE TITLE
Encoding::ConverterNotFoundError: code converter not found (xml_attr_content,xml_attr_quote)

### ISSUE THREAD

**Issue by hakunin** [aws/aws-sdk-ruby#1303] opened 2016-09-26 14:17 UTC
Hey guys,
I got this weird error that doesn't have any records on the internet. 
Any ideas why this might be happening?

I got it just once so I guess this could mean that AWS had a hickup?

```
Encoding::ConverterNotFoundError: code converter not found (xml_attr_content,xml_attr_quote)
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/xml/doc_builder.rb" line 64 in encode
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/xml/doc_builder.rb" line 64 in escape
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/xml/doc_builder.rb" line 72 in block in attributes
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/xml/doc_builder.rb" line 71 in each
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/xml/doc_builder.rb" line 71 in map
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/xml/doc_builder.rb" line 71 in attributes
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/xml/doc_builder.rb" line 56 in open_el
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/xml/doc_builder.rb" line 33 in node
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/xml/builder.rb" line 116 in node
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/xml/builder.rb" line 29 in structure
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/xml/builder.rb" line 18 in to_xml
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/rest/request/body.rb" line 43 in serialize
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/rest/request/body.rb" line 28 in build_body
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/rest/request/body.rb" line 18 in apply
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/rest/request/builder.rb" line 35 in populate_body
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/rest/request/builder.rb" line 10 in apply
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/rest/handler.rb" line 6 in call
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/user_agent.rb" line 12 in call
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/plugins/endpoint.rb" line 41 in call
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/param_validator.rb" line 21 in call
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/plugins/raise_response_errors.rb" line 14 in call
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/s3_sse_cpk.rb" line 18 in call
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/param_converter.rb" line 20 in call
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/plugins/response_target.rb" line 21 in call
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/request.rb" line 70 in send_request
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/base.rb" line 207 in block (2 levels) in define_operation_methods
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-resources-2.2.19/lib/aws-sdk-resources/request.rb" line 24 in call
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-resources-2.2.19/lib/aws-sdk-resources/operations.rb" line 41 in call
File "/app/vendor/bundle/ruby/2.1.0/gems/aws-sdk-resources-2.2.19/lib/aws-sdk-resources/operation_methods.rb" line 19 in block in add_operation
File "/app/vendor/bundle/ruby/2.1.0/gems/shrine-1.2.0/lib/shrine/storage/s3.rb" line 162 in multi_delete
File "/app/vendor/bundle/ruby/2.1.0/gems/shrine-1.2.0/lib/shrine/plugins/multi_delete.rb" line 25 in _delete
File "/app/vendor/bundle/ruby/2.1.0/gems/shrine-1.2.0/lib/shrine/plugins/versions.rb" line 159 in _delete
File "/app/vendor/bundle/ruby/2.1.0/gems/shrine-1.2.0/lib/shrine/plugins/versions.rb" line 156 in _delete
File "/app/vendor/bundle/ruby/2.1.0/gems/shrine-1.2.0/lib/shrine.rb" line 254 in delete
```

**Comment by awood45** [comment] 2016-09-27 21:25
It's hard to pin down without a wire trace - did this happen only a single time, or does this periodically recur?

**Comment by hakunin** [comment] 2016-09-28 06:03
We don't have much traffic yet and this is the first time I see it. It happened when removing a file from S3 in a background job and it looks like it ended up being successful on an automatic re-run so I don't have data to recreate it.

**Comment by janko-m** [comment] 2016-10-04 09:35
@awood45 It happens when using the S3 endpoint for deleting multiple objects at once (through the corresponding aws-sdk method).

**Comment by awood45** [comment] 2016-10-17 22:33
Is this in a threaded setup, or deleting objects sequentially?

**Comment by hakunin** [comment] 2016-11-09 13:45
This is from a sidekiq background job.

**Comment by trevorrowe** [comment] 2016-11-17 09:29
There are a bunch of red herrings flying around here. This is not a concurrency issue at all. The stack trace is coming from code in the SDK when we are trying to build an XML document to send as a request. The error is not returned from the remote service.

> It happens when using the S3 endpoint for deleting multiple objects at once (through the corresponding aws-sdk method).

There is a known issue with Amazon S3 and object keys as represented in XML. Object keys can contain characters that are invalid inside an XML document. Some of these, often non-printable characters, will even cause S3 to fail on responses. As a work-around, S3 allows you to send a boolean on all list object calls, requesting the keys be URL encoded before serializing them in the XML response. The SDK does this automatically, and then URL decodes them before returning them to the user. This happens transparently and avoids many errors.

The issue is that S3's Delete Objects api call accepts keys back in XML. If you have some of these object keys with invalid characters, the xml encode method raises. This is the error you are seing. These keys simply can not be represented in XML. As such, they can not be sent via DELETE objects. They must be sent as an individual DELETE object call where the key is sent in the URI where it is URL encoded.

If Amazon S3 adds the options to provide the keys to DELETE objects in a URL encoded form, then the SDK could smooth over this issue automatically. Until such a parameters/option exists, the only work-around is to DELETE the object(s) with the special characters individually.

**Comment by trevorrowe** [comment] 2016-11-17 09:29
I'm going to close this issue, as there is nothing the SDK can do at this time. Please feel free to re-open if you have additional questions.

**Closed by trevorrowe** 2016-11-17 09:29 UTC
Labels: information requested, Version 2

**Comment by hakunin** [comment] 2016-11-17 10:15
Thanks for sharing @trevorrowe, I think the files could have been uploaded via direct upload (we support both), so I am wondering if that could cause let the issue happen, as it doesn't go through the SDK?
