### ISSUE TITLE
Dependencies issue using latest version of aws-sdk-core

### ISSUE THREAD

**Issue by scalp42** [aws/aws-sdk-ruby#2044] opened 2019-05-13 21:01 UTC
I believe a recent change is the cause of this issue:

```
Unable to activate aws-sdk-autoscaling-1.20.0, because aws-sdk-core-3.44.2 conflicts with aws-sdk-core (~> 3, >= 3.48.2), aws-sigv4-1.0.3 conflicts with aws-sigv4 (~> 1.1)
```

List of the gems:

```
Fetching aws-sdk-core 3.44.2
Installing aws-sdk-core 3.44.2
Fetching aws-sdk-cloudformation 1.13.0
Installing aws-sdk-cloudformation 1.13.0
Fetching aws-sdk-cloudwatch 1.13.0
Installing aws-sdk-cloudwatch 1.13.0
Fetching aws-sdk-dynamodb 1.18.1
Installing aws-sdk-dynamodb 1.18.1
Fetching aws-sdk-ec2 1.63.0
Installing aws-sdk-ec2 1.63.0
Fetching aws-sdk-elasticloadbalancing 1.8.0
Installing aws-sdk-elasticloadbalancing 1.8.0
Fetching aws-sdk-iam 1.13.0
Installing aws-sdk-iam 1.13.0
Fetching aws-sdk-kinesis 1.9.0
Installing aws-sdk-kinesis 1.9.0
Fetching aws-sdk-kms 1.13.0
Installing aws-sdk-kms 1.13.0
Fetching aws-sdk-route53 1.16.0
Installing aws-sdk-route53 1.16.0
Fetching aws-sdk-s3 1.30.1
Installing aws-sdk-s3 1.30.1
Fetching aws-sdk-ssm 1.34.0
Installing aws-sdk-ssm 1.34.0
```

Investigating.

**Comment by cjyclaire** [comment] 2019-05-14 19:15
@scalp42  I cannot reproduce the issue locally, quick question, are you doing a single gem update or using bundle or in other environment? Newer versions of service gems requires more recent core versions as well, those should be auto picked up.

**Comment by scalp42** [comment] 2019-05-14 23:59
So something really weird is that I can't reproduce it.

I'm really confused, no gems were updated or anything.

Could it be a require ordering issue?

Going to close this in meantime as I can't reproduce it either 🤷‍♂

**Comment by cjyclaire** [comment] 2019-05-15 16:27
No worries at all, closing, feel free to reopen with further info : )

**Closed by cjyclaire** 2019-05-15 16:27 UTC
Labels: guidance

**Comment by scalp42** [comment] 2019-05-15 21:57
@cjyclaire we just hit the issue again:


```
8:          require 'httparty'
9:          require 'aws-sdk-ec2'
10>>         require 'aws-sdk-autoscaling'
```

```
Gem::ConflictError
  ------------------
  Unable to activate aws-sdk-autoscaling-1.22.0, because aws-sdk-core-3.44.2 conflicts with aws-sdk-core (~> 3, >= 3.52.1), aws-sigv4-1.0.3 conflicts with aws-sigv4 (~> 1.1)
```

Current gems installed:

```
root@consul-i-04ecf592eb4f03a38:~# /opt/chef/embedded/bin/gem list | grep -i aws
aws-eventstream (1.0.3)
aws-partitions (1.123.0)
aws-sdk-autoscaling (1.22.0)
aws-sdk-cloudformation (1.13.0)
aws-sdk-cloudwatch (1.13.0)
aws-sdk-core (3.52.1, 3.44.2)
aws-sdk-dynamodb (1.18.1)
aws-sdk-ec2 (1.63.0)
aws-sdk-elasticloadbalancing (1.8.0)
aws-sdk-iam (1.13.0)
aws-sdk-kinesis (1.9.0)
aws-sdk-kms (1.13.0)
aws-sdk-route53 (1.16.0)
aws-sdk-s3 (1.30.1)
aws-sdk-ssm (1.34.0)
aws-sigv4 (1.1.0, 1.0.3)
```

**Comment by scalp42** [comment] 2019-05-15 22:13
No idea what's the issue:

```
root@consul-i-01c9b7b875dab4a02:~# /opt/chef/embedded/bin/pry
[1] pry(main)> require 'httparty'
=> true
[2] pry(main)> require 'aws-sdk-ec2'
=> true
[3] pry(main)> require 'aws-sdk-autoscaling'
=> true
```

**Comment by scalp42** [comment] 2019-05-15 22:29
I think I tracked it down to https://github.com/chef-cookbooks/aws/blob/master/metadata.rb#L24

I'll open an issue over there.

Thanks!
