### ISSUE TITLE
Struct::Tms is deprecated warning

### ISSUE THREAD

**Issue by nickdnk** [aws/aws-sdk-ruby#2323] opened 2020-06-03 18:58 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
I'm not entirely sure that this is considered a bug, but Elastic Beanstalk worker environments complain (a lot) with this message in `journalctl -xe`

```
/opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.6.0/gems/aws-sdk-core-2.11.482/lib/aws-sdk-core/eager_loader.rb:22: warning: constant Struct::Tms is deprecated
```

It seems to affect at least version 2.11.482. Maybe this report belongs somewhere else. If so please close it and forward it to whoever should be handling this.

**Comment by alextwoods** [comment] 2020-06-04 18:52
Do you have a larger stack trace?  

What [platform version](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.ruby) are you using? And do you have a Gemfile?

**Comment by nickdnk** [comment] 2020-06-04 20:07
Hello Alex

The platform was PHP 7.4 3.0.1. I am on 3.0.2 now and I *think* it may have been fixed. I've been struggling with getting the PHP worker type on an AL2 environment to work for two days, so a lot of debugging has come and gone and I no longer have an environment that gives this error.

I don't run Ruby at all. This is a PHP stack. I think the SQS daemon in Elastic Beanstalk uses this library to run its SQS commands. In other words; the EB guys are the ones you want to talk to and the ones who can probably figure this out. I just didn't really know where to go with this error to get the right people's attention.

**Comment by alextwoods** [comment] 2020-06-05 16:34
Hey - good to hear you're not actively experiencing the issue anymore.  I'll cut a ticket with the Elastic beanstalk team to investigate.  Any chance you have more of a stack trace from the error in your logs?

**Comment by nickdnk** [comment] 2020-06-05 16:35
Cool. Unfortunately no. That was all the output I got in the logs. I don't even know if this was the cause of any of my problems, but I figured I'd just report it.

**Comment by alextwoods** [comment] 2020-06-05 17:53
Thanks for reporting this.  I wasn't able to reproduce it using the 3.0.2 version and the console no longer lets me create an application with the older 3.0.1 - so this may be an issue that was fixed in the newer version so I'm going to close this out.  Feel free to re-open if you run into this again and I can engage the service team.

**Closed by alextwoods** 2020-06-05 17:53 UTC
Labels: dependencies, investigating

**Comment by BanzaiMan** [comment] 2020-08-26 20:04
Hello, there. We can reliably reproduce this problem with a recent Ruby > 2.6:

```sh-session
$ ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
$ gem install dpl-s3
Fetching jmespath-1.4.0.gem
Fetching aws-eventstream-1.1.0.gem
Fetching aws-sigv4-1.2.2.gem
Fetching aws-sdk-core-2.11.572.gem
Fetching aws-sdk-resources-2.11.572.gem
Fetching aws-sdk-2.11.572.gem
Fetching dpl-1.10.15.gem
Fetching mime-types-data-3.2020.0512.gem
Fetching dpl-s3-1.10.15.gem
Fetching mime-types-3.3.1.gem
Successfully installed dpl-1.10.15
Successfully installed jmespath-1.4.0
Successfully installed aws-eventstream-1.1.0
Successfully installed aws-sigv4-1.2.2
AWS SDK For Ruby V2 has been marked as deprecated. Please upgrade to AWS SDK For Ruby V3.
Successfully installed aws-sdk-core-2.11.572
AWS SDK For Ruby V2 has been marked as deprecated. Please upgrade to AWS SDK For Ruby V3.
Successfully installed aws-sdk-resources-2.11.572
AWS SDK For Ruby V2 has been marked as deprecated. Please upgrade to AWS SDK For Ruby V3.
Successfully installed aws-sdk-2.11.572
Successfully installed mime-types-data-3.2020.0512
Successfully installed mime-types-3.3.1
Successfully installed dpl-s3-1.10.15
10 gems installed
$ dpl --provider=s3
Installing deploy dependencies
/home/travis/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-2.11.572/lib/aws-sdk-core/eager_loader.rb:22: warning: constant Struct::Tms is deprecated
/home/travis/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-2.11.572/lib/aws-sdk-core/eager_loader.rb:22: warning: constant Struct::Tms is deprecated
/home/travis/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-2.11.572/lib/aws-sdk-core/eager_loader.rb:22: warning: constant Struct::Tms is deprecated
/home/travis/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-2.11.572/lib/aws-sdk-core/eager_loader.rb:22: warning: constant Struct::Tms is deprecated
Version 2 of the Ruby SDK will enter maintenance mode as of November 20, 2020. To continue receiving service updates and new features, please upgrade to Version 3. More information can be found here: https://aws.amazon.com/blogs/developer/deprecation-schedule-for-aws-sdk-for-ruby-v2/
/home/travis/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-2.11.572/lib/aws-sdk-core/eager_loader.rb:22: warning: constant Struct::Tms is deprecated
/home/travis/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-2.11.572/lib/aws-sdk-core/eager_loader.rb:22: warning: constant Struct::Tms is deprecated
/home/travis/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-2.11.572/lib/aws-sdk-core/eager_loader.rb:22: warning: constant Struct::Tms is deprecated
/home/travis/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-2.11.572/lib/aws-sdk-core/eager_loader.rb:22: warning: constant Struct::Tms is deprecated
/home/travis/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-2.11.572/lib/aws-sdk-core/eager_loader.rb:22: warning: constant Struct::Tms is deprecated
/home/travis/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-2.11.572/lib/aws-sdk-core/eager_loader.rb:22: warning: constant Struct::Tms is deprecated
/home/travis/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-2.11.572/lib/aws-sdk-core/eager_loader.rb:22: warning: constant Struct::Tms is deprecated
/home/travis/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-2.11.572/lib/aws-sdk-core/eager_loader.rb:22: warning: constant Struct::Tms is deprecated
⋮
```

https://github.com/travis-ci/dpl/pull/1208 is a patch to our gem that fixes the issue, but ideally, it would be incorporated here, so that it can be used by everyone.

As far as I can tell, v3 does not exhibit this problem.

**Comment by schlick** [comment] 2020-09-28 08:26
Got the same issue as @BanzaiMan using aws-sdk-core 2.11.520 when we upgraded from Ruby 2.5.8 to 2.6.6.

**Comment by alextwoods** [comment] 2020-09-29 16:23
I've created a PR to merge the patch from dpl#1208 since this is a fairly straightforward fix.   Version-2 of the SDK is on a path to maintaince mode and will stop receiving [regular updates on 11/20/2020](https://aws.amazon.com/blogs/developer/deprecation-schedule-for-aws-sdk-for-ruby-v2/).
