### ISSUE TITLE
SNS list_subscriptions not returning all items

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#1197] opened 2016-05-30 19:24 UTC
We have a subscription to a lambda function in SNS. The AWS console displays the correct number of subscriptions, which is 12, including the lambda sub. The aws-cli also returns the correct number of subs. When I use the aws-sdk-ruby, only 11 subscriptions are being returned and the lambda one is not among them. Is there something we are missing?

```Ruby
2.3.0 :027 > sns = Aws::SNS::Client.new(access_key_id: ENV['AWS_ACCESS_KEY_ID'], secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'], region: 'us-east-1', http_wire_trace: false)
 => #<Aws::SNS::Client> 
2.3.0 :028 > sns.list_subscriptions.subscriptions.length
 => 11 
2.3.0 :029 > 
``` 

From the AWS Console:

![screen_shot_2016-05-30_at_3_22_45_pm](https://cloud.githubusercontent.com/assets/6500/15656945/974bb1ec-267a-11e6-9175-ca71f59bb96e.png)

**Comment by awood45** [comment] 2016-05-30 21:25
I have a (loose) suspicion. What happens if you try this variant?

```ruby
sns = Aws::SNS::Client.new(access_key_id: ENV['AWS_ACCESS_KEY_ID'], secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'], region: 'us-east-1', http_wire_trace: false)
resp = sns.list_subscriptions
resp.last_page? # Testing if pagination happened.
resp.subscriptions.length # For reference.
```

I'd also be interested in seeing the HTTP wire trace of your call and response. That will help determine why you're seeing a discrepancy (because the other possibility is that you're getting a legitimately different response between console and the service, which would be an issue I would raise with the service).

**Comment by pchaganti** [comment] 2016-05-30 21:46
Removed the actual list of subs brought back as I do not want to post those details in a public post. Here is the rest. TRhe length still comes back as 11.

thanks!


```Ruby
2.3.0 :006 > sns = Aws::SNS::Client.new(access_key_id: ENV['AWS_ACCESS_KEY_ID'], secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'], region: 'us-east-1', http_wire_trace: true)
 => #<Aws::SNS::Client> 
2.3.0 :007 > resp = sns.list_subscriptions
opening connection to sns.us-east-1.amazonaws.com:443...
opened
starting SSL for sns.us-east-1.amazonaws.com:443...
SSL established
<- "POST / HTTP/1.1\r\nContent-Type: application/x-www-form-urlencoded; charset=utf-8\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.3.7 ruby/2.3.0 x86_64-darwin15\r\nX-Amz-Date: 20160530T214145Z\r\nHost: sns.us-east-1.amazonaws.com\r\nX-Amz-Content-Sha256: 0693efeb802ed7b95fd14be8698fa947dcdd642a4f1c46bb0830aea20d\r\nAuthorization: AWS4-HMAC-SHA256 Credential=CRED/20160530/us-east-1/sns/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=428ae3db3092d5106ae7656eee1a86c9f7532a624ad81fa119980a3cd6e7e\r\nContent-Length: 43\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "x-amzn-RequestId: 69d4d65d-c6ff-5732-91b2-999b73268807\r\n"
-> "Content-Type: text/xml\r\n"
-> "Content-Length: 5415\r\n"
-> "Date: Mon, 30 May 2016 21:41:45 GMT\r\n"
-> "\r\n"
reading 5415 bytes...
-> ""

read 5415 bytes
Conn keep-alive
 => 
2.3.0 :008 > resp.last_page?
 => false 
2.3.0 :009 > resp.subscriptions.length
 => 11 
```

**Comment by pchaganti** [comment] 2016-05-30 21:47
This might be a pagination thing?

**Comment by awood45** [comment] 2016-05-30 22:30
Yes. Try this:

```ruby
sns.list_subscriptions.each_page do |page|
  page.subscriptions.each do |subscription|
    # do what you want, but for example:
    puts subscription.subscription_arn
  end
end
```

**Comment by awood45** [comment] 2016-05-30 22:32
That's why I asked for `last_page?` - your value of "false" shows that the response was truncated. If that had returned true, I was hoping something in the wire trace response would have hinted to the cause (or to a broken pagination configuration). But, this looks to be a correctly behaving paginated response.

**Comment by awood45** [comment] 2016-05-30 22:33
Closing this since it appears we've identified the cause. Feel free to tack on any follow-up questions, or reopen/open a new issue if we missed something.

**Closed by awood45** 2016-05-30 22:33 UTC
Labels: service api, usage-question, Version 2
