### ISSUE TITLE
KMS encrypt does not return Base64 encoded ciphertext_blob

### ISSUE THREAD

**Issue by evanwieren** [aws/aws-sdk-ruby#1173] opened 2016-04-29 21:49 UTC
When I encrypt a value using KMS, it comes back with the following struct based on doing 

resp.data

#<struct Aws::KMS::Types::EncryptResponse ciphertext_blob="\n \x00+\xD0'\xE3:\xDEW\x1348GdA^0\eL(@\xCB\t\x8B\xD5@rE \xABhx\x11\x12\x96\x01\x01\x01\x02\x00x\x00+\xD0'\xE3:\xDEW\x1348GdA^0\eL(@\xCB\t\x8B\xD5@rE \xABhx\x11\x00\x00\x00m0k\x06\t*\x86H\x86\xF7\r\x01\a\x06\xA0^0\\\x02\x01\x000W\x06\t*\x86H\x86\xF7\r\x01\a\x010\x1E\x06\t`\x86H\x01e\x03\x04\x01.0\x11\x04\f\n\xB5\xE7\x97,!{\x86\xE1\xF5\xA9\xAD\x02\x01\x10\x80*\xBC\xEB &n\xB1\xD8q~\x1C#F3\x80\xE4\xFCJ\xCB\xF5vK\xAAUgH\x82q\xC1;e\xE30K\xFE\xE4}\xC9\x9A\x01\x96A>", key_id="arn:aws:kms:us-east-1:scrubbed:key/scrubbed">

According to the documentation it is 

    #ciphertext_blob ⇒ String

    The encrypted plaintext.
    #key_id ⇒ String

    The ID of the key used during encryption.

Is there a way to change this back to plain text?

**Comment by awood45** [comment] 2016-04-29 22:55
Can you provide a bit more context? Client-side or server-side encryption? Is the "resp" you're referring to from an S3 get_object?

**Comment by evanwieren** [comment] 2016-04-29 23:03
This would be a client side encryption.

  def encrypt_content(kms_key_id, content)
    kms_client = Aws::KMS::Client.new
    begin
      resp = kms_client.encrypt({
        key_id: kms_key_id,
        plaintext: content
      })
    rescue => e
      # TODO: get the actual exception
      Rails.logger.debug "Error! AWS problem encrypting contents"
      Rails.logger.debug "#{e.message} #{e.backtrace.join("\n")}"
    end
    resp ? resp.ciphertext_blob : nil
  end

**Comment by awood45** [comment] 2016-04-30 00:03
Okay, I can see that the response is not Base64 encoded. This is currently by design. You can Base64 encode the response with:

```ruby
resp = kms_client.encrypt(key_id: kms_key_id, plaintext: content)
Base64.encode64(resp.ciphertext_blob)
```

**Comment by evanwieren** [comment] 2016-04-30 00:24
Yes, that worked. I had attempted to decode64, I did not try encode64. 

Thanks 
👍

**Comment by awood45** [comment] 2016-04-30 00:38
Glad that worked for you! Closing, feel free to follow up if you have other questions or issues.

**Closed by awood45** 2016-04-30 00:38 UTC
Labels: pending, Version 2
