### ISSUE TITLE
url_for incorrectly encodes entities in path portion of URI

### ISSUE THREAD

**Issue by jbergler** [aws/aws-sdk-ruby#718] opened 2015-02-26 00:51 UTC
In S3 I have an object with a key containing a colon, lets say `file-123:456`.
In a rails app I generate a pre-signed url for this object, which returns the `:`, %-encoded as `%3A`.

```
https://my-bucket.s3.amazonaws.com/file-123%3A456?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=....
```

I then ask nginx to reverse proxy to this url via the `X-Accel-Redirect` header, but this request fails with a `SignatureDoesNotMatch` error.

It appears that internally nginx is adhering to the [RFC for a URI](https://tools.ietf.org/html/rfc3986#section-3.3) in that a colon is specifically listed as a character that isn't %-encoded in the path portion, as such when parsing the url, it decodes `%3A` to `:` and forwards the request like this:

```
https://my-bucket.s3.amazonaws.com/file-123:456?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=....
```
It's easy to understand that this difference results in the invalid signature - what is less clear to me is what should be happening here. I believe that the RFC indicates that a colon in the path portion should not be %-encoded (specifically this line `pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
`). If that assumption holds true, it would suggest the issue should be fixed in the aws gem - maybe?

Note, I also tested the same thing with v2 of the gem and found the same behavior.

```ruby
>> signer.presigned_url(:get_object, bucket: "my-bucketl", key: "file-123:456")
=> "https://my-bucket.s3.amazonaws.com/file-123%3A456?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=...."
```

**Comment by trevorrowe** [comment] 2015-02-26 02:17
thanks for reporting the issue. I agree this sounds like it should be fixed in the SDK. I'll try to take a look at this shortly.

**Comment by trevorrowe** [comment] 2015-03-03 01:53
I took a look into this and was unable to reproduce the issue:

```ruby
signer = Aws::S3::Presigner.new

url = signer.presigned_url(:get_object, bucket:'aws-sdk', key:'foo:bar')
#=> "https://aws-sdk.s3.amazonaws.com/foo%3Abar?X-Amz-..."

r = Net::HTTP.get_response(URI(url))
#=> #<Net::HTTPOK 200 OK readbody=true>

url = url.gsub('%3A', ':')
#=> "https://aws-sdk.s3.amazonaws.com/foo:bar?X-Amz-..."

r = Net::HTTP.get_response(URI(url))
#=> #<Net::HTTPOK 200 OK readbody=true>
```

I purposefully modified the generated url to use ":" instead of the percent-encoded "%3A".  Both versions of the URL are accepted by Amazon S3. I suspect that the nginx to reverse proxy is adding headers that Amazon S3 expects to be signed, that aren't, or is modifying header values that were already signed.

Are you able to run the example above?

**Comment by trevorrowe** [comment] 2015-03-05 21:32
As it stands, it does not look like a bug in the SDK. I would investigate the proxy to see if it is changing or adding headers to the request. Also, if you can provide a sample gist that shows the pre-signed URL can not be used, I'd be happy to dig into this more. Please feel free to re-open if you have more information.

**Closed by trevorrowe** 2015-03-05 21:32 UTC
Labels: requesting feedback, Version 2

**Comment by imlocn** [comment] 2016-08-10 23:09
can the uri take this:  http://username:pass-wordKo@abc!a@proxy.abc.xyz.net:80
