### ISSUE TITLE
Aws::EC2::Client#describe_images is painfully slow

### ISSUE THREAD

**Issue by JaimeHolland** [aws/aws-sdk-ruby#2079] opened 2019-06-27 07:47 UTC
### Issue description

The requirement is to list the Image Ids of AMIs, using a tag filter.  There are currently 2,788 AMIs which match the criteria.  

Using the aws-sdk this takes time (e.g. after turning on logging you can see it takes about 40 minutes:

D, [2019-06-26T16:49:37.547565 #26157] DEBUG -- : [Aws::EC2::Client 200 2253.411334 0 retries] describe_images(filters:[{name:"tag:MyTag",values:["something"]}])

If I do this with the AWS cli, it returns in < 20 seconds.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

*** LOCAL GEMS ***

aws-sdk (2.11.164, 2.9.44)
aws-sdk-core (2.11.164, 2.9.44)
aws-sdk-resources (2.11.164, 2.9.44)

### Version of Ruby, OS environment

Amazon Linux
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

### Code snippets / steps to reproduce

      ec2 = Aws::EC2::Resource.new(client: ec2_client)
      all_images = ec2.images(filters: [{ name: "tag:MyTag", values: ["something"] }])

This results in the long-running describe_images as mentioned above.  I'm not even sure that this should be doing a describe_images at this point, since I've not asked for any image details?  But anyway, it's slow.

Whereas, this cli code produces the same number of amis, but runs in seconds

      aws ec2 describe-images --filters "Name=tag:MyTag,Values=something"

**Comment by cjyclaire** [comment] 2019-06-27 22:26
For solving the root cause, EC2 team is working on pagination support for their APIs that are not yet have pagination support, once they have pagination enabled, you should be able to iterate through pageable responses like a lazy load enumerator(instead of waiting a giant response).

The latency diffs mentioned with CLI is interesting though, do you see the pattern persists every time? 
Just tried calling `ec2.describe_images()` (for every AMIs)
Ruby: 
```
[Aws::EC2::Client 200 435.607839 0 retries] describe_images()
```
will need to to some benchmarking comparison

**Comment by JaimeHolland** [comment] 2019-06-28 06:30
The latency diff is consistent, that is the concern for me. I would imagine that either far more information is being requested by the SDK (that I don't need) or that somehow we're retrieving information individually for every ami, instead of doing it in one batch like the cli?  How many amis were being returned in your above example?

**Comment by cjyclaire** [comment] 2019-06-28 17:40
One quick note, I did use CLI debug mode to see wire logs and confirmed that we are doing the same by making single request, you can see SDK wire log by `:http_wire_trace` to true at client as well.

simply calling `describe_images` with no filters returns  AMIs 102914 in total.

**Comment by cjyclaire** [comment] 2019-09-10 23:01
Soft update, really appreciate the service API behavior feedback, mind following our [getting hep](https://github.com/aws/aws-sdk-ruby#getting-help) section for contacting AWS support or on stackoverflow with service tag? In that way service team can be notified directly and help : )

Closing, feel free to reopen with further concerns or comments!

**Closed by cjyclaire** 2019-09-10 23:01 UTC
Labels: service-api
