### ISSUE TITLE
RSS memory of this gem is large (total of ~20-23 mb)

### ISSUE THREAD

**Issue by schneems** [aws/aws-sdk-ruby#2409] opened 2020-09-22 22:38 UTC
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

Using `bundle exec derailed exec perf:mem` against the open source app https://www.codetriage.com I'm seeing this gem is taking up a lot of memory:

- aws-sdk-s3 version: 1.81.0
  - memory: 28.6367 MiB
  - Full output: https://gist.github.com/schneems/18d956b8daf4ffb91c05b97f3f0b4338

Gem Name: aws-sdk-s3

**Version of Ruby, OS environment**
-paste the output of ruby -v

ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin17]

**To Reproduce (observed behavior)**

Add this gem to a rails app, configure it to run with derailed benchmarks then execute  `bundle exec derailed exec perf:mem`

You can see a smaller version here using `get_process_mem` but it looks like it might not be the full require:

```ruby
require 'bundler/inline'
version = '1.81.0'
gemfile do
  source 'https://rubygems.org'
  gem 'aws-sdk-s3', version, require: false
  gem 'get_process_mem'
end

require 'get_process_mem'

before = GetProcessMem.new.mb
require 'aws-sdk-s3'
after = GetProcessMem.new.mb

puts "Memory difference: #{after - before}"
# => "Memory difference: 22.08984375"
```

**Expected behavior**

I expect this behavior to use less memory. Most gems are around 2-3mb. 12mb for a gem of this size is already large.

**Comment by mullermp** [comment] 2020-09-23 16:26
While I agree it's a large gem, I don't see anything that would cause concern. I checked the prior commits between those versions and I don't see anything unusual. There are a lot of APIs and even more documentation for those APIs. Generated code is almost doubled with resource models included. I don't think it's fair to compare s3 with "most gems" because most gems are not code generated from a large service API.

**Comment by alextwoods** [comment] 2020-09-23 16:46
I've been unable to reproduce this locally (outside of rails):

```
aws-sdk-s3 version 1.79.1: 22.81640625 MB require   (gem size: 266K, installed on disk: 1928k)
aws-sdk-s3 version 1.81.0: 23.15234375 MB require (gem size: 276K, installed on disk: 2056K)
required %increase: 1.5%
gem size %increase: 6.6%
```

While these numbers have increased (as a result of adding new codegen'ed code for new api features), they don't match the increase you're seeing when benchmarking with `derailed`.  I'm not sure how derailed is measuring memory usage but I wonder if something else is going on.   Did any of your other dependencies change between those two tests?

**Comment by schneems** [comment] 2020-09-23 17:11
I can confirm that the gems both take up about the same amount of memory, so the problem isn't isolated between those two version releases

```ruby
require 'bundler/inline'

pid = fork do
  version = '1.79.1'
  gemfile do
    source 'https://rubygems.org'
    gem 'aws-sdk-s3', version, require: false
    gem 'get_process_mem'
  end

  require 'get_process_mem'

  before = GetProcessMem.new.mb
  require 'aws-sdk-s3'
  after = GetProcessMem.new.mb

  puts "Memory difference (#{version}): #{after - before}"
end
Process.waitpid(pid)


pid = fork do
  version = '1.81.0'
  gemfile do
    source 'https://rubygems.org'
    gem 'aws-sdk-s3', version, require: false
    gem 'get_process_mem'
  end

  require 'get_process_mem'

  before = GetProcessMem.new.mb
  require 'aws-sdk-s3'
  after = GetProcessMem.new.mb

  puts "Memory difference (#{version}): #{after - before}"
end
Process.waitpid(pid)
```

Generates:

```
Memory difference (1.79.1): 24.35546875
Memory difference (1.81.0): 25.55859375
```

I've updated the issue and description to reflect this.


Regarding the derailed numbers, notice that the total memory of my two runs didn't really change, so it might be something to do with load order. We can ignore those results if the problem reproduces here outside of rails and is present in older versions. It's all based off of RSS and since GC uses a 1.2x multiplier for how much memory it will malloc at a time it is sensitive to load order.

> with "most gems" because most gems are not code generated from a large service API.

Then lets look at another generated gem. Heroku's `platform-api` is generated using `heroics` 

```
irb(main):003:0> before = GetProcessMem.new.mb
irb(main):004:0> require 'platform-api'
=> true
irb(main):005:0> after = GetProcessMem.new.mb
irb(main):006:0>
irb(main):007:0> puts "Memory difference: #{after - before}"
Memory difference: 12.40234375
```

This is about half the size of the current gem, but I do think you're onto something that the issue likely has less to do with the specific code that's being used than how it's being generated on disk.

Human-generated code tends to favor many smaller files while programmatic generated code tends to favor one large file. I think there might be a related issue in ruby/ruby that i'm struggling to point out and describe adequately enough to turn it into a bug report at ruby-lang.

To help that conversation i've created a repo: https://github.com/schneems/require_array_source_memory_problem

While I ultimately feel it's the owner of the gem's responsibility for the resource utilization of their library, it looks like there could be a much larger "fix" out there than breaking down code into smaller files. Can you take a look at that repo and give me feedback? I would like to ultimately report this to ruby/ruby

## Next steps

* Explore and report this behavior back up to ruby/ruby
* Explore a workaround for generated code. One idea: Since it seems the problem is related to the size of source code, could we possibly split up some generated code into more files, and if we do that...would it decrease RSS requirements?

**Comment by alextwoods** [comment] 2020-09-24 22:28
Thanks for looking into that - I create a small PR in your repository to compare the difference in memory usage by requiring a bunch of smaller files which may indeed improve memory usage.  If that is indeed true it would be possible (though not super straightforward) to modify the SDK's codegen to split some of the generated types into smaller files.

**Comment by mullermp** [comment] 2020-09-24 22:41
Closing to move discussion to other repo.

**Closed by mullermp** 2020-09-24 22:41 UTC
Labels: guidance, wontfix

**Comment by schneems** [comment] 2020-09-25 15:11
@alextwoods thanks! @mullermp is it a private repo or can you tag me?

**Comment by katpadi** [comment] 2024-08-30 03:56
I'm experiencing the same "high" memory from this gem and I'm curious if there's any update?

**Comment by rubyonrailsworks** [comment] 2024-10-22 01:58
I'm experiencing the same "high" memory issue
