### ISSUE TITLE
Aws::S3::Object#presigned_url(:get, reponse_expires: ... ) raise NotImplementedError

### ISSUE THREAD

**Issue by hiboma** [aws/aws-sdk-ruby#1730] opened 2018-03-16 01:00 UTC
### Issue description

When I test the following code, `Aws::S3::Object#presigned_url(:get)` with `:response_expires`, it raises `NotImplementedError` instead of generating a pre-sign URL.

```ruby
#!/usr/bin/env ruby

require 'aws-sdk-s3'

s3 = Aws::S3::Resource.new(
  access_key_id: '***',
  secret_access_key: '***',
)

obj = s3.bucket('examplebucket').object('test.txt')
puts obj.presigned_url(:get, response_expires: Time.now)
```

While other `:response_*` parameters

 * `:response_content_type`
 * `:response_content_language`
 * `:response_cache_control`
 * `:response_content_disposition`
 * `:response_content_encoding`

 are specified as an argument, preceding code works fine. Only `:reponse_expires` raises exceptions.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-sdk-s3` `1.8.2`

##### Gemfile

```
$ cat Gemfile
source 'https://rubygems.org'

gem 'aws-sdk-s3'
```

```
$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    aws-partitions (1.70.0)
    aws-sdk-core (3.17.0)
      aws-partitions (~> 1.0)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-kms (1.5.0)
      aws-sdk-core (~> 3)
      aws-sigv4 (~> 1.0)
    aws-sdk-s3 (1.8.2)
      aws-sdk-core (~> 3)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.0)
    aws-sigv4 (1.0.2)
    jmespath (1.3.1)

PLATFORMS
  ruby

DEPENDENCIES
  aws-sdk-s3

BUNDLED WITH
   1.16.1
```

### Version of Ruby, OS environment

```sh
$ ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]
```

### Code snippets / steps to reproduce

1. Prepare a script code (Please see above)
2. Run the script.

backtrace will be like following.

```
[] /tmp $ bundle exec ruby presign.rb
/private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/rest/request/querystring_builder.rb:55:in `build_part': NotImplementedError (NotImplementedError)
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/rest/request/querystring_builder.rb:25:in `block in build'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/rest/request/querystring_builder.rb:24:in `map'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/rest/request/querystring_builder.rb:24:in `build'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/rest/request/endpoint.rb:58:in `apply_querystring_params'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/rest/request/endpoint.rb:24:in `uri'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/rest/request/builder.rb:23:in `populate_endpoint'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/rest/request/builder.rb:8:in `apply'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/rest/handler.rb:7:in `call'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.2/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.2/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.2/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/seahorse/client/request.rb:70:in `send_request'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.2/lib/aws-sdk-s3/presigner.rb:54:in `presigned_url'
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.2/lib/aws-sdk-s3/customizations/object.rb:189:in `presigned_url'
	from presign.rb:12:in `<main>'
```

----

### my examination

As far as I looked sources and documentations, `Aws::S3::Object#presigned_url` invokes `Aws::S3::Client#get_object` internally and  `Aws::S3::Client#get_object` seems to be able to take `:reponse_expires` as an valid argument.

 * [Aws::S3::Object#presigned_url](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/customizations/object.rb#L156-L163)
 * [Aws::S3::Client#get_object](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/client.rb#L2457-L2458)

##### Examining the backtrace

```
/private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/rest/request/querystring_builder.rb:55:in `build_part': NotImplementedError (NotImplementedError)
	from /private/tmp/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/rest/request/querystring_builder.rb:25:in `block in build'
```

Exception is raised in `aws-sdk-core/rest/request/querystring_builder.rb` build_part()

https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/rest/request/querystring_builder.rb#L31-L57,

```ruby
        def build_part(shape_ref, param_value)
          case shape_ref.shape # 👈👈👈
          # supported scalar types
          when StringShape, BooleanShape, FloatShape, IntegerShape, StringShape
            param_name = shape_ref.location_name
            "#{param_name}=#{escape(param_value.to_s)}"
          when MapShape
            if StringShape === shape_ref.shape.value.shape
              query_map_of_string(param_value)
            elsif ListShape === shape_ref.shape.value.shape
              query_map_of_string_list(param_value)
            else
              msg = "only map of string and string list supported"
              raise NotImplementedError, msg
            end
          when ListShape
            if StringShape === shape_ref.shape.member.shape
              list_of_strings(shape_ref.location_name, param_value)
            else
              msg = "Only list of strings supported, got "
              msg << shape_ref.shape.member.shape.class.name
              raise NotImplementedError, msg
            end
          else
            raise NotImplementedError # 👈👈👈
          end
        end`
```

When invoking `presigned_url(:get, reponse_expires: ... )`, `shape_ref.shape` in build_part()
 will be a instance of `Seahorse::Model::Shapes::TimestampShape`.

However, build_part() doesn't handle the cases of being `TimestampShape`, so it raises `NotImplementedError`.

**Comment by awood45** [comment] 2018-03-16 20:54
I'm able to reproduce this, looks like a valid use case as well. I have a guess as to where this regression came in as well.

**Comment by awood45** [comment] 2018-03-19 19:39
We're working on some test failures in PR #1731 which is the proposed fix for this. Once we can sort that out, will go out with the next release.

**Comment by awood45** [comment] 2018-03-20 16:03
Closing, this will go out with the next release. Will note the version number of core after releasing, and then feel free to reopen if issues recur.

**Closed by awood45** 2018-03-20 16:03 UTC
Labels: Version 3, bug

**Comment by hiboma** [comment] 2018-03-21 03:13
Thank you. I appreciate it !
