### ISSUE TITLE
Aws::EC2::Types::BlockDeviceMapping#no_device does not work/not documented well.

### ISSUE THREAD

**Issue by dElogics** [aws/aws-sdk-ruby#1472] opened 2017-03-26 10:24 UTC
At least I could not get this to work.

My defs as follows -- 

removeMapping = Aws::EC2::Types::BlockDeviceMapping.new
removeMapping.no_device = '/dev/sdc'
removeMapping.device_name = '/dev/sdc'
removeMapping.ebs = nil

And I always get -- 
/usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.50/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The request received was invalid. (Aws::EC2::Errors::InvalidRequest)
When using it with create_instances

**Comment by cjyclaire** [comment] 2017-03-27 22:26
@dElogics I did a quick debugging, looks like the issue is with your `.no_device` value, API reference [here](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_BlockDeviceMapping.html). Could you verify that and try again? SDK can only validate parameter based on their shapes, and this is an error from server side. [`dry_run`](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#create_image-instance_method) (I don't see `#create_instances`, so I'm testing your snippet with `#create_image` instead) flag would be quite helpful when you are debugging those issues :)

Feel free to get involved with [`AWS Support`](https://github.com/aws/aws-sdk-ruby#getting-help) as well if this really frustrates you :) Your feedback will be highly appreciated. If you still finds this might be a SDK bug, I'll be more than happy to dig deeper into the issue with you.
Hope this helps :)

**Comment by cjyclaire** [comment] 2017-03-28 17:38
Closing, since this relates to API behavior instead of SDK bug, feel free to reopen with further details if you feel it still feels like a SDK bug :) Thanks

**Closed by cjyclaire** 2017-03-28 17:38 UTC
Labels: Documentation, service api, usage-question, Version 2

**Comment by dElogics** [comment] 2017-03-30 16:36
When setting dry run to true, I got -- 

```
/usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.50/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Request would have succeeded, but DryRun flag is set. (Aws::EC2::Errors::DryRunOperation)
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.50/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.50/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.50/lib/seahorse/client/plugins/response_target.rb:21:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.50/lib/seahorse/client/request.rb:70:in `send_request'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.50/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-resources-2.6.50/lib/aws-sdk-resources/request.rb:24:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-resources-2.6.50/lib/aws-sdk-resources/operations.rb:41:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-resources-2.6.50/lib/aws-sdk-resources/operations.rb:87:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/aws-sdk-resources-2.6.50/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
        from ./aws.rb:114:in `<main>'
```

Sure it's a server side response, but it might be that SDK is not transforming the request well, because at least from the GUI can remove devices.

Also from the documentation that you pointed, it's still not clear what will be the value of no_device. Should it be the device node?
