### ISSUE TITLE
Ruby SDK does not include S3 instruction file identifier

### ISSUE THREAD

**Issue by cory-p-oncota** [aws/aws-sdk-ruby#1426] opened 2017-02-17 18:08 UTC
All other SDKs which support client-side encryption set and depend on the existence of the `x-amz-crypto-instr-file` on instruction files. Currently, any files uploaded via the Ruby SDK cannot be decrypted by the other SDKs.

**Comment by awood45** [comment] 2017-02-17 18:16
Which version of the SDK are you using, for reference? We do have tests to ensure encryption and decryption works across SDKs, so I'd like to reproduce your issue.

**Comment by cory-p-oncota** [comment] 2017-02-17 18:25
Ruby SDK is at 2.3.22
Java SDK is at 1.11.3

The Java client complains "Unable to detect encryption information for object", however, when the header is added to the instruction file manually, the file is successfully decrypted.

**Comment by awood45** [comment] 2017-02-17 20:33
Thanks for that, we'll look in to this.

**Comment by awood45** [comment] 2017-02-17 23:40
It looks like this may be an issue with the Java SDK, as that metadata doesn't seem to be used. We're tracking it (you don't need to file a new issue with the Java SDK repo), but just wanted to update.

**Comment by cory-p-oncota** [comment] 2017-02-18 05:14
It did seem that the header was completely unused by the client, but was absolutely dependent on its presence. We've currently moved our troublesome task into a Scala job, but we're very unsure where Amazon stands on the approach considering that the .NET and Java clients both set the header. Ultimately, it seems unnecessary as all clients require explicit definition of instruction file location.

**Comment by awood45** [comment] 2017-02-22 23:51
We're working on a fix to the Java SDK currently. I'll update when there's a Java update to consume, then we can close this issue.

**Comment by awood45** [comment] 2017-02-24 17:34
The AWS SDK for Java has released version `1.11.96` which fixes this issue on their end. Upgrade your Java SDK and you should no longer have this issue. If you do, feel free to reopen. Thanks for the report!

**Closed by awood45** 2017-02-24 17:34 UTC
Labels: pending, Version 2
