### ISSUE TITLE
NotImplementedError: #exists? is not implemented for Aws::CloudWatch::Alarm

### ISSUE THREAD

**Issue by tyler-ball** [aws/aws-sdk-ruby#1171] opened 2016-04-29 15:31 UTC
When calling http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudWatch/Resource.html#alarm-instance_method with the name of a non-exist alarm I get back a `Aws::CloudWatch::Alarm` object.

I would expect this to either raise `Aws::CloudWatch::Errors::NoSuchEntity` or allow me to call `exists?` on the object returned. Right now I'm having to call [`client.describe_alarms(["does_not_exist"])`](http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudWatch/Client.html#describe_alarms-instance_method) and check if the response is empty.

This is with the SDK 2.3.0

**Comment by awood45** [comment] 2016-04-29 23:09
You wouldn't get a `NoSuchEntity` error since we lazy load resources by design - we won't make a client call for you until we have to. However, adding an `exists?` method is a good feature request.

**Comment by tyler-ball** [comment] 2016-05-02 13:42
Thanks @awood45 - I looked at other places we were catching the `NoSuchEntity` error and it was because we were calling `.load`. Lazy loading FTW

**Comment by awood45** [comment] 2016-06-06 23:26
I've created an `:alarm_exists` waiter, and the corresponding `Aws::CloudWatch::Alarm#exists?` method. It's currently pending review before it can be pushed out to all the SDKs.

**Comment by awood45** [comment] 2016-06-07 16:52
Feature will be included in the next release.

**Closed by awood45** 2016-06-07 16:52 UTC
Labels: feature request, Version 2

**Comment by tyler-ball** [comment] 2016-06-15 17:59
Thanks @awood45 !
