### ISSUE TITLE
copy_from and copy_to not working when a object file with a space is used and multipart_copy enabled

### ISSUE THREAD

**Issue by johan-smits** [aws/aws-sdk-ruby#1143] opened 2016-03-29 13:32 UTC
When I copy a object from a source bucket to a new bucket and the source file has a space, it fails with the multipart => true.

The source_object.key is for example: "foo bar.baz"

Code:
```ruby
source_object.copy_to("#{AWS_S3_GLACIER_DIR}/#{target_object.key}",
                                     {multipart_copy: (source_object.size > 5.megabytes)})
```

Back trace:
```
/var/lib/gems/2.1.0/gems/aws-sdk-core-2.2.30/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Aws::S3::Errors::NotFound
	from /var/lib/gems/2.1.0/gems/aws-sdk-core-2.2.30/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'
	from /var/lib/gems/2.1.0/gems/aws-sdk-core-2.2.30/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /var/lib/gems/2.1.0/gems/aws-sdk-core-2.2.30/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /var/lib/gems/2.1.0/gems/aws-sdk-core-2.2.30/lib/seahorse/client/request.rb:70:in `send_request'
	from /var/lib/gems/2.1.0/gems/aws-sdk-core-2.2.30/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /var/lib/gems/2.1.0/gems/aws-sdk-resources-2.2.30/lib/aws-sdk-resources/services/s3/object_multipart_copier.rb:124:in `source_size'
	from /var/lib/gems/2.1.0/gems/aws-sdk-resources-2.2.30/lib/aws-sdk-resources/services/s3/object_multipart_copier.rb:31:in `copy'
	from /var/lib/gems/2.1.0/gems/aws-sdk-resources-2.2.30/lib/aws-sdk-resources/services/s3/object_copier.rb:31:in `copy_object'
	from /var/lib/gems/2.1.0/gems/aws-sdk-resources-2.2.30/lib/aws-sdk-resources/services/s3/object_copier.rb:15:in `copy_from'
	from /var/lib/gems/2.1.0/gems/aws-sdk-resources-2.2.30/lib/aws-sdk-resources/services/s3/object.rb:66:in `copy_from'
	from ./S3Backup:45:in `block (2 levels) in <main>'
	from /var/lib/gems/2.1.0/gems/aws-sdk-resources-2.2.30/lib/aws-sdk-resources/batch.rb:75:in `each'
	from /var/lib/gems/2.1.0/gems/aws-sdk-resources-2.2.30/lib/aws-sdk-resources/batch.rb:75:in `each'
	from /var/lib/gems/2.1.0/gems/aws-sdk-resources-2.2.30/lib/aws-sdk-resources/batch.rb:75:in `each'
	from /var/lib/gems/2.1.0/gems/aws-sdk-resources-2.2.30/lib/aws-sdk-resources/collection.rb:18:in `block in each'
	from /var/lib/gems/2.1.0/gems/aws-sdk-resources-2.2.30/lib/aws-sdk-resources/operations.rb:130:in `block in all_batches'
	from /var/lib/gems/2.1.0/gems/aws-sdk-core-2.2.30/lib/aws-sdk-core/pageable_response.rb:75:in `each'
	from /var/lib/gems/2.1.0/gems/aws-sdk-resources-2.2.30/lib/aws-sdk-resources/operations.rb:129:in `all_batches'
	from /var/lib/gems/2.1.0/gems/aws-sdk-resources-2.2.30/lib/aws-sdk-resources/collection.rb:18:in `each'
	from /var/lib/gems/2.1.0/gems/aws-sdk-resources-2.2.30/lib/aws-sdk-resources/collection.rb:18:in `each'
	from ./S3Backup:39:in `block in <main>'
	from ./S3Backup:34:in `each'
	from ./S3Backup:34:in `<main>'
```

**Comment by Doug-AWS** [comment] 2016-03-29 14:05
This is V1 of the Ruby SDK, right? I would recommend moving to V2, as it's been out over a year. The AWS SDK for Ruby Developer Guide, http://docs.aws.amazon.com/sdk-for-ruby/latest/DeveloperGuide/, has some S3 samples you can use and the S3 docs have some Ruby examples you can use, although the latter still has some V1 code that is currently being reworked for V2. The S3 Ruby SDK V1 sample of copy_to is here: http://docs.aws.amazon.com/AmazonS3/latest/dev/CopyingObjectUsingRuby.html.

I don't see the mulipart_copy option in copy_to. It's there as use_mulitpart_copy, not multipart_copy in copy_from.

http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3/S3Object.html#copy_to-instance_method

doug

**Comment by awood45** [comment] 2016-03-29 16:35
This should be working (nothing about a space character should break this), I'll try to reproduce on my end.

**Comment by awood45** [comment] 2016-03-29 16:44
I'm able to replicate this issue on my end, thanks for the report and I'm looking at it now.

**Comment by awood45** [comment] 2016-03-29 16:54
Specifically, it looks like we are URL encoding that space twice, which is leading to the 404 (we're calling `#head_object` on an object that doesn't exist).

**Comment by awood45** [comment] 2016-03-29 23:25
I'm working through some edge cases in the proposed fix for other URL encoding cases. The referenced pull request code will fix your case, but it breaks for other URL encoding situations.

**Comment by awood45** [comment] 2016-03-31 23:28
This should be resolved by that PR, and will go out with the next release. Thanks for the report!

**Closed by awood45** 2016-03-31 23:28 UTC
Labels: bug, Version 2

**Comment by johan-smits** [comment] 2016-04-01 07:44
Thnx for the quick fix. Waiting for the new release to come out.
