### ISSUE TITLE
Unexpected behavior of CGI#unescape when required via aws-sdk

### ISSUE THREAD

**Issue by bankair** [aws/aws-sdk-ruby#1493] opened 2017-04-25 09:46 UTC
Hi Folks,

I'm currently using aws-sdk 2.9.11, and it seems to have a bad side effect on the behavior of CGI#unescape.

Ruby version: mri 2.4.1

Gemfile:
```
source 'https://rubygems.org'
gem 'aws-sdk', '~> 2'
```

Test file:
```
require 'aws-sdk'
# The next line should print 'foo bar'
puts CGI.unescape('foo%20bar')
```

What I expected: an output line showing 'foo bar'.

What I got:
the following exception:
```
test.rb:3:in `unescape': uninitialized class variable @@accept_charset in #<Class:CGI> (NameError)
Did you mean?  @@accept_charset
	from test.rb:3:in `<main>'
```

An easy workaround is adding an explicit `require "CGI"` before (or after) the aws sdk require:

```
require 'CGI'
require 'aws-sdk'
# The next line prints 'foo bar'
puts CGI.unescape('foo%20bar')
```

**Comment by awood45** [comment] 2017-04-25 14:47
This definitely looks like a side effect of #1487 - and the best possible workaround seems to be what you've already discovered, to require the rest of the `cgi` library as needed.

However the exception is very unhelpful...considering if we should return the old require pattern.

**Comment by bankair** [comment] 2017-04-26 12:28
Yep, I agree on the usefulness of the exception 😄

**Comment by cjyclaire** [comment] 2017-04-27 16:59
Adding info.

Looks like this is another problem with Ruby 2.4, I can reproduce the same error there. For Ruby 2.3, it works fine though. Definitely an issue that we will follow up with.

**Comment by awood45** [comment] 2017-04-27 17:46
Okay, given that this seems to be a Ruby 2.4 change in `cgi`, it's probably easiest to just patch that now be reverting to the full CGI import now, and figure out what they changed later.

**Comment by awood45** [comment] 2017-04-27 17:48
On second thought, the bug label is inappropriate given that the weirdness seems to center on Ruby proper (consider opening an issue with them), but I'll change the import strategy regardless.

**Comment by awood45** [comment] 2017-04-27 17:51
I've pushed a fix to this that will go out with the next release.

**Closed by awood45** 2017-04-27 17:51 UTC
Labels: Ruby 2.4, Version 2
