### ISSUE TITLE
PUT Versioning Incorrectly Succeeds

### ISSUE THREAD

**Issue by mike-bailey** [aws/aws-sdk-ruby#1919] opened 2018-11-16 23:22 UTC
Please fill out the sections below to help us address your issue

### Issue description

Despite having versioning take without issue according to the SDK, the next sent call proceeds to fail, claiming the versioning failed.

![image](https://user-images.githubusercontent.com/7607089/48652285-b12e4580-e9cc-11e8-99f0-9f18de839df5.png)

I can understand if this call is asynchronous and that the response of the PUT doesn't imply the operation completed, but if that's the case there would/should be a callback.

###

```
puts s3_client.put_bucket_versioning(
      bucket: 'datahere',
      versioning_configuration: {
        status: 'Enabled'
      }
    ).inspect
    # Initialize Cross region replication
    puts s3_client.put_bucket_replication(
      bucket: 'datahere',
      replication_configuration: { # required
        role: 'arn:aws:iam::xxxxxx:role/xxxxx', # required
        rules: [ # required
          {
            prefix: '*', # required
            status: 'Enabled', # required, accepts Enabled, Disabled
            destination: { # required
              bucket: 'arn:aws:s3:::namehere', # required
              storage_class: 'STANDARD', # accepts STANDARD, REDUCED_REDUNDANCY, STANDARD_IA
            }
          }
        ]
      },
      use_accelerate_endpoint: false
    ).inspect
```

**Comment by srchase** [comment] 2018-11-17 00:58
Thanks for opening this issue.

Just to be clear, versioning is successfully enabled on the origin bucket, but just not in time for the put_bucket_replication call to succeed?

**Comment by mike-bailey** [comment] 2018-11-17 00:59
Seems like it, yes.

**Comment by mike-bailey** [comment] 2018-11-17 00:59
Given they're run synchronously I'd expect one to pass after another.

**Comment by srchase** [comment] 2018-11-19 20:58
Do you see this error every time?  Or does ```put_bucket_replication``` sometimes succeed?

Also, are these newly created or existing buckets?

**Comment by mike-bailey** [comment] 2018-11-19 21:14
It’s occasional. It’s an app that provisions a distinct stack so the bucket create comes a few calls earlier.

**Comment by srchase** [comment] 2018-11-19 22:58
@mike-bailey 

Thanks for following up.

I have not been able to reproduce this issue, but the evidence indicates that the SDK is executing ```put_bucket_versioning``` and ```put_bucket_replication``` as expected.   S3's underlying consistency model is the likely culprit for what's happening on the service side.  Unfortunately, I don't have documentation from S3 that spells out the impact of enabling versioning on subsequent calls to add bucket replication.

If you capture the Request IDs, the S3 service team may be able to assist further on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=24).  Optionally, you could retry setting up replication when you encounter this error, or make a call to confirm that versioning is enabled before doing the ```put_bucket_replication``` call.

**Comment by mike-bailey** [comment] 2018-11-19 23:00
I did capture request ID's so I'll post those.

>Optionally, you could retry setting up replication when you encounter this error

Wouldn't this require each of my calls having a fallback for the subsequent calls? We make a number of S3 calls that are dependent on the prior one passing, so is the logic that it should go back a step if it fails? We'd risk infinite loops in that case so unfortunately that's a bit of a non-solution.

**Comment by mike-bailey** [comment] 2018-11-19 23:01
Thank you for replying.

To clarify:

>the evidence indicates that the SDK is executing put_bucket_versioning and put_bucket_replication as expected

I think it's a little strange to say this is _as expected_, as it returns no errors but didn't actually happen, so I'm not sure how that's useful to a developer.

**Comment by mike-bailey** [comment] 2018-11-19 23:09
Not a callback, but something to be able to determine if a call was actually completed.

Additionally, is there a way to remove the “close if no response tag”? My average response time on this issue has been under a minute :smile:

**Comment by mike-bailey** [comment] 2018-11-19 23:37
Thanks. I can get the request IDs and I understand I can implement my own waiters, but this isn’t the only AWS service and only S3 interaction we use in our app, so would we be implementing waiters for all of it? We just spotted this issue like a week or two ago and we have been using this codebase for probably 6mo+

**Comment by mike-bailey** [comment] 2018-11-19 23:42
>I'm curious if you see that returning "Disabled" or not.

I can’t think of how to reproduce this without polluting our account (we have a lot of sns stuff) since it would take a number of calls to replicate since it only happens on occasion

**Comment by mike-bailey** [comment] 2018-11-20 01:46
![image](https://user-images.githubusercontent.com/7607089/48746139-176ccf80-ec3c-11e8-8ffb-d1e7f6546e43.png)

Less redacted for IDs

**Comment by srchase** [comment] 2018-11-20 16:48
@mike-bailey 

Thanks for replying.  I've opened in an internal ticket with the Service Team.  I will update you when I have a response.

**Comment by mike-bailey** [comment] 2018-11-21 04:32
Is there anywhere I can put them out-of-band? I'm relatively low on the food chain at a forensic company so I have to limit public commentary on particulars like bucket names.

As for request ID, none of that is redacted, but I can pull whatever else I have in logs, sure.

**Comment by srchase** [comment] 2018-11-21 17:00
@mike-bailey 

Does your organization have an AWS Support plan?

You could open a case with  [AWS Premium Support](https://console.aws.amazon.com/support/home#/).

**Comment by mike-bailey** [comment] 2018-11-26 07:45
We have one planned, but haven't gotten it yet. Have to wait for a budget to hit that's way above my pay grade. 😄

**Comment by mike-bailey** [comment] 2018-11-26 07:45
Granted, this made it easier to justify

**Comment by srchase** [comment] 2018-11-27 00:43
@mike-bailey 

I'm going to close this issue for now.  Happy to re-open if there's any followup once you've engaged Support and the Service Team.

**Comment by mike-bailey** [comment] 2018-11-27 01:03
I’m still confused as to how this isn’t an SDK issue. So the argument is if there’s a PUT versioning request then a PUT lifecycle request via the SDK the SDK doesn’t garauntee they’ll take in order?

**Comment by mike-bailey** [comment] 2018-11-27 01:04
And if the point is “yes but implement a waiter”, shouldn’t there be a waiter available in the SDK given this is a pretty common scenario in s3?

**Comment by srchase** [comment] 2018-11-27 17:14
@mike-bailey 

We can track this as a feature request to implement a waiter.

**Comment by mullermp** [comment] 2020-07-09 17:11
I went to go implement this waiter, but I'm noticing S3's get/put bucket replication is instant.. Perhaps at the time there was some delay? There's nothing to wait for.

**Closed by mullermp** 2020-07-09 17:11 UTC
Labels: feature-request, service-api, waiter

**Comment by mike-bailey** [comment] 2020-12-02 21:47
It didn't have strong concurrency. With the new re:Invent announcements, I think this is _actually_ done now.

**Comment by mullermp** [comment] 2020-12-02 22:02
I'm glad to hear. I'm sorry for the delay on this. When this issue was opened, I wasn't working on the Ruby SDK. I don't remember the details, but I looked at this on July 9 and it looked instantaneous to me and I couldn't reproduce. But I'm glad it's finally addressed. :D
