### ISSUE TITLE
JMESPath::Errors::SyntaxError: unexpected token 0 on Aws::EC2::Instance exists?

### ISSUE THREAD

**Issue by kpmueller** [aws/aws-sdk-ruby#1234] opened 2016-07-06 22:45 UTC
When using the .exists? method on a Aws::EC2::Instance which refers to an existing instance, the following error is produced:

JMESPath::Errors::SyntaxError: unexpected token 0

in jmespath

This is using:

aws-sdk (2.3.20)
jmespath (1.2.4)

instances which don't exist return false, as expected.

demo/stack trace:

irb(main):003:0> i = ec2.instance('i-c9ba4e31')
=> #<Aws::EC2::Instance id="i-c9ba4e31">
irb(main):004:0> i.exists?
JMESPath::Errors::SyntaxError: unexpected token 0
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/jmespath-1.2.4/lib/jmespath/parser.rb:50:in `method_missing'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/jmespath-1.2.4/lib/jmespath/parser.rb:61:in `expr'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/jmespath-1.2.4/lib/jmespath/parser.rb:161:in `led_comparator'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/jmespath-1.2.4/lib/jmespath/parser.rb:63:in `expr'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/jmespath-1.2.4/lib/jmespath/parser.rb:39:in `parse'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/jmespath-1.2.4/lib/jmespath/caching_parser.rb:25:in `block in cache_expression'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/jmespath-1.2.4/lib/jmespath/caching_parser.rb:23:in `synchronize'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/jmespath-1.2.4/lib/jmespath/caching_parser.rb:23:in `cache_expression'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/jmespath-1.2.4/lib/jmespath/caching_parser.rb:16:in `parse'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/jmespath-1.2.4/lib/jmespath/runtime.rb:56:in `search'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/jmespath-1.2.4/lib/jmespath.rb:47:in `search'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/waiters/poller.rb:70:in `matches_path?'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/waiters/poller.rb:65:in `acceptor_matches?'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/waiters/poller.rb:49:in `block in call'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/waiters/poller.rb:48:in `each'
	from /Users/karl/piazza/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/waiters/poller.rb:48:in `call'
... 32 levels...

**Comment by awood45** [comment] 2016-07-07 16:34
This appears to be related to a JMESpath/JSON issue that has come up recently. A fix is being worked on for the `jmespath` gem (which we also maintain) and I'll update this space once it is released.

**Comment by trevorrowe** [comment] 2016-07-07 23:13
I've pushed jmespath 1.3.0 which should address this issue.

**Comment by antoniobeyah** [comment] 2016-07-10 20:12
Same issue here, even with jmespath 1.3.0.  Although the error message is slightly different.  It appears that adding json_pure v2.0.1 causes this to blow up, but using 1.8.3 the error goes away.

To reproduce:

*Gemfile*
```ruby
source 'https://rubygems.org'

gem 'aws-sdk', '= 2.3.21'
gem 'json_pure', '= 2.0.1'
```

*Excerpt from Gemfile.lock*
```
    aws-sdk (2.3.21)
      aws-sdk-resources (= 2.3.21)
    aws-sdk-core (2.3.21)
      jmespath (~> 1.0)
    aws-sdk-resources (2.3.21)
      aws-sdk-core (= 2.3.21)
    jmespath (1.3.0)
    json_pure (1.8.3)
```

*script.rb*
```ruby
#!/usr/bin/env ruby

require 'aws-sdk'
ec2 = ::Aws::EC2::Client.new(region: 'us-west-2')
# this must point to an instance id that exists to cause the error
ec2.wait_until(:instance_exists, instance_ids: ['i-ebb9547f'])
```

```
-> bundle exec script.rb
JMESPath::Errors::SyntaxError: unknown token "0"
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/jmespath-1.3.0/lib/jmespath/parser.rb:159:in `nud_unknown'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/jmespath-1.3.0/lib/jmespath/parser.rb:61:in `expr'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/jmespath-1.3.0/lib/jmespath/parser.rb:165:in `led_comparator'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/jmespath-1.3.0/lib/jmespath/parser.rb:63:in `expr'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/jmespath-1.3.0/lib/jmespath/parser.rb:39:in `parse'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/jmespath-1.3.0/lib/jmespath/caching_parser.rb:25:in `block in cache_expression'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/jmespath-1.3.0/lib/jmespath/caching_parser.rb:23:in `synchronize'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/jmespath-1.3.0/lib/jmespath/caching_parser.rb:23:in `cache_expression'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/jmespath-1.3.0/lib/jmespath/caching_parser.rb:16:in `parse'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/jmespath-1.3.0/lib/jmespath/runtime.rb:56:in `search'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/jmespath-1.3.0/lib/jmespath.rb:32:in `search'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/waiters/poller.rb:70:in `matches_path?'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/waiters/poller.rb:65:in `acceptor_matches?'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/waiters/poller.rb:49:in `block in call'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/waiters/poller.rb:48:in `each'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/waiters/poller.rb:48:in `call'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/waiters/waiter.rb:104:in `block in poll'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/waiters/waiter.rb:101:in `loop'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/waiters/waiter.rb:101:in `poll'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/waiters/waiter.rb:91:in `block (2 levels) in wait'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/waiters/waiter.rb:90:in `catch'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/waiters/waiter.rb:90:in `block in wait'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/waiters/waiter.rb:89:in `catch'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/waiters/waiter.rb:89:in `wait'
  /Users/USERNAME/.rvm/gems/ruby-2.2.5@all/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/client_waiters.rb:110:in `wait_until'
  script.rb:7:in `<top (required)>'
```

**Comment by trevorrowe** [comment] 2016-07-11 19:34
I haven't tracked down the root cause yet. The `json_pure` gem is no longer in our dependency tree, but I understand that it may still be causing problems with jmespath when loaded. I'm going to continue investigating this issue to see if I can narrow down the root cause here.

**Comment by trevorrowe** [comment] 2016-07-19 17:35
Version 1.3.1 of the `jmespath` gem was released yesterday. This includes a fix for environments where `pure_json` is already loaded into the environment. Can you update `jmespath` and see if this resolves the issue above?

**Comment by trevorrowe** [comment] 2016-07-20 17:30
I'm closing this issue here. The root cause has been addressed in our dependency. Updating `jmespath` to 1.3.1 should resolve this issue for anyone affected.

**Closed by trevorrowe** 2016-07-20 17:30 UTC
Labels: bug, Version 2
