### ISSUE TITLE
Aws::VERSION is not up

### ISSUE THREAD

**Issue by k1LoW** [aws/aws-sdk-ruby#1592] opened 2017-09-01 05:43 UTC
### Issue description

Aws::VERSION is not up

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

- aws-sdk-core

### Version of Ruby, OS environment

```sh
$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]
```

### Code snippets / steps to reproduce

https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/version.rb#L2

**Comment by cjyclaire** [comment] 2017-09-01 16:38
@k1LoW Thanks for catching, working on fix this

**Comment by cjyclaire** [comment] 2017-09-01 16:40
A side note is that for core version, it's tracking [VERSION](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/VERSION) file instead, which has the correct version, I'll remove the redundant one.

**Comment by cjyclaire** [comment] 2017-09-05 18:46
PR has been merged, closing : )

**Closed by cjyclaire** 2017-09-05 18:46 UTC
Labels: pr-in-progress, Version 3

**Comment by JaganNarayanan** [comment] 2017-09-07 10:25
Sorry, newbie here. I get this error 'uninitialized constant Aws::VERSION' when loading my page after using the gem 'aws-sdk'. How do I remove the version file? Will it fix this? Thank you in advance!

**Comment by cjyclaire** [comment] 2017-09-07 17:00
@JaganNarayanan Could you provide more context? Which version of the gem are you on? I tried install the `aws-sdk` gem from scratch and tried several API calls, I cannot reproduce the error here.

**Comment by JaganNarayanan** [comment] 2017-09-08 06:31
Gemfile 
`gem 'aws-sdk'
`
config/environments/development.rb 
`  config.paperclip_defaults = {
      storage: :s3,
      s3_region: ENV["aws_bucket_region"],
      s3_credentials: {
        # s3_host_name: ENV["aws_bucket_name"],
        bucket: ENV["aws_bucket_name"],
        access_key_id: ENV["amazon_key"],
        secret_access_key: ENV["amazon_secret_access_key"]
        }
      }`

config/environment/production.rb
`  config.paperclip_defaults = {
  :storage => :s3,
  :preserve_files => true,
  :bucket => ENV['aws_bucket_name']
}`

That was my code. I also tried using older versions of the gem, 1 & 2 but I get the same version error. Any help would be much appreciated, thanks!

**Comment by easybills-admin** [comment] 2017-09-12 09:00
Possible side effect: https://github.com/thoughtbot/paperclip/issues/2484
