### ISSUE TITLE
:http_response_body in log formatter errors with BlockIO

### ISSUE THREAD

**Issue by nate** [aws/aws-sdk-ruby#1464] opened 2017-03-22 19:53 UTC
If the log formatter string includes `:http_response_body` and a logger is set a `NoMethodError` is raised.

Code to recreate the error:

```ruby
require "rubygems"
require "logger"
require "aws-sdk"

access_key_id = ""
secret_access_key = ""
region = ""
bucket = ""
key = ""

credentials = Aws::Credentials.new(access_key_id, secret_access_key)
log_formatter = Aws::Log::Formatter.new(":http_response_body")
logger = Logger.new(STDOUT)

client = Aws::S3::Client.new(region: region, credentials: credentials, log_formatter: log_formatter, logger: logger)

client.get_object(bucket: bucket, key: key){|_chunk| }
```

Backtrace:

```
/Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/seahorse/client/http/response.rb:45:in `body_contents': undefined method `rewind' for #<Seahorse::Client::BlockIO:0x007fb46a6e8068> (NoMethodError)
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/aws-sdk-core/log/formatter.rb:174:in `_http_response_body'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/aws-sdk-core/log/formatter.rb:100:in `block in format'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/aws-sdk-core/log/formatter.rb:100:in `gsub'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/aws-sdk-core/log/formatter.rb:100:in `format'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/aws-sdk-core/plugins/logging.rb:58:in `format'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/aws-sdk-core/plugins/logging.rb:51:in `log'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/aws-sdk-core/plugins/logging.rb:41:in `block in call'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/aws-sdk-core/plugins/logging.rb:39:in `tap'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/aws-sdk-core/plugins/logging.rb:39:in `call'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/aws-sdk-core/plugins/s3_dualstack.rb:24:in `call'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/aws-sdk-core/plugins/s3_accelerate.rb:34:in `call'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/seahorse/client/plugins/response_target.rb:21:in `call'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/seahorse/client/request.rb:70:in `send_request'
from /Users/nate/.rvm/gems/ruby-2.2.2@test-gemset/gems/aws-sdk-core-2.8.9/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
from test_block_io_bug.rb:20:in `<main>'
```

**Comment by nate** [comment] 2017-03-22 19:56
This could be fixed by changing the `_http_response_body` instance method on `Aws::Log::Formatter` to this:

```ruby
def _http_response_body(response)
  if response.context.http_response.body.respond_to?(:rewind)
    @param_formatter.summarize(response.context.http_response.body_contents)
  end
end
```

**Comment by nate** [comment] 2017-03-22 20:00
Alternatively, `Seahorse::Client::Http::Response#body_contents` could raise a specific exception in this case, something like `UnreadableBodyError` or similar, and that specific exception could be caught here.

**Comment by cjyclaire** [comment] 2017-03-24 21:25
@nate Thanks for the information! The issue is using [`Response`](http://docs.aws.amazon.com/sdkforruby/api/Seahorse/Client/Response.html) directly, it's passing a [`BlockIO`](http://docs.aws.amazon.com/sdkforruby/api/Seahorse/Client/BlockIO.html) that doesn't have `#rewind` method.
 
So a quick one line workaround first:
``` ruby
 # use body of response instead
  s3.get_object(bucket: 'a-fancy-bucket', key: 'key_my').body {|c| puts c.inspect}
```

Personally, the fix in `Aws::Log::Formatter` appears as a hard coded fix to me, since the cause actually lies in response, log formatter just helps uncover it. Yet I agreed that more helpful exception message would be beneficial. I'll open a PR shortly to address this, thanks :)

**Comment by nate** [comment] 2017-03-24 23:11
The issue for us is that a log format can cause an exception to be raised. That shouldn't be the case, in my opinion. I can't optionally include exclude a field from the log format when the response is `BlockIO`.

Maybe some background would help? We're wrapping an S3 client instance with our own code. This code creates the client with some defaults (including setting the log format and passing in the logger) and when executing operations it handles a few conveniences (extra logging, instrumentation, etc). Sometimes downloads get are passed a block and we allow it.

If the log format can cause exceptions to be raised we will either need to write our own log formatter which would duplicate everything in `Aws::Log::Formatter` except catch an exception or we will need to keep two S3 client objects around and call one or the other depending on if a block is passed.

It seems much more sensible for `_http_response_body` to return nil or some sort of indicator that the body is irretrievable, since it's just a convenience method for logging.

**Comment by cjyclaire** [comment] 2017-04-07 00:12
@nate Appreciate the patience, and thanks for the clarification. The reason why I'm raising error instead of letting it go silently is that the usage is actually taking in a wrong `.body`.

I'm open to better solutions to make debugging experience better. Yet noted that using the block directly will lead to wrong body, and this is not a good practice. Even if I have `warn` instead of `raise`, the error will be uncovered later in the chain any ways.

I'm a bit curious to know why you are looking for catching the exception instead of fixing/working around the error? I noticed that you mentioned:
>  Sometimes downloads are passed a block and we allow it.
Yet I'm assuming that this doesn't mean that you would like wrong input right?

Thoughts?

**Comment by nate** [comment] 2017-04-07 01:44
The reason why I'm raising error instead of letting it go silently is that the usage is actually taking in a wrong .body

    using the block directly will lead to wrong body, and this is not a good practice

I don't understand, isn't the block syntax [supported by the API](https://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#get_object-instance_method)? The block syntax makes certain things possible that would be difficult without it.

I get that you're resistant to catching the error and returning the wrong body, but how about adding a new log formatter field like `:http_response_body_unless_block_io`? Then at least people can opt into the behavior.

I'm not sure how else I'd work around this issue except using two separate s3 clients initialized with two separate log formatters, one for use with block transfers and one for file transfers.

**Comment by cjyclaire** [comment] 2017-04-07 17:17
@nate Apology if my reply has cause the confusion : ) , to clarify first, I'm not suggesting that you shouldn't use block, and as you can see, actually I'm suggesting correct input is important. Silent failure in logging could potential making people ignore the situation and future debugging could be rather painful.

So I'm revisiting your situation, using
``` ruby
client.get_object(bucket: bucket, key: key){|_chunk| }
```
causes error yet
``` ruby
client.get_object(bucket: bucket, key: key).body {|_chunk| }
```
would be the correct behavior that will not lead to error.
May I ask why that fix won't work in your situation? perhaps I'm missing something obvious?

**Comment by nate** [comment] 2017-04-07 17:23
```ruby
client.get_object(bucket: bucket, key: key){|_chunk| }
```

This will stream bytes to the block as they become available, right?

```ruby
client.get_object(bucket: bucket, key: key).body {|_chunk| }
```

And this will download the entire file into memory, right?

Downloading the entire file into memory is unacceptable.

**Comment by cjyclaire** [comment] 2017-04-07 17:55
@nate Ah I see, looks like I misunderstood your initial request somehow, sorry for that, taking a look for proper fix or work-arounds. Now I see why you find `Aws::Log::Formatter` is causing trouble. Will update shortly!

**Comment by nate** [comment] 2017-04-07 18:32
Thanks!

**Comment by cjyclaire** [comment] 2017-04-13 17:52
The fix has been merged in, will be tagged in the next release thanks!

**Closed by cjyclaire** 2017-04-13 17:52 UTC
Labels: enhancement, pr-in-progress, Version 2

**Comment by nate** [comment] 2017-04-13 22:17
Excellent, thanks!
