### ISSUE TITLE
Aws::S3::Presigner on bucket, not key level

### ISSUE THREAD

**Issue by stiller-leser** [aws/aws-sdk-ruby#1528] opened 2017-05-30 14:20 UTC
Is it possible to create a presigned URL for a whole bucket instead of just one specific key? The scenario here would be a bunch of blobs (packaged as form-data) coming from ajax-requests in the browser. They would need to be stored into mybucket.s3-my-region.amazonaws.com/path/to/storage/location .

**Comment by cjyclaire** [comment] 2017-05-30 18:27
@stiller-leser Thanks for the information, first, currently no. PresignedUrls are based on single operation currently, such as `#get_object` or `#put_object`, for those operations `key` is a required parameter as you see. I heard your use case, after a quick thought, I couldn't find a single operation tied to it specifically. 

Meanwhile an enhanced and flexible presigned interface feature has already been in our backlog. We are definitely considering possible bucket level usage. Happy to hear more and figure out how we can make it easier for you with that feature request.

**Comment by awood45** [comment] 2017-05-30 19:17
I think a bit more clarification is needed on what you're trying to do. I can see two approaches - one you can do today with some code, and one that is not possible:

If you want to get presigned URLs for everything in a bucket at a given point, that's not difficult:

```ruby
client = Aws::S3::Client.new
presigner = Aws::S3::Presigner.new
urls = []
client.list_objects(bucket: BUCKET).each_page do |page|
  page.contents.each do |obj|
    urls << presigner.presigned_url(:get_object, bucket: BUCKET, key: obj.key)
  end
end
```

If you want a presigned URL that gives you some sort of navigable, updating interface, the problem is that that's stacking multiple operations, and isn't something presigned URLs can do - they are just a presigned request to S3. For example, you'd need to generate new `:get_object` URLs somewhere with credentials.

If you're trying to go the latter route, I'd recommend looking at tools that help make this easier, like the AWS SDK for JavaScript's browser SDK.

**Comment by stiller-leser** [comment] 2017-05-31 06:30
First off, thanks for the elaborations. I really appreciate it.

The use case here is the following: 
Uploading a file every x seconds from the user's browser directly to AWS S3. Yes, we could send a request every x seconds to the rails server to generate a signed url for that specific use case. The goal however was to minimize the interaction with the server as they could not only potentially DDOS the server when many users are doing the same (I exaggerate intentionally), but the upload is also fairly time critical and interaction with the server might take some of this valuable time.

We did switch to JavaScript SDK for now - which works fine. However our initial goal was to avoid bringing in another service (Cognito).

**Comment by awood45** [comment] 2017-05-31 17:16
Given your requirements, it seems like the JavaScript SDK approach is the right one. Or you could make the S3 objects public and potentially reduce the amount of server-side URL generation you need to do, but I suspect that's not the goal here.

What bringing in Cognito does for you is to help solve the authentication problem. Presigned URLs aren't really designed to do what you're trying to do, so server side generation would be the alternative.

Closing since I think we've gotten to the answer here. Feel free to let me know if you have any follow-up questions.

**Closed by awood45** 2017-05-31 17:16 UTC
Labels: usage-question, Version 2
