### ISSUE TITLE
Aws::S3::Encryption::Client cannot be instantiated with explicitly defined region

### ISSUE THREAD

**Issue by samjdacanay** [aws/aws-sdk-ruby#803] opened 2015-05-01 17:23 UTC
```
1.9.3-p125 :002 > opts = {:access_key_id => "XXXX", :secret_access_key=>"XXXX", :region=>"us-east-1", :encryption_key => "XXXX"}
 => {:access_key_id=>"XXXX", :secret_access_key=>"XXXX", :region=>"us-east-1", :encryption_key=>"XXXX"} 
1.9.3-p125 :003 > client = Aws::S3::Encryption::Client.new(opts)
Aws::Errors::MissingRegionError: missing region; use :region option or export region name to ENV['AWS_REGION']
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/aws-sdk-core-2.0.41/lib/aws-sdk-core/plugins/regional_endpoint.rb:30:in `after_initialize'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/aws-sdk-core-2.0.41/lib/seahorse/client/base.rb:86:in `block in after_initialize'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/aws-sdk-core-2.0.41/lib/seahorse/client/base.rb:85:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/aws-sdk-core-2.0.41/lib/seahorse/client/base.rb:85:in `after_initialize'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/aws-sdk-core-2.0.41/lib/seahorse/client/base.rb:23:in `initialize'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/aws-sdk-core-2.0.41/lib/aws-sdk-core/client_stubs.rb:19:in `initialize'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/aws-sdk-core-2.0.41/lib/seahorse/client/base.rb:107:in `new'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/aws-sdk-resources-2.0.41/lib/aws-sdk-resources/services/s3/encryption/client.rb:183:in `initialize'
	from (irb):3:in `new'
	from (irb):3
	from /usr/local/rvm/rubies/ruby-1.9.3-p125/bin/irb:12:in `<main>'
```

Additional info:
System: Centos 6.6
Ruby Version: 1.9.3-p125

I exported the region as an Environment Variable and that seems to work, but explicit definition in the instantiation of the client seems to be a bug.

**Comment by trevorrowe** [comment] 2015-05-01 17:30
Closed as a duplicate of https://github.com/aws/aws-sdk-ruby/issues/800

The workaround it to construct a vanilla `Aws::S3::Client` and pass that in via `:client`. I corrected the documentation on this, and then expanded the initialize method to accept vanilla client options as well, such as `:region`.

**Comment by trevorrowe** [comment] 2015-05-01 17:30
Sorry for the confusion.

**Closed by trevorrowe** 2015-05-01 17:30 UTC

**Comment by samjdacanay** [comment] 2015-05-01 17:36
Thanks Trevor. I appreciate the clarification!
