### ISSUE TITLE
StringIO  from get_bucket_policy

### ISSUE THREAD

**Issue by asetiawan** [aws/aws-sdk-ruby#1413] opened 2017-02-07 23:01 UTC
Per [api reference](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#get_bucket_policy-instance_method), get_bucket_policy returns GetBucketPolicyOutput, which has   
`resp.policy #=> String`

When I try it out, It returned StringIO instead. is that expected?

Sample test code:
```
s3 = Aws::S3::Client.new(region: 'us-east-1')
bucket_policy = s3.get_bucket_policy(bucket: 's3-bucket-with-policy').policy
bucket_policy_json = JSON.parse(bucket_policy)
puts bucket_policy_json["Statement"]
```

Expected result: JSON object for Statement
Current output:
```
/usr/local/bundle/gems/json-2.0.3/lib/json/common.rb:156:in `initialize': no implicit conversion of StringIO into String (TypeError)
	from /usr/local/bundle/gems/json-2.0.3/lib/json/common.rb:156:in `new'
	from /usr/local/bundle/gems/json-2.0.3/lib/json/common.rb:156:in `parse'
	from test.rb:11:in `<main>'
```
 
Current workaround:
```
bucket_policy_json = JSON.parse(bucket_policy.read)
```

Thanks,
AS

**Comment by awood45** [comment] 2017-02-08 18:57
This seems to be expected behavior (though we're looking in to it). It occurs because it's marked as a "payload" member, which leaves the response member as an IO type. I can see that the documentation isn't reflecting this, so at minimum that's something we should update.

**Comment by cjyclaire** [comment] 2017-06-14 18:49
This has been fixed in V3 documentation (which is compatible with v2 docs).
Closing : )

**Closed by cjyclaire** 2017-06-14 18:49 UTC
Labels: Documentation, service api, Version 2
