### ISSUE TITLE
Aws::EC2::Resource#route_tables filter association.main does not work.

### ISSUE THREAD

**Issue by dElogics** [aws/aws-sdk-ruby#1467] opened 2017-03-24 05:49 UTC
```
nondefRT = Aws::EC2::Types::Filter.new
nondefRT.name = "association.main"
nondefRT.values = ["false"]
myVPC = Aws::EC2::Types::Filter.new
myVPC.name = "vpc-id"
myVPC.values = ["vpc-628c120b"]
resource.route_tables( { :filters => [ myVPC, nondefRT ] }).each do
	|routeTable|
	puts routeTable.id
end
```
Gives no output. But if I set nondefRT.values = ["false"] to nondefRT.values = ["true"] it produces -- 
rtb-b7006dde
i.e. the main routing table.

**Comment by cjyclaire** [comment] 2017-03-24 20:12
@dElogics Thanks for the information, your code snippet looks good, I'm a bit confused about why you say this filter doesn't work, especially it produced correct output for the main routing table.
 
So may I ask more information to see how this troubles?
The `association.main` set to false  helps filter out the main route table in the VPC, if it returns nil, it actually means there is no other route tables except the main table in the VPC specified. Could you try just having `myVPC` in the filters to see the output (all tables)? If it produces the main routing table only, then no output when `false` is actually the correct behavior there.

**Comment by dElogics** [comment] 2017-03-25 05:10
Looks like a verity of issues are being hit (this time it's different) --
```
nondefRT = Aws::EC2::Types::Filter.new
nondefRT.name = "association.main"
nondefRT.values = ["false"]
myVPC = Aws::EC2::Types::Filter.new
myVPC.name = "vpc-id"
myVPC.values = ["vpc-8f1886e6"]
resource.route_tables( { :filters => [ myVPC, nondefRT ] }).each do
	|routeTable|
	puts routeTable.id
end
```
Outputs -- 
rtb-e99af780
rtb-e89af781

```
nondefRT = Aws::EC2::Types::Filter.new
nondefRT.name = "association.main"
nondefRT.values = ["false"]
myVPC = Aws::EC2::Types::Filter.new
myVPC.name = "vpc-id"
myVPC.values = ["vpc-8f1886e6"]
resource.route_tables( { :filters => [ myVPC ] }).each do
	|routeTable|
	puts routeTable.id
end
```
outputs the same -- 
rtb-e99af780
rtb-e89af781

```
nondefRT = Aws::EC2::Types::Filter.new
nondefRT.name = "association.main"
nondefRT.values = ["true"]
myVPC = Aws::EC2::Types::Filter.new
myVPC.name = "vpc-id"
myVPC.values = ["vpc-8f1886e6"]
resource.route_tables( { :filters => [ myVPC, nondefRT ] }).each do
	|routeTable|
	puts routeTable.id
end
```
Produces 
rtb-e99af780

**Comment by cjyclaire** [comment] 2017-03-27 21:48
@dElogics I can reproduce this, thanks for reporting, looks like when `association.main` is set to `false`, it doesn't work properly, I reached out to service team for this problem, will keep updated.

Meanwhile, our [`Getting Help`](https://github.com/aws/aws-sdk-ruby#getting-help) section has been updated recently, free feel to get help from `Aws Support` as well if this has been blocking for a while : )

**Comment by cjyclaire** [comment] 2017-03-28 17:33
@dElogics I digger deeper into this behavior and found that "association.main, false" won't work if the route table doesn't have [association](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/RouteTableAssociation.html) at all (which is the default behavior if you create a route table under VPC from AWS console). I have asked for better documentation from service team about this.

Closing. since this doesn't seem to be a SDK bug, rather than an API behavior, if you still struggle with the API, feel free to cut a ticket for [AWS Support](https://github.com/aws/aws-sdk-ruby#getting-help) as our latest `README` suggest :)

**Closed by cjyclaire** 2017-03-28 17:33 UTC
Labels: service api, usage-question, Version 2
