### ISSUE TITLE
Using the built-in waiter to wait for CloudFormation stacks to reach the CREATED state results in an uncaught rate limiting exception

### ISSUE THREAD

**Issue by pdrakeweb** [aws/aws-sdk-ruby#1478] opened 2017-04-06 14:48 UTC
We are using the built-in waiter with the default configuration to wait for CloudFormation stacks to reach the CREATED state.  We are regularly encountering uncaught exceptions related to rate limiting.  We would expect that the default configuration of the built-in waiters would be designed to avoid hitting rate limits in the AWS APIs.

Expected behavior: The waiter waits for a stack to reach the desired state.
Actual behavior: The waiter raises an uncaught Rate Limit exception.

**Comment by cjyclaire** [comment] 2017-04-06 16:20
@pdrakeweb A quick follow up question to make sure I'm reproducing based on the same waiter, are you suggesting this [waiter](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/apis/cloudformation/2010-05-15/waiters-2.json#L29) in particular?

**Comment by pdrakeweb** [comment] 2017-04-06 17:11
Yes, that is the waiter.

**Comment by awood45** [comment] 2017-04-06 18:00
Do you have multiple operations against CloudFormation occurring across processes/threads while running this? I can check what those API rate limits are, but we do generally work to account for that and this waiter actually has a much longer delay than some other waiters in the same waiter collection.

**Comment by pdrakeweb** [comment] 2017-04-06 18:16
Yes, we are commonly creating, updating and deleting many CloudFormation stacks in many different processes simultaneously.

**Comment by awood45** [comment] 2017-04-06 18:22
That would explain it - it's possible that between all of your processes, you're hitting the API limit. Unfortunately, the built-in rates can't account for the fact that API limits are across different call sources. There are a couple workarounds you can do:

- The [wait_until documentation](http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudFormation/Client.html#wait_until-instance_method) shows how you can modify the polling period and maximum retries. You could set longer polling periods and find a rate that works for your usage rates.
- You can also implement retries around your waiter calls, starting a waiter over (perhaps with an even longer polling period) when you encounter a throttling error.

Closing because I think we've gotten to the root of it. Feel free to add any follow-up questions you have.

**Closed by awood45** 2017-04-06 18:22 UTC
Labels: usage-question, Version 2

**Comment by pdrakeweb** [comment] 2017-04-07 18:31
@awood45 given the use of more than one CloudFormation stack in a single AWS account is likely a common use-case (and is expected to result in Throttling errors), is there a reason why the waiters shouldn't handle Throttling errors as a retry-able response (see https://github.com/aws/aws-sdk-ruby/compare/master...pdrakeweb:retry-throttled-cf-requests).

**Comment by awood45** [comment] 2017-04-07 18:35
One potential issue is that silently wrapping that error at this point would be a breaking behavior change. Anyone relying on those errors to be surfaced would instead potentially punch through their throttle limits.

It is an interesting question to see if we could expose the ability to expand the set of errors we retry on an opt-in basis, but not by default.

**Comment by pdrakeweb** [comment] 2017-04-07 18:48
I understand the concern, however, since throttling is part of the black box of AWS' APIs (and is thus entirely unpredictable) is it really reasonable for someone to expect to reliably fail to poll because of throttling?  I guess there are some use cases for failing instead of succeeding when AWS starts throttling (like sleeping, then re-starting the polling), but I can't think of one which wouldn't be better served by simply succeeding in the first place.

**Comment by awood45** [comment] 2017-04-10 16:30
Something to help clarify (I gave a confusing response earlier) - our standard retry handling already retries throttling errors. If you're seeing the error, we've already retried multiple times and failed our retry limit before surfacing the error. Hence the recommendation to handle the throttling error by expanding retry periods. You do have a couple more advanced options to consider in your client configuration:

* Set your own [:retry_limit](http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudFormation/Client.html#initialize-instance_method). Our default is three. Set as you desire, but I don't think we'd want to retry indefinitely as you could create a never-terminating waiter.
* You can also provide a custom [:retry_backoff](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/plugins/retry_errors.rb#L16) lambda, if you want to bring your own retry backoff logic.

**Comment by JoeMcGuire** [comment] 2018-05-14 12:30
+1 for fixing, while we wait we have requested an API rate increase.

**Comment by M1strall** [comment] 2019-10-15 20:09
Facing a similar issues.
What is the name of this API limit?
