### ISSUE TITLE
Aws::S3::Client#copy_object raises Aws::Xml::Parser::ParsingError

### ISSUE THREAD

**Issue by itghlu** [aws/aws-sdk-ruby#2502] opened 2021-03-30 18:14 UTC
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
When calling `Aws::S3::Client#copy_object`, an exception is intermittently raised from the SDK:
```
Aws::Xml::Parser::ParsingError: XML declaration allowed only at the start of the document
aws-sdk-core-3.112.1/lib/aws-sdk-core/xml/parser/stack.rb:47:in `error'
aws-sdk-core-3.112.1/lib/aws-sdk-core/xml/parser/engines/nokogiri.rb:41:in `error'
nokogiri-1.9.1/lib/nokogiri/xml/sax/parser.rb:110:in `parse_with'
nokogiri-1.9.1/lib/nokogiri/xml/sax/parser.rb:110:in `parse_memory'
nokogiri-1.9.1/lib/nokogiri/xml/sax/parser.rb:83:in `parse'
aws-sdk-core-3.112.1/lib/aws-sdk-core/xml/parser/engines/nokogiri.rb:15:in `parse'
aws-sdk-core-3.112.1/lib/aws-sdk-core/xml/parser.rb:36:in `parse'
aws-sdk-core-3.112.1/lib/aws-sdk-core/rest/response/body.rb:45:in `parse'
aws-sdk-core-3.112.1/lib/aws-sdk-core/rest/response/body.rb:25:in `apply'
aws-sdk-core-3.112.1/lib/aws-sdk-core/rest/response/parser.rb:34:in `extract_body'
aws-sdk-core-3.112.1/lib/aws-sdk-core/rest/response/parser.rb:14:in `apply'
aws-sdk-core-3.112.1/lib/aws-sdk-core/rest/handler.rb:11:in `block in call'
aws-sdk-core-3.112.1/lib/seahorse/client/response.rb:46:in `block in on'
aws-sdk-core-3.112.1/lib/seahorse/client/http/response.rb:146:in `block in on_success'
aws-sdk-core-3.112.1/lib/seahorse/client/http/response.rb:173:in `call'
aws-sdk-core-3.112.1/lib/seahorse/client/http/response.rb:173:in `block in listener'
aws-sdk-core-3.112.1/lib/seahorse/client/http/response.rb:137:in `call'
aws-sdk-core-3.112.1/lib/seahorse/client/http/response.rb:137:in `on_done'
aws-sdk-core-3.112.1/lib/seahorse/client/http/response.rb:144:in `on_success'
aws-sdk-core-3.112.1/lib/seahorse/client/response.rb:45:in `on'
aws-sdk-core-3.112.1/lib/aws-sdk-core/rest/handler.rb:11:in `call'
aws-sdk-core-3.112.1/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
aws-sdk-core-3.112.1/lib/aws-sdk-core/plugins/endpoint_discovery.rb:80:in `call'
aws-sdk-core-3.112.1/lib/seahorse/client/plugins/endpoint.rb:47:in `call'
aws-sdk-core-3.112.1/lib/aws-sdk-core/plugins/param_validator.rb:26:in `call'
aws-sdk-s3-1.92.0/lib/aws-sdk-s3/plugins/arn.rb:73:in `call'
aws-sdk-core-3.112.1/lib/seahorse/client/plugins/raise_response_errors.rb:16:in `call'
aws-sdk-s3-1.92.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
aws-sdk-s3-1.92.0/lib/aws-sdk-s3/plugins/dualstack.rb:36:in `call'
aws-sdk-s3-1.92.0/lib/aws-sdk-s3/plugins/accelerate.rb:50:in `call'
aws-sdk-core-3.112.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
aws-sdk-core-3.112.1/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
aws-sdk-core-3.112.1/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
aws-sdk-core-3.112.1/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
aws-sdk-core-3.112.1/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
aws-sdk-core-3.112.1/lib/seahorse/client/plugins/response_target.rb:24:in `call'
aws-sdk-core-3.112.1/lib/seahorse/client/request.rb:72:in `send_request'
aws-sdk-s3-1.92.0/lib/aws-sdk-s3/client.rb:1274:in `copy_object'
```

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
```
aws-sdk-core (3.112.1)
aws-sdk-s3 (1.92.0)
```

**Version of Ruby, OS environment**
```
# ruby -v
ruby 2.2.8p477 (2017-09-14 revision 59906) [x86_64-linux]
```
**To Reproduce (observed behavior)**

The code related to the error is just a `Aws::S3::Client` calling the `copy_object` method:
```
client = Aws::S3::Client.new(region: 'us-east-1')
client.copy_object(
  bucket: DESTINATION_BUCKET,
  copy_source: SOURCE_BUCKET/SOURCE_KEY?versionId=SOURCE_VERSION_ID,
  key: DESTINATION_KEY
)
```

The client is used in a multithreaded script where a single `Aws::S3::Client` instance is shared between all threads. However, we have also tested creating a new `Aws::S3::Client` instance for each thread which resulted in the same error.

Logs from `http_wire_trace` show the bad responses have two `<?xml` tags:

```
<?xml version=\"1.0\" encoding=\"UTF-8\"?><?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<CopyObjectResult xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><LastModified>2021-03-30T03:46:24.000Z</LastModified><ETag>&quot;dde6aa8f2c282ed665c34b837d589618&quot;</ETag></CopyObjectResult>"
```

This reflects the error message from the raised exception.

The response code is always `HTTP/1.1 200 OK` for all requests. A correct response will log `read 234 bytes` while the malformed response logs `reading 272 bytes`, which might be expected since there was extra data. The copy object operation does succeed server-side since the objects related to these malformed responses can be found in the destination bucket.

This problem happens intermittently, but most frequently when the script runs for a longer period of time (6+ hours). It had been reproduced fairly consistently as long as the script is left running long enough.

**Expected behavior**
The XML response parsing error should not be raised when the copy object operation succeeds.

**Additional context**
* https://github.com/aws/aws-xray-sdk-ruby/issues/40 and https://github.com/aws/aws-sdk-ruby/issues/2180 reported the same issue with `Aws::S3::Client#copy_object` (no resolution). We are not using XRay as in these two reports though.
* https://github.com/aws/aws-sdk-ruby/issues/1870 reported a different XML response `ParsingError` with SQS `receive_message`. While the service and error message (`Extra content at the end of the document`) are not the same, it could potentially be related since it was also caused by extra data in the XML body (added to the end of the response body rather than the start).

**Comment by alextwoods** [comment] 2021-03-30 21:50
I'm looking into this now - trying to get a reproduction but haven't been able to yet.

One workaround is to switch the XML engine you are using - some of them are more forgiving than others. Based on the stacktrace, it looks like you have nokogiri loaded. If you add ox to your Gemfile, the AWS SDK will pick it up and use ox as the engine and it is a bit more forgiving and is able to parse the xml from the stack trace you included.

**Comment by alextwoods** [comment] 2021-03-30 22:46
Is there any chance these bad requests were retries?  You should be able to see something like:
`[Aws::S3::Client 200 0.572954 1 retries] ` in the logs.

**Comment by itghlu** [comment] 2021-03-30 23:36
From one of the recent script runs with the exception, there were no retry logs for `copy_object` requests.

One thing that was noted previously though, is that client debug logs like `[Aws::S3::Client 200 0.572954 1 retries]` are not logged for requests with the malformed XML. Only the `http_wire_trace` logs are available for them.

**Comment by itghlu** [comment] 2021-03-31 16:46
`ox` was able to parse the malformed XML as suggested. All logging was available since there were no errors. Some extra notes:
- The `Aws::S3::Client 200...` logs showed 0 retries for responses with the malformed XML.
- About 3M S3 objects were copied in the last test, and only 55 responses were bad so this seems like a rare occurrence.
- Nothing was obviously abnormal about the bad responses. Response times for these were all within the 3 second range, which is higher than the large majority between 0 and 2 seconds (~97%). However there were many hundred other responses with the similar or higher response times and did not have bad XML.

Possibly worth mentioning the `copy_object` requests were copying from us-west-2 to ap-southeast-2.

**Comment by alextwoods** [comment] 2021-03-31 16:56
Thanks for the extra details - that helps!  Glad `ox` was at least able to parse the malformed XML.  

I'll follow up with S3 on this, but I believe this may be an edge case behavior on their end.

**Comment by mullermp** [comment] 2021-04-30 23:04
S3 is aware of this, closing. Please re-open if there is any concern.

**Closed as completed by mullermp** 2021-04-30 23:04 UTC
Labels: service-api

**Comment by alextwoods** [comment] 2021-06-09 21:48
S3 has made a change to correct this issue and it should be deployed within the next couple of weeks.
