### ISSUE TITLE
FIPS Regions Should Be Easier to Find and Use

### ISSUE THREAD

**Issue by phene** [aws/aws-sdk-ruby#2496] opened 2021-03-22 18:00 UTC
Today, each service may or may not have a FIPS endpoint, and specifying the pseudo-region for that FIPS endpoint is not easy or straight-forward.

For example, if I want to use the FIPS endpoint for CloudFormation in us-west-2, I would need to specify the `us-west-2-fips` region. For EBS in the same region, I would need to specify `fips-us-west-2`. All of the necessary information is in aws-partitions's [endpoints.json](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-partitions/partitions.json), but it is not easy to query directly with `Aws::Partitions`

Common questions I would like to be able to ask `Aws::Partitions`:

1) Given a service, what is the relevant FIPS pseudo-region in a particular region?  (e.g. `Aws::Partitions.fips_region_for('cloudformation', 'us-west-2') #=> 'us-west-2-fips` ) Maybe return `nil` if none is available. This could also be a method on the partition itself: `Aws::Partitions.partition('aws').fips_region_for('cloudformation', 'us-west-2')`

I wrote my own method that does something similar, given what is available in `endpoints.json`:

```ruby
   def fips_region_if_exists(client, region)
      client_id = client.identifier.to_s
      %W[
        #{region}-fips
        fips-#{region}
      ].find do |fips_region|
        # This works because every FIPS endpoint has a corresponding `credentialScope` that specifies the 
        # non-FIPS version of the region. Otherwise, the original value is returned.
        Aws::Partitions::EndpointProvider.signing_region(fips_region, client_id) != fips_region 
      end || region
    end

    fips_region_if_exists(Aws::Route53::Client, 'aws-global') # => "fips-aws-global"
    fips_region_if_exists(Aws::CloudFormation::Client, 'us-west-2') # => "us-west-2-fips"
    fips_region_if_exists(Aws::EBS::Client, 'us-west-2') # => "fips-us-west-2"
    fips_region_if_exists(Aws::Personalize::Client, 'us-west-2') # => "us-west-2"
```

2) What are all of the regions and psuedo-regions for a given service?

`Aws::Partitions.partition('aws').service('CloudFormation').fips_regions # => list of fips regions`

Related issue: https://github.com/aws/aws-sdk-ruby/issues/2486

**Comment by mullermp** [comment] 2021-06-02 17:53
I haven't forgotten about this. I just wanted to give you an update. There's an on-going discussion about FIPS and how modeled endpoints should not have pseudo regions such as "fips-region". They should have never been introduced the way they currently are, and the problem is multiplied across all SDKs.

**Comment by mullermp** [comment] 2021-11-04 19:38
This has been addressed in https://github.com/aws/aws-sdk-ruby/pull/2553

I have exposed `fips_regions` and `dualstack_regions` in `Aws::Partitions`, along with `use_fips_endpoint` and `use_dualstack_endpoint` configurations. I've found a way to deprecate pseudo regions for all SDKs. A `fips` pseudo region will now be normalized and automatically set `use_fips_endpoint` to true. Please migrate away from these regions and use normal region and config instead.

**Closed as completed by mullermp** 2021-11-04 19:38 UTC
Labels: feature-request
