### ISSUE TITLE
Aws::IoTDataPlane::Errors::ForbiddenException

### ISSUE THREAD

**Issue by lsilvs** [aws/aws-sdk-ruby#1052] opened 2016-01-11 15:02 UTC
I'm trying to use the ruby sdk in order to get the shadow of my Thing but I'm getting the following error:

Code used:
```ruby
client = Aws::IoTDataPlane::Client.new(
  endpoint: 'https://data.iot.eu-west-1.amazonaws.com',
  region: 'eu-west-1',
  credentials: credentials,
)
```

Error returned:
```ruby
Credential should be scoped to a valid region, not 'iot.eu-west-1'
```

Is the endpoint I'm using correct?

**Comment by trevorrowe** [comment] 2016-01-11 18:14
I think this may be an issue with how the service's regional signing name is extracted from the endpoint:
https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/plugins/request_signer.rb#L53

To demonstrate:

```ruby
client = Aws::IoTDataPlane::Client.new(
  endpoint: 'https://data.iot.eu-west-1.amazonaws.com',
  region: 'eu-west-1',
)
cilent.config.sigv4_region
#=> "io.eu-west-1" -- oops, should be "eu-west-1"
```

This shouldn't be to difficult to fix. Thank you for reporting the issue.

**Comment by awood45** [comment] 2016-01-11 23:16
Pushed the fix, will go out with the next release.

**Closed by awood45** 2016-01-11 23:16 UTC
Labels: bug, Version 2

**Comment by lsilvs** [comment] 2016-01-12 16:04
Tested and approved.

Cheers,

**Comment by lsilvs** [comment] 2016-01-21 13:11
Hi @awood45 
seems that your commit '[Fix SigV4 Signing Region for Aws::IoTDataPlane](https://github.com/aws/aws-sdk-ruby/commit/804d0f8d43a67132ae149a3ad0690be4c52e6022)' solved the problem but the commit '[Simplify Request Signer Region Assignment](https://github.com/aws/aws-sdk-ruby/commit/b0cb55845802955617bace5718219d6c0df83167)' brought it back.

Can you check it out, pls

**Comment by awood45** [comment] 2016-01-21 17:51
I can't reproduce an error, here is what I'm seeing with the latest version (using `aws.rb`):
```ruby
Aws> client = Aws::IoTDataPlane::Client.new(region: "us-east-1", endpoint: "https://#{iot.describe_endpoint.endpoint_address}")
[Aws::IoT::Client 200 0.67704 0 retries] describe_endpoint()
=> #<Aws::IoTDataPlane::Client>
Aws> client.config.sigv4_region
=> "us-east-1"
Aws> client.publish(topic: "foo")
[Aws::IoTDataPlane::Client 200 0.786854 0 retries] publish(topic:"foo")
=> #<struct Aws::EmptyStructure>
```
Can you give me a failing example to work off of? Your original failing example also appears to work fine for me.

**Comment by lsilvs** [comment] 2016-01-22 15:10
I'm using the region 'eu-west-1' and getting the error:
```
Aws::IoTDataPlane::Errors::ForbiddenException (Credential should be scoped to a valid region, not 'us-east-1'. )
```

Seems that it's only working for ' us-east-1'

**Comment by awood45** [comment] 2016-01-22 17:18
That makes sense, I'm able to recreate that. Going to create a separate tracking issue since this may go beyond IoT.
