### ISSUE TITLE
dry_run ignored on Aws::EC2::Instance#wait_until_stopped

### ISSUE THREAD

**Issue by Affix** [aws/aws-sdk-ruby#1140] opened 2016-03-23 15:58 UTC
Today I was writing a Script to Restore snapshots using Aws::EC2::Resource.

```
#!/usr/bin/env ruby

require 'aws-sdk'
require 'json'

ec2 = Aws::EC2::Resource.new

ec2.instances.each do | i |
  begin
    i.wait_until_stopped({
      dry_run: true,
      instance_ids: [i.id],
      max_results: 1
    })
  rescue Aws::EC2::Errors::DryRunOperation
    puts "DryRun No Changed Made"
  end
end
```

Expected : 
Instance Stays Running 
Aws::EC2::Errors::DryRunOperation

Actual: 
Instance Stopped
No Output

**Comment by Affix** [comment] 2016-03-23 16:05
Edits are the benefits of using 2 computers to submit this bug...

**Comment by awood45** [comment] 2016-03-23 16:13
I see what you're saying about the `:dry_run` flag not being passed through, but what do you mean about the instance stopping? That code snippet above will only call `Aws::EC2::Client#describe_instances`.

**Comment by Affix** [comment] 2016-03-23 16:17
@awood45 

By doing

```
ec2.instances.each do | i |
```

i is returned as an instance object. So calling wait_for_stopped on the instance resource object stops the instance. I have misunderstood the documentation in that case.

But my instance ended up stopping and I don't understand how or why it stopped then.

**Comment by awood45** [comment] 2016-03-23 16:34
To clarify, your example above is functionally equivalent to:

```ruby
#!/usr/bin/env ruby

require 'aws-sdk'
require 'json'

ec2 = Aws::EC2::Resource.new
client = ec2.client

ec2.instances.each do | i |
  begin
    client.wait_until(:instance_stopped, instance_ids: [i.id])
  rescue Aws::EC2::Errors::DryRunOperation
    puts "DryRun No Changed Made"
  end
end
```

That code will only make an API call to `#describe_instances`. Adding wire tracing to your resource instantiation can show this:

```ruby
ec2 = Aws::EC2::Resource.new(http_wire_trace: true)
```

Incidentally, the following code should give you your intended behavior:

```ruby
#!/usr/bin/env ruby

require 'aws-sdk'
require 'json'

ec2 = Aws::EC2::Resource.new
client = ec2.client

ec2.instances.each do | i |
  begin
    client.wait_until(:instance_stopped, instance_ids: [i.id], dry_run: true)
  rescue Aws::EC2::Errors::DryRunOperation
    puts "DryRun No Changed Made"
  end
end
```

**Comment by Affix** [comment] 2016-03-23 16:36
Thanks for the very quick response to this! @awood45 quite impressed

**Comment by awood45** [comment] 2016-03-23 16:46
Your point about us not plumbing the parameters to the waiter stands, at the very least it's not clear that this is the behavior.

However, as a matter of helping with your use case, I'm not sure that passing `:dry_run` to `#describe_instances` is necessary in your case, if I'm understanding it correctly. To be clear, `:wait_until_stopped` **DOES NOT** stop the instance. It won't make changes, it will poll for changes.

To stop an instance, and block until the instance is in a stopped state, you'd do the following (this is obviously not a dry run):

```ruby
#!/usr/bin/env ruby

require 'aws-sdk'

ec2 = Aws::EC2::Resource.new

ec2.instances.each do | i |
  i.stop
  i.wait_until_stopped
end
```

Hopefully this unblocks you.

**Comment by awood45** [comment] 2016-03-23 17:04
I can see where the [documentation](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Instance.html#wait_until_stopped-instance_method) could be more clear on this method. The instance ID of your resource instance is passed through on your behalf, you do not need to add it like in your earlier example.

**Comment by awood45** [comment] 2016-03-23 21:31
I've added a pull request to fix the documentation. At this point, we don't plan to support adding extra parameters to resource waiter calls, as there isn't a case we know of where it is needed at this point. In your case, it does not appear that you need `:dry_run` as you're calling a side-effect free method.

Resolving this, feel free to reach out again if you need any other help.

**Closed by awood45** 2016-03-23 21:31 UTC
Labels: Version 2
