### ISSUE TITLE
Fix INI parsing of whitespace preceding config key

### ISSUE THREAD

**Issue by jordanrmerrick** [aws/aws-sdk-ruby#3058] opened 2024-07-01 19:55 UTC
### Describe the bug

Whitespace before a key, specifically a key after a profile in the config file, causes the ini parser to fail. Per the [TOML spec](https://github.com/toml-lang/toml/blob/main/toml.md#keyvalue-pair), whitespace around (before _and_ after) keys and values should be ignores.

 This profile works correctly:
```
[profile my-profile]
output = json
region = us-west-2
...
```

This profile fails with `aws-sdk-core-3.197.0/lib/aws-sdk-core/ini_parser.rb:28:in `block in ini_parse': undefined method `[]' for nil:NilClass (NoMethodError)`:
```
[profile my-profile]
    output = json
region = us-west-2
```

### Expected Behavior

A profile with whitespace before a key should be parsed correctly.

```
[profile my-profile]
    output = json
region = us-west-2
```
Should be parsed into
```
profile=my-profile
output=json
region=us-west-2
```

### Current Behavior

A profile with whitespace before a key is not parsed correctly.
```
 [profile my-profile]
 output = json
 region = us-west-2
```
Results in the error
```
aws-sdk-core-3.197.0/lib/aws-sdk-core/ini_parser.rb:28:in `block in ini_parse': undefined method `[]' for nil:NilClass (NoMethodError)
```

### Reproduction Steps

1. Add a profile to your config file, typically found at `$HOME/.aws/config`. It should contain whitespace before the first key, e.g. 
    ```
    [profile my-profile]
        output = json
    region = us-west-2
    ```

2. Try to call IniParser::ini_parse with the file's contents
    ```
    IniParser::ini_parse(File.read("<your-config-path>"))
    ```

### Possible Solution

The `item` and `prefix` [regex patterns](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/aws-sdk-core/ini_parser.rb#L23-L24) can be modified to accommodate whitespace before keys.

```
item = line.match(/^(.+?)\s*=\s*(.+?)\s*$/)
prefix = line.match(/^(.+?)\s*=\s*$/)
```

Can be modified to
```
item = line.match(/^\s*(.+?)\s*=\s*(.+?)\s*$/)
prefix = line.match(/^\s*(.+?)\s*=\s*$/)
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core 3.197

### Environment details (Version of Ruby, OS environment)

Ruby 2.7, MacOS

**Comment by jterapin** [comment] 2024-07-01 21:35
Thank you for submitting the ticket. We will be taking a look.

**Comment by jordanrmerrick** [comment] 2024-07-02 12:50
I don't actually think this is so simple, I didn't consider nested configurations (i.e., services). I'm curious what you expect is the right behavior here. In this scenario, there is no nested configuration. Are top level properties permitted to be indented? 

Example:
```
[profile my-profile]
    region=us-east-1 # This fails right now
s3 =
  region = us-west-2
```

**Comment by jterapin** [comment] 2024-07-02 17:48
I'm currently under the impression that the whitespaces on the top level properties _should_ be ignored based on some guidelines set across AWS SDKs. We are still investigating so stay tuned.

**Comment by jterapin** [comment] 2024-07-03 14:33
Update: We now have an internal ticket to resolve this bug and improve tests to cover edge cases.

**Comment by mullermp** [comment] 2024-07-04 13:55
This may take a long time to fix because it's not straight forward. In fact I see many issues with our ini parsing in relation to other SDKs. My best advice would be to fix the config file as this will take some time to change and we'd like to fully align with the specification. I think the Ruby SDKs implementation predates that specification as such.

**Comment by mullermp** [comment] 2024-07-08 17:39
I confirmed with the internal specification that this preceding space is NOT part of the specification and this is not a bug. INI specifications are generally not universal. I am closing this. The recommended fix is to fix your formatting as you've already pointed out. We've taken a backlog item to improve other parsing cases outlined in the internal specification not related to this specific issue.

**Closed as completed by mullermp** 2024-07-08 17:39 UTC
Labels: bug, queued
