### ISSUE TITLE
aws-partitions 1.856.0 no longer be found in that source

### ISSUE THREAD

**Issue by enescakir** [aws/aws-sdk-ruby#2955] opened 2023-11-23 11:31 UTC
### Describe the bug

Dependabot bumped `aws-partitions` gem from `1.854.0` to `1.856.0`.

Bundler can't download the `1.856.0` version.

https://github.com/ubicloud/ubicloud/pull/922

### Expected Behavior

Be able to download `aws-partitions 1.856.0` gem

### Current Behavior

Bundler fails with following error:

```
Your bundle is locked to aws-partitions (1.856.0) from rubygems repository https://rubygems.org/ or installed locally, but that version can no longer be found in that source. That means the author of aws-partitions (1.856.0) has removed it. You'll need to update your bundle to a version other than aws-partitions (1.856.0) that hasn't been
removed in order to install.
```

### Reproduction Steps

- Add `aws-partitions (1.856.0)` to your Gemfile
- Run `bundle install`

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-partitions

### Environment details (Version of Ruby, OS environment)

ruby 3.2.2

**Comment by mullermp** [comment] 2023-11-23 12:49
That is strange. I see them listed here: https://rubygems.org/gems/aws-partitions/versions

But they look to be missing from the RubyGems index: https://index.rubygems.org/versions

I'll reach out to the RubyGems.org staff - you should also do that.

EDIT - looks like it is in the index at the bottom:
```
aws-partitions 1.856.0 872d29a0921968c6295ef6b28e165d36
```

**Comment by mullermp** [comment] 2023-11-23 12:58
I've confirmed reproduction in a Ruby > 2.3 or 2.4. My error is:

```
Could not find gem 'aws-partitions (= 1.856.0)' in any of the gem sources listed in your Gemfile.
```

with a Gemfile:

```
source "https://rubygems.org"

gem 'aws-partitions', '1.856.0'
```

**Comment by mullermp** [comment] 2023-11-23 13:03
In the mean time, please pin to 1.855.0 or sooner.

**Comment by mullermp** [comment] 2023-11-23 13:10
`gem install aws-partitions --version 1.856.0` seems to work however.

**Comment by enescakir** [comment] 2023-11-23 13:40
It looks interesting. `gem` is able to find this version but `bundler` can't find it.

```
$ gem list aws-partitions --remote --all

*** REMOTE GEMS ***

aws-partitions (1.856.0, 1.855.0, 1.854.0, 1.853.0, 1.852.0, 1.851.0, 1.850.0, 1.849.0, 1.848.0 ......
```

**Comment by simi** [comment] 2023-11-23 17:38
Hello @enescakir and @mullermp. It seems this was problem on RubyGems.org compact index side and this version was missing at https://index.rubygems.org/info/aws-partitions. I have regenerated info file for `aws-partitions` gem and it includes this version now. Can you please check the issue was fixed by this?

**Comment by mullermp** [comment] 2023-11-23 17:49
Thank you @simi ! It looks to be downloadable now with `bundle install`. Can you confirm with the minimal repro?

@enescakir Please re-open if there's still an issue.

**Closed as completed by mullermp** 2023-11-23 17:49 UTC
Labels: bug, needs-triage
