### ISSUE TITLE
questions regarding autoscaling waiter conditions

### ISSUE THREAD

**Issue by quiver** [aws/aws-sdk-ruby#1109] opened 2016-02-28 17:30 UTC
I was about to implement autoscaling waiters for [aws-cli ](https://github.com/aws/aws-cli) and found that you've recently [implemented it](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/apis/autoscaling/2011-01-01/waiters-2.json).
I have questions about specifications of autoscaling waiters, more specifically, `acceptors` conditions for success cases.
(I've just copied ruby-sdk's autoscaling waiter JSON to aws-cli source tree and tested from aws-cli, not from ruby-sdk.)

### condition

```
{
  "argument": "length(AutoScalingGroups)",
  "expected": 1,
  "matcher": "pathAll",
  "state": "success"
},
```

`"length(AutoScalingGroups)"` returns a scalar value and  mather `pathAll` expects list arguments.

I think this should be
```
{
  "argument": "length(AutoScalingGroups)",
  "expected": 1,
  "matcher": "path",  // CHANGED
  "state": "success"
}
```

Same for `GroupNotExists` API.

### condition
Success condition is that ASG has  at least `MinSize` `InService` instances.

```
{
  "argument": "contains(AutoScalingGroups[].[length(Instances[?LifecycleState=='InService']) >= MinSize][], `false`)",
  "expected": false,
  "matcher": "pathAll",
  "state": "success"
},
```

`AutoScalingGroups[].[length(Instances[?LifecycleState=='InService']) >= MinSize][]` returns a list and `contains(AutoScaling ...)` returns a boolean value, but mather `pathAll` expects list arguments.

I think this should be
```
{
  "argument": "contains(AutoScalingGroups[].[length(Instances[?LifecycleState=='InService']) >= MinSize][], `false`)",
  "expected": false,
  "matcher": "path",
  "state": "success"
},
```
or 
```
{
  "argument": "AutoScalingGroups[].[length(Instances[?LifecycleState=='InService']) >= MinSize][]",
  "expected": true,
  "matcher": "pathAll",
  "state": "success"
}
```

My revised autoscaling waiter.json and a `DescribeAutoScalingGroups` sample output file can be found here https://gist.github.com/quiver/fca4dc97d7d5be04cf79#file-waiters-2-json.

Or am I missing something?

**Comment by awood45** [comment] 2016-02-29 18:17
I'm going to check if there is any unexpected behavior from the waiters as written. I do know that some matcher types end up behaving in de facto the same manner, so it may not be an issue (even if not semantically optimal). I don't recall off the top of my head (returning from vacation too) which matchers are which, so I'll be looking at differences in behavior if any.

**Comment by awood45** [comment] 2016-02-29 22:09
This is a good catch - the waiter will likely just cycle on false for a scalar with a pathAll matcher.

I'm already going to be touching Auto Scaling resources to fix another bug, so I will test and push the fix for this - no need for a PR, unless it's already done and tested.

**Comment by quiver** [comment] 2016-03-01 03:22
@awood45 
> I'm already going to be touching Auto Scaling resources to fix another bug, so I will test and push the fix for this - no need for a PR, unless it's already done and tested.

I don't have a work-in-progress PR, so please do.
Thank you for your quick response. I really need this feature!

**Comment by awood45** [comment] 2016-03-01 20:52
I've written a fix for this that will work in the case of requesting exactly one Auto Scaling group. Unfortunately, due to waiter/JMESPath limitations, if you have multiple Auto Scaling groups in a single request, something like `:group_exists` will return a success response if at least one group exists.

You can avoid this by always specifying a single group in your waiter requests.

**Closed by awood45** 2016-03-01 20:52 UTC
Labels: bug, Version 2

**Comment by quiver** [comment] 2016-03-02 02:40
:clap:
