### ISSUE TITLE
SDK version 3 erroneously requires :is_truncated for route53 list_resource_record_sets

### ISSUE THREAD

**Issue by fdr** [aws/aws-sdk-ruby#1654] opened 2017-10-30 23:20 UTC
The latest vintages of version 2 is fine, and version 3 works against a real R53 endpoint, but not in tests. Code to reproduce:

```ruby
require 'aws-sdk'
Aws.config[:stub_responses] = true
r53 = Aws::Route53::Client.new(region: 'us-west-2')
r53.list_resource_record_sets(
  hosted_zone_id: 'abc',
  start_record_name: 'def',
)
```

Yields:

```
ArgumentError: missing required parameter params[:is_truncated]
from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/param_validator.rb:32:in `validate!'
```

Should yield: empty or default response.

Notably, `is_truncated` is a response field, not a request field.

**Comment by cjyclaire** [comment] 2017-10-30 23:28
Hmm, using the same code snippet with same API, I cannot reproduce the error in V3

**Comment by fdr** [comment] 2017-10-30 23:44
Well...I can? 100%. Here's the full trace.

```
ArgumentError: missing required parameter params[:is_truncated]
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/param_validator.rb:32:in `validate!'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/param_validator.rb:13:in `validate!'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/client_stubs.rb:257:in `data_to_http_resp'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/client_stubs.rb:242:in `http_response_stub'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/client_stubs.rb:209:in `default_stub'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/client_stubs.rb:197:in `block in next_stub'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/client_stubs.rb:194:in `synchronize'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/client_stubs.rb:194:in `next_stub'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/stub_responses.rb:43:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/seahorse/client/plugins/content_length.rb:12:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/signature_v4.rb:64:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/rest/handler.rb:8:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-route53-1.3.0/lib/aws-sdk-route53/plugins/id_fix.rb:23:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-route53-1.3.0/lib/aws-sdk-route53/client.rb:3305:in `list_resource_record_sets'
	from (irb):5
	from /home/fdr/.rbenv/versions/2.4.2/bin/irb:11:in `<main>'

```

**Comment by cjyclaire** [comment] 2017-10-31 00:27
@fdr Ah I see, sorry for the confusion, this is about the stubbed response instead if a real API call. I can reproduce this, taking a look

**Comment by cjyclaire** [comment] 2017-11-02 04:14
Sorry for the late response, so this is a problem with our empty struct for stubs. PR #1655 is opened and is under review.

**Comment by fdr** [comment] 2017-11-03 20:48
Oh, no problems. Thanks.

**Comment by cjyclaire** [comment] 2017-11-03 21:51
PR has been merged, will be included in the next release.

**Comment by cjyclaire** [comment] 2017-11-07 18:53
The fix is out in the latest release for [`core`](https://rubygems.org/gems/aws-sdk-core/versions/3.6.1), closing, feel free to reopen with further comments or questions

**Closed by cjyclaire** 2017-11-07 18:53 UTC
Labels: pr-in-progress, Version 3
